import { MultilingualModelDescription } from '../../types/descriptionTypes';

export const dualShaftDescriptions: { [modelName: string]: MultilingualModelDescription } = {
    'CS-20': {
        tr: {
            intro: 'CS-20 çift şaftlı parçalama makinesi, küçük ölçekli geri dönüşüm tesisleri, pilot projeler ve start-up işletmeler için özel olarak tasarlanmış kompakt, ekonomik ve güvenilir bir parçalama çözümüdür.',
            paragraph1: 'CS-20 çift şaftlı parçalama makinesi, 2x7.5 kW çift motor sistemi ile 400 mm rotor uzunluğu ve 200 mm rotor çapına sahiptir. 300-500 kg/saat işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında güvenilir performans sağlar. PET şişeler, PP-PE malzemeler, plastik film atıkları, karton-kağıt, hafif metal ve küçük ahşap parçaların parçalanmasında etkili performans gösterir. Düşük hız-yüksek tork prensibi ile çalışan çift şaftlı parçalama makinesi, malzeme sıkışmalarını önler ve homojen parçalama sağlar.',
            paragraph2: 'Basit kullanımlı kontrol paneli ve güvenlik sistemleri ile donatılmış CS-20 çift şaftlı parçalama makinesi, sınırlı alanlarda bile verimli çalışır. 32 adet değiştirilebilir bıçak ve ayarlanabilir elek sistemi (30-80 mm) ile farklı materyal türlerine kolayca uyum sağlar. Plastik kırma makinesi ve hurda plastik kırma makinası işlevlerini ekonomik bir paket içinde sunan bu sistem, düşük enerji tüketimi sayesinde işletme maliyetlerini minimize eder. Otomatik ters çalışma fonksiyonu ile sıkışma durumlarında kesintisiz çalışma garantisi verir.',
            paragraph3: 'MT Makina CS-20 katı atık parçalama makinası, küçük plastik geri dönüşüm atölyeleri, kağıt-karton toplama merkezleri, ambalaj atığı işleme birimleri ve yerel atık yönetim merkezleri için idealdir. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak kompakt tasarımı sayesinde kolay montaj ve hızlı kurulum imkanı sunar. Senkronize çalışan çift şaft yapısı sayesinde palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında da güvenle kullanılabilir.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-20, plastik hurda kırma makinası, balya parçalama makinası ve kauçuk parçalama makinası uygulamalarında da etkili sonuçlar verir. Kompakt boyutlarına rağmen endüstriyel dayanıklılık sunan bu sistem, güçlü şaft yapısı ve dayanıklı bıçak sistemi ile uzun ömür garantisi verir. Katı atık parçalama makinası fiyatları açısından giriş seviyesi yatırımlar için ekonomik bir başlangıç noktası sunar.',
            paragraph5: 'Enerji verimliliği sunan CS-20 çift şaftlı parçalama makinesi, işletme maliyetlerini minimize ederek yüksek yatırım getirisi sağlar. Plastik kırma makinesi fiyatları konusunda rekabetçi fiyatlandırma sunan bu sistem, küçük ölçekli geri dönüşüm projeleri ve pilot tesisler için ideal bir yatırımdır. Tahliye helezonları ve konveyör bantları ile entegre edilebilir. CE sertifikalı güvenlik standartları ve 1 yıl garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-20 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek küçük işletmelere yüksek verimlilik ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi ve teknik danışmanlık hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için bizimle iletişime geçin. CS-20, küçük ölçekli tesisler ve start-up projeler için mükemmel bir başlangıç yatırımıdır.'
        },
        en: {
            intro: 'CS-20 dual shaft shredder is a compact, economical and reliable shredding solution specially designed for small-scale recycling facilities, pilot projects and start-up businesses.',
            paragraph1: 'CS-20 dual shaft shredder features 2x7.5 kW dual motor system with 400 mm rotor length and 200 mm rotor diameter. With 300-500 kg/hour processing capacity, it provides reliable performance in plastic shredder, fabric shredder, paper shredder and pallet shredder applications. Shows effective performance in shredding PET bottles, PP-PE materials, plastic film waste, cardboard-paper, light metal and small wood pieces.',
            paragraph2: 'CS-20 dual shaft shredder equipped with easy-to-use control panel and safety systems operates efficiently even in limited spaces. With 32 replaceable blades and adjustable screen system (30-80 mm), it easily adapts to different material types. This system minimizes operating costs with low energy consumption. Automatic reverse function guarantees uninterrupted operation in case of jams.',
            paragraph3: 'MT Makina CS-20 solid waste shredder is ideal for small plastic recycling workshops, paper-cardboard collection centers, packaging waste processing units and local waste management centers. As a plastic shredding machine and recycling crusher, its compact design offers easy assembly and quick installation.',
            paragraph4: 'With dual shaft shredder technology, CS-20 also provides effective results in plastic scrap crusher, bale shredder and rubber shredder applications. Despite its compact dimensions, this system offers industrial durability with strong shaft structure and durable blade system, guaranteeing long life.',
            paragraph5: 'CS-20 dual shaft shredder offering energy efficiency provides high return on investment by minimizing operating costs. This system is an ideal investment for small-scale recycling projects and pilot facilities. Can be integrated with discharge screws and conveyor belts. Supported by CE certified safety standards and 1-year warranty.',
            paragraph6: 'CS-20 dual shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits to small businesses by optimizing recycling processes. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes and technical consultancy services. CS-20 is an excellent starter investment for small-scale facilities and start-up projects.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-20 - компактное, экономичное и надежное решение, специально разработанное для малых предприятий по переработке, пилотных проектов и стартапов.',
            paragraph1: 'Двухвальный измельчитель CS-20 оснащен системой с двумя двигателями 2x7,5 кВт с длиной ротора 400 мм и диаметром ротора 200 мм. С производительностью обработки 300-500 кг/час обеспечивает надежную работу в применениях измельчителя пластика, ткани, бумаги и поддонов.',
            paragraph2: 'Двухвальный измельчитель CS-20, оснащенный простой панелью управления и системами безопасности, эффективно работает даже в ограниченном пространстве. С 32 сменными ножами и регулируемой системой сит (30-80 мм) легко адаптируется к различным типам материалов.',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-20 идеально подходит для небольших мастерских по переработке пластика, центров сбора бумаги и картона, подразделений по переработке упаковочных отходов и местных центров управления отходами.',
            paragraph4: 'С технологией двухвального измельчителя CS-20 также обеспечивает эффективные результаты в применениях дробилки пластикового лома, измельчителя тюков и измельчителя резины. Несмотря на компактные размеры, эта система предлагает промышленную долговечность.',
            paragraph5: 'Двухвальный измельчитель CS-20, предлагающий энергоэффективность, обеспечивает высокую отдачу от инвестиций за счет минимизации эксплуатационных расходов. Может интегрироваться с разгрузочными шнеками и конвейерными лентами. Поддерживается сертификатом CE и гарантией 1 год.',
            paragraph6: 'Двухвальный измельчитель CS-20, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность и экологические преимущества малому бизнесу. MT Makina, ведущий производитель измельчителей в Турции, предлагает ценовые предложения и технические консультации.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-20 هي حل مدمج واقتصادي وموثوق مصمم خصيصاً لمرافق إعادة التدوير صغيرة الحجم والمشاريع التجريبية والشركات الناشئة.',
            paragraph1: 'تتميز آلة التمزيق ثنائية العمود CS-20 بنظام محرك مزدوج 2×7.5 كيلووات مع طول دوار 400 مم وقطر دوار 200 مم. بسعة معالجة 300-500 كجم/ساعة، توفر أداءً موثوقاً في تطبيقات تمزيق البلاستيك والأقمشة والورق والمنصات.',
            paragraph2: 'آلة التمزيق ثنائية العمود CS-20 المجهزة بلوحة تحكم سهلة الاستخدام وأنظمة السلامة تعمل بكفاءة حتى في المساحات المحدودة. مع 32 شفرة قابلة للاستبدال ونظام شاشة قابل للتعديل (30-80 مم)، تتكيف بسهولة مع أنواع المواد المختلفة.',
            paragraph3: 'آلة تمزيق النفايات الصلبة MT Makina CS-20 مثالية لورش إعادة تدوير البلاستيك الصغيرة ومراكز جمع الورق والكرتون ووحدات معالجة نفايات التعبئة والتغليف ومراكز إدارة النفايات المحلية.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-20 أيضاً نتائج فعالة في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط. على الرغم من أبعادها المدمجة، توفر هذه الآلة متانة صناعية.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-20 التي توفر كفاءة الطاقة تحقق عائداً مرتفعاً على الاستثمار من خلال تقليل تكاليف التشغيل. يمكن دمجها مع براغي التفريغ وأحزمة النقل. مدعومة بمعايير السلامة المعتمدة CE وضمان سنة واحدة.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-20 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية للشركات الصغيرة. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وخدمات استشارية تقنية.'
        }
    },
    'CS-40': {
        tr: {
            intro: 'CS-40 çift şaftlı parçalama makinesi, orta ölçekli işletmeler ve geri dönüşüm tesisleri için güvenilir, verimli ve ekonomik bir parçalama çözümü sunan profesyonel bir sistemdir.',
            paragraph1: 'CS-40 çift şaftlı parçalama makinesi, 2x11 kW çift motor gücü ile 600 mm rotor uzunluğu ve 250 mm rotor çapı sunarak dengeli parçalama performansı sağlar. 500-800 kg/saat işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında üstün verimlilik gösterir. Plastik şişeler, PP-PE malzemeler, karton kutular, ahşap paletler, hafif metal atıklar ve tekstil döküntülerinin parçalanmasında etkili performans sergiler. Düşük hız-yüksek tork prensibi ile çalışan çift şaftlı parçalama makinesi, homojen ve kontrollü parçalama garantisi verir.',
            paragraph2: 'Yarı-otomatik kontrol sistemi, aşırı yük koruması ve acil durdurma butonu ile donatılmış CS-40 çift şaftlı parçalama makinesi, güvenli çalışma ortamı sunar. 48 adet yüksek mukavemetli bıçak ve ayarlanabilir elek sistemi (30-100 mm) ile farklı çıkış boyutları elde edilebilir. Plastik kırma makinesi ve hurda plastik kırma makinası işlevlerini tek bir sistemde birleştiren CS-40, otomatik ters çalışma fonksiyonu ile sıkışma durumlarında kesintisiz çalışma garantisi verir.',
            paragraph3: 'MT Makina CS-40 katı atık parçalama makinası, plastik toplama merkezleri, ambalaj atığı işleme tesisleri, ahşap atık geri dönüşümü ve karma atık ön işleme üniteleri için optimize edilmiştir. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak kompakt boyutlara rağmen sağlam çelik gövde yapısı uzun ömür garantisi verir. Senkronize çalışan çift şaft yapısı sayesinde palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında da güvenle kullanılabilir.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-40, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında da etkili sonuçlar verir. Orta ölçekli tesisler için optimize edilmiş bu sistem, güçlü şaft yapısı ve dayanıklı bıçak sistemi ile uzun ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından yüksek performans-maliyet dengesi sağlar. Tahliye helezonları, konveyör bantları ve metal ayırıcılar ile entegre edilebilir.',
            paragraph5: 'Enerji verimliliği sunan CS-40 çift şaftlı parçalama makinesi, işletme maliyetlerini minimize ederek yüksek yatırım getirisi sağlar. Plastik kırma makinesi fiyatları konusunda rekabetçi fiyatlandırma sunan bu sistem, orta ölçekli geri dönüşüm projeleri ve genişleyen tesisler için ideal bir yatırımdır. CE sertifikalı güvenlik standartları ve 2 yıl garanti ile desteklenir. Plastik geri dönüşüm tesisleri, ahşap işleme merkezleri ve endüstriyel atık yönetim tesisleri için profesyonel çözüm sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-40 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi ve teknik danışmanlık hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için bizimle iletişime geçin. CS-40, orta ölçekli tesisler için optimal maliyet-performans dengesi sunan profesyonel bir parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-40 dual shaft shredder is a reliable, efficient and economical shredding solution offering professional performance for medium-sized businesses and recycling facilities.',
            paragraph1: 'CS-40 model provides balanced shredding performance with 2x11 kW dual motor power, 600 mm rotor length and 250 mm rotor diameter. With 500-800 kg/hour processing capacity, it shows superior efficiency in plastic shredder, fabric shredder, paper shredder and pallet shredder applications.',
            paragraph2: 'Equipped with semi-automatic control system, overload protection and emergency stop button, CS-40 dual shaft shredder offers safe working environment. Different output sizes can be obtained with 48 high-strength blades and adjustable screen system (30-100 mm). Automatic reverse function guarantees uninterrupted operation in case of jams.',
            paragraph3: 'MT Makina CS-40 solid waste shredder is optimized for plastic collection centers, packaging waste processing facilities, wood waste recycling and mixed waste pre-processing units. Thanks to synchronized dual shaft structure, it can also be safely used in pallet shredder and fabric shredder applications.',
            paragraph4: 'With dual shaft shredder technology, CS-40 provides effective results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Optimized for medium-sized facilities, this system offers long life guarantee with strong shaft structure and durable blade system.',
            paragraph5: 'CS-40 dual shaft shredder offering energy efficiency provides high return on investment by minimizing operating costs. This system is an ideal investment for medium-scale recycling projects and expanding facilities. Supported by CE certified safety standards and 2-year warranty.',
            paragraph6: 'CS-40 dual shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits to businesses by optimizing recycling processes. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes and technical consultancy services. CS-40 is a professional shredding solution offering optimal cost-performance balance for medium-sized facilities.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-40 - надежное, эффективное и экономичное решение для предприятий среднего размера и перерабатывающих предприятий.',
            paragraph1: 'Модель CS-40 обеспечивает сбалансированную производительность измельчения с мощностью двойного двигателя 2x11 кВт, длиной ротора 600 мм и диаметром ротора 250 мм. С производительностью обработки 500-800 кг/час демонстрирует превосходную эффективность в применениях измельчителя пластика, ткани, бумаги и поддонов.',
            paragraph2: 'Оснащенный полуавтоматической системой управления, защитой от перегрузки и кнопкой аварийного останова, двухвальный измельчитель CS-40 обеспечивает безопасную рабочую среду. Различные размеры выхода могут быть получены с 48 высокопрочными ножами и регулируемой системой сит (30-100 мм).',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-40 оптимизирован для центров сбора пластика, предприятий по переработке упаковочных отходов, переработки древесных отходов и подразделений предварительной обработки смешанных отходов.',
            paragraph4: 'С технологией двухвального измельчителя CS-40 обеспечивает эффективные результаты в применениях дробилки пластикового лома, измельчителя тюков, измельчителя резины и измельчителя изношенных шин. Эта система предлагает долгий срок службы с прочной конструкцией вала.',
            paragraph5: 'Двухвальный измельчитель CS-40, предлагающий энергоэффективность, обеспечивает высокую отдачу от инвестиций за счет минимизации эксплуатационных расходов. Поддерживается сертификатом CE и гарантией 2 года.',
            paragraph6: 'Двухвальный измельчитель CS-40, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность и экологические преимущества предприятиям. MT Makina, ведущий производитель измельчителей в Турции, предлагает ценовые предложения и технические консультации.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-40 هي حل تمزيق موثوق وفعال للشركات متوسطة الحجم.',
            paragraph1: 'يوفر طراز CS-40 أداء تمزيق متوازنًا بقوة محرك مزدوج 2×11 كيلووات وطول دوار 600 مم وقطر دوار 250 مم.',
            paragraph2: 'مجهز بنظام تحكم شبه أوتوماتيكي وحماية من الحمل الزائد وزر إيقاف طوارئ، يوفر CS-40 بيئة عمل آمنة.',
            paragraph3: 'تم تحسين CS-40 لمراكز جمع البلاستيك ومرافق معالجة نفايات التعبئة والتغليف وإعادة تدوير نفايات الخشب.'
        }
    },
    'CS-60': {
        tr: {
            intro: 'CS-60 çift şaftlı parçalama makinesi, endüstriyel atık yönetiminde yüksek verimlilik sunan kompakt, güçlü ve çok yönlü bir parçalama çözümüdür.',
            paragraph1: 'CS-60 çift şaftlı parçalama makinesi, 2x15 kW çift motor konfigürasyonu ile 800 mm rotor uzunluğu ve 300 mm rotor çapına sahiptir. 800-1500 kg/saat işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında güvenilir performans sağlar. Plastik, metal, lastik, ahşap, cam ve evsel atıkların güvenli şekilde parçalanmasını sağlar. Düşük hız-yüksek tork prensibi ile çalışan çift şaftlı parçalama makinesi, zorlu malzemeleri bile kolayca işler ve enerji verimliliği sunar.',
            paragraph2: 'Gelişmiş PLC kontrol sistemi, otomatik ters çalışma fonksiyonu ve acil durum güvenlik sistemleri ile donatılmış CS-60 çift şaftlı parçalama makinesi, kesintisiz üretim garantisi verir. 64 adet özel alaşımlı bıçak ve değiştirilebilir elek sistemi (40-120 mm) ile farklı çıkış boyutları elde edebilirsiniz. Plastik kırma makinesi ve hurda plastik kırma makinası olarak senkronize çalışan çift şaft yapısı, malzeme sıkışmalarını önler ve dengeli kesim işlemi sağlar.',
            paragraph3: 'MT Makina CS-60 katı atık parçalama makinası, plastik geri dönüşüm tesisleri, metal hurda işleme merkezleri, lastik parçalama üniteleri, ahşap atık işleme ve evsel atık yönetim merkezleri için idealdir. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak kompakt tasarımı sayesinde orta ölçekli tesislere kolayca entegre edilir. Senkronize çalışan çift şaft yapısı sayesinde palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında da üstün performans gösterir.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-60, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında da etkili sonuçlar verir. Endüstriyel tesisler için optimize edilmiş bu sistem, güçlü şaft yapısı ve dayanıklı bıçak sistemi ile uzun ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından yüksek performans sunarak rekabetçi fiyatlandırma imkanı sağlar. Tahliye helezonları, konveyör bantları ve metal ayırıcılar ile entegre edilebilir.',
            paragraph5: 'Enerji verimliliği sunan CS-60 çift şaftlı parçalama makinesi, işletme maliyetlerini minimize ederek yüksek yatırım getirisi sağlar. Plastik kırma makinesi fiyatları konusunda orta sınıf bütçeler için uygun bir çözüm sunan bu sistem, büyüme potansiyeli olan tesisler için ideal bir yatırımdır. CE sertifikalı güvenlik standartları ve 2 yıl garanti ile desteklenir. Otomatik yağlama sistemi ve güçlendirilmiş rulman yapısı ile minimum bakım gerektirir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-60 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi ve teknik danışmanlık hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. CS-60, endüstriyel atık yönetimi ve geri dönüşüm tesisleri için güvenilir bir parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-60 dual shaft shredder is a compact, powerful and versatile shredding solution offering high efficiency in industrial waste management.',
            paragraph1: 'CS-60 model features 2x15 kW dual motor configuration with 800 mm rotor length and 300 mm rotor diameter. With 800-1500 kg/hour processing capacity, it ensures safe shredding of plastic, metal, tire, wood, glass and household waste. Working with low speed-high torque principle, it easily processes even difficult materials.',
            paragraph2: 'Equipped with advanced PLC control system, automatic reverse function and emergency safety systems, CS-60 guarantees uninterrupted production. Different output sizes can be obtained with 64 special alloy blades and replaceable screen system (40-120 mm). Synchronized dual shaft structure prevents material jams.',
            paragraph3: 'MT Makina CS-60 dual shaft shredder is ideal for plastic recycling facilities, metal scrap processing centers, tire shredding units, wood waste processing and household waste management centers. Compact design offers easy assembly and quick installation.',
            paragraph4: 'With dual shaft shredder technology, CS-60 provides excellent results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. This system offers industrial durability with strong shaft structure and durable blade system, guaranteeing long life.',
            paragraph5: 'CS-60 dual shaft shredder offering energy efficiency provides high return on investment by minimizing operating costs. Can be integrated with discharge screws, conveyor belts and metal separators. Supported by CE certified safety standards and 2-year warranty.',
            paragraph6: 'CS-60 dual shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits to businesses by optimizing recycling processes. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes and technical consultancy services.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-60 - компактное, мощное и универсальное решение, обеспечивающее высокую эффективность в управлении промышленными отходами.',
            paragraph1: 'Модель CS-60 оснащена конфигурацией двойного двигателя 2x15 кВт с длиной ротора 800 мм и диаметром ротора 300 мм. С производительностью обработки 800-1500 кг/час обеспечивает безопасное измельчение пластика, металла, шин, древесины, стекла и бытовых отходов.',
            paragraph2: 'Оснащенный усовершенствованной системой управления ПЛК, функцией автоматического реверса и системами аварийной безопасности, CS-60 гарантирует бесперебойное производство. Различные размеры выхода могут быть получены с 64 ножами из специального сплава и заменяемой системой сит (40-120 мм).',
            paragraph3: 'Двухвальный измельчитель MT Makina CS-60 идеально подходит для предприятий по переработке пластика, центров обработки металлолома, подразделений измельчения шин и центров управления бытовыми отходами.',
            paragraph4: 'С технологией двухвального измельчителя CS-60 обеспечивает отличные результаты в применениях дробилки пластикового лома, измельчителя тюков и измельчителя резины. Эта система предлагает промышленную долговечность с прочной конструкцией вала.',
            paragraph5: 'Двухвальный измельчитель CS-60, предлагающий энергоэффективность, обеспечивает высокую отдачу от инвестиций за счет минимизации эксплуатационных расходов. Поддерживается сертификатом CE и гарантией 2 года.',
            paragraph6: 'Двухвальный измельчитель CS-60, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность предприятиям. MT Makina, ведущий производитель измельчителей в Турции, предлагает ценовые предложения и технические консультации.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-60 هي حل مدمج وقوي ومتعدد الاستخدامات يوفر كفاءة عالية في إدارة النفايات الصناعية.',
            paragraph1: 'يتميز طراز CS-60 بتكوين محرك مزدوج 2×15 كيلووات مع طول دوار 800 مم وقطر دوار 300 مم. بسعة معالجة 800-1500 كجم/ساعة، يضمن التمزيق الآمن للبلاستيك والمعادن والإطارات والخشب والزجاج والنفايات المنزلية.',
            paragraph2: 'مجهز بنظام تحكم PLC متقدم ووظيفة عكسية تلقائية وأنظمة السلامة في حالات الطوارئ، يضمن CS-60 إنتاجًا متواصلاً. يمكن الحصول على أحجام مخرجات مختلفة مع 64 شفرة من السبائك الخاصة ونظام شاشة قابل للاستبدال (40-120 مم).',
            paragraph3: 'آلة التمزيق ثنائية العمود MT Makina CS-60 مثالية لمرافق إعادة تدوير البلاستيك ومراكز معالجة الخردة المعدنية ووحدات تمزيق الإطارات ومراكز إدارة النفايات المنزلية.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-60 نتائج ممتازة في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط. توفر هذه الآلة متانة صناعية مع هيكل عمود قوي.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-60 التي توفر كفاءة الطاقة تحقق عائداً مرتفعاً على الاستثمار من خلال تقليل تكاليف التشغيل. مدعومة بمعايير السلامة المعتمدة CE وضمان سنتين.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-60 توفر الاستدامة في إدارة النفايات وتقدم كفاءة عالية للشركات. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وخدمات استشارية تقنية.'
        }
    },
    'CS-80': {
        tr: {
            intro: 'CS-80 çift şaftlı parçalama makinesi, yüksek hacimli atık işleme gerektiren endüstriyel tesisler için güçlü, dayanıklı ve profesyonel bir parçalama çözümüdür.',
            paragraph1: 'CS-80 çift şaftlı parçalama makinesi, 2x22 kW yüksek performanslı çift motor sistemi ile 1000 mm rotor uzunluğu ve 350 mm rotor çapı sunarak ağır hizmet tipi uygulamalar için tasarlanmıştır. 1500-2500 kg/saat işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında üstün performans sağlar. Endüstriyel plastik konteynerler, kalın duvarlı borular, büyük ahşap paletler, otomotiv parçaları ve kompozit malzemelerin parçalanmasında benzersiz verimlilik gösterir.',
            paragraph2: 'Tam otomatik PLC kontrol paneli, gerçek zamanlı yük izleme, otomatik aşırı yük koruması ve çift yönlü ters çalışma fonksiyonu ile donatılmış CS-80 çift şaftlı parçalama makinesi, 7/24 kesintisiz çalışma kapasitesine sahiptir. 80 adet premium kalite bıçak ve çift elek sistemi (50-150 mm) ile hem kaba hem de orta boy parçalama yapılabilir. Plastik kırma makinesi ve hurda plastik kırma makinası olarak endüstriyel standartta performans sağlar. Senkronize çalışan çift şaft yapısı sayesinde malzeme sıkışmalarını tamamen önler.',
            paragraph3: 'MT Makina CS-80 katı atık parçalama makinası, büyük plastik geri dönüşüm tesisleri, otomotiv hurda işleme merkezleri, ahşap palet parçalama üniteleri ve endüstriyel atık yönetim tesisleri için optimize edilmiştir. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak modüler yapısı sayesinde konveyör besleyici, seperatör sistemleri ve elek üniteleri ile kolayca entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında da güvenle kullanılabilir.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-80, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında olağanüstü sonuçlar verir. Büyük ölçekli tesisler için optimize edilmiş bu sistem, güçlü şaft yapısı, takviyeli dişli kutusu ve dayanıklı bıçak sistemi ile uzun ömür ve yüksek performans garantisi sunar. Katı atık parçalama makinası fiyatları açısından yatırım maliyeti düşük, geri dönüş hızı yüksektir.',
            paragraph5: 'Enerji verimliliği sunan CS-80 çift şaftlı parçalama makinesi, işletme maliyetlerini minimize ederek yüksek yatırım getirisi sağlar. Plastik kırma makinesi fiyatları konusunda büyük projeler için ekonomik çözümler sunan bu sistem, profesyonel geri dönüşüm operasyonları için ideal bir yatırımdır. CE ve ISO sertifikalı güvenlik standartları ile 2 yıl garanti ile desteklenir. Otomatik yağlama sistemi, güçlendirilmiş rulman yapısı ve sağlam çelik gövde ile minimum bakım gerektirir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-80 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, teknik danışmanlık ve turnkey proje çözümleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. CS-80, ağır hizmet tipi endüstriyel projeler için tercih edilen güvenilir parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-80 dual shaft shredder is a powerful, durable and professional shredding solution for industrial facilities requiring high-volume waste processing.',
            paragraph1: 'CS-80 model is designed for heavy-duty applications with 2x22 kW high-performance dual motor system, 1000 mm rotor length and 350 mm rotor diameter. With 1500-2500 kg/hour processing capacity, it shows superior performance in plastic shredder, fabric shredder, paper shredder and pallet shredder applications.',
            paragraph2: 'Equipped with fully automatic PLC control panel, real-time load monitoring, automatic overload protection and bi-directional reverse function, CS-80 has 7/24 uninterrupted operation capacity. With 80 premium quality blades and dual screen system (50-150 mm), both coarse and medium shredding can be performed.',
            paragraph3: 'MT Makina CS-80 solid waste shredder is optimized for large plastic recycling facilities, automotive scrap processing centers, wooden pallet shredding units and industrial waste management facilities. Modular structure allows easy integration with conveyor feeders and separator systems.',
            paragraph4: 'With dual shaft shredder technology, CS-80 provides extraordinary results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. This system offers long life and high performance guarantee with strong shaft structure and reinforced gearbox.',
            paragraph5: 'CS-80 dual shaft shredder offering energy efficiency provides high return on investment by minimizing operating costs. Supported by CE and ISO certified safety standards with 2-year warranty. Requires minimum maintenance with automatic lubrication system.',
            paragraph6: 'CS-80 dual shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits to businesses. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes and technical consultancy services.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-80 - мощное, долговечное и профессиональное решение для объектов, требующих обработки больших объемов отходов.',
            paragraph1: 'Модель CS-80 разработана для тяжелых условий эксплуатации с высокопроизводительной системой двойного двигателя 2x22 кВт, длиной ротора 1000 мм и диаметром ротора 350 мм. С производительностью 1500-2500 кг/час демонстрирует превосходную эффективность.',
            paragraph2: 'Оснащенный полностью автоматической панелью управления ПЛК, мониторингом нагрузки в реальном времени и автоматической защитой от перегрузки, CS-80 имеет возможность непрерывной работы 7/24. С 80 ножами премиум качества и двойной системой сит можно выполнять грубое и среднее измельчение.',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-80 оптимизирован для крупных предприятий по переработке пластика, центров обработки автомобильного лома, подразделений измельчения деревянных поддонов и промышленных объектов управления отходами.',
            paragraph4: 'С технологией двухвального измельчителя CS-80 обеспечивает выдающиеся результаты в применениях дробилки пластикового лома, измельчителя тюков и измельчителя резины. Эта система предлагает долгий срок службы с прочной конструкцией вала и усиленным редуктором.',
            paragraph5: 'Двухвальный измельчитель CS-80, предлагающий энергоэффективность, обеспечивает высокую отдачу от инвестиций. Поддерживается сертификатами CE и ISO с гарантией 2 года. Требует минимального обслуживания с автоматической системой смазки.',
            paragraph6: 'Двухвальный измельчитель CS-80, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность предприятиям. MT Makina, ведущий производитель измельчителей в Турции, предлагает ценовые предложения и технические консультации.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-80 هي حل قوي ومتين ومهني للمرافق الصناعية التي تتطلب معالجة نفايات كبيرة الحجم.',
            paragraph1: 'تم تصميم طراز CS-80 للتطبيقات الثقيلة بنظام محرك مزدوج عالي الأداء 2×22 كيلووات وطول دوار 1000 مم وقطر دوار 350 مم. بسعة معالجة 1500-2500 كجم/ساعة، يظهر أداءً فائقاً.',
            paragraph2: 'مجهز بلوحة تحكم PLC أوتوماتيكية بالكامل ومراقبة الحمل في الوقت الفعلي وحماية تلقائية من الحمل الزائد، يتمتع CS-80 بقدرة تشغيل متواصل 7/24. مع 80 شفرة عالية الجودة ونظام شاشة مزدوج يمكن إجراء التمزيق الخشن والمتوسط.',
            paragraph3: 'آلة تمزيق النفايات الصلبة MT Makina CS-80 محسنة لمرافق إعادة تدوير البلاستيك الكبيرة ومراكز معالجة خردة السيارات ووحدات تمزيق المنصات الخشبية ومنشآت إدارة النفايات الصناعية.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-80 نتائج استثنائية في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط. توفر هذه الآلة عمراً طويلاً مع هيكل عمود قوي وعلبة تروس معززة.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-80 التي توفر كفاءة الطاقة تحقق عائداً مرتفعاً على الاستثمار. مدعومة بمعايير السلامة المعتمدة CE وISO مع ضمان سنتين. تتطلب الحد الأدنى من الصيانة مع نظام التشحيم التلقائي.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-80 توفر الاستدامة في إدارة النفايات وتقدم كفاءة عالية للشركات. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وخدمات استشارية تقنية.'
        }
    },
    'CS-100': {
        tr: {
            intro: 'CS-100 çift şaftlı parçalama makinesi, yüksek kapasiteli endüstriyel uygulamalar için güçlü tork, üstün performans ve Endüstri 4.0 uyumlu otomasyon sunan profesyonel bir sistemdir.',
            paragraph1: 'CS-100 çift şaftlı parçalama makinesi, 2x30 kW endüstriyel sınıf çift motor yapısı ile 1200 mm geniş rotor uzunluğu ve 400 mm rotor çapına sahiptir. 2500-4000 kg/saat yüksek işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında maksimum verimlilik sağlar. Büyük hacimli konteynerler, IBC tanklar, endüstriyel plastik kasalar, evsel eşya atıkları ve kompozit malzemelerin parçalanmasında olağanüstü performans gösterir.',
            paragraph2: 'Siemens PLC tabanlı gelişmiş otomasyon sistemi, dokunmatik ekran operatör paneli, uzaktan izleme altyapısı ile donatılmış CS-100 çift şaftlı parçalama makinesi, Endüstri 4.0 standartlarına uygundur. 96 adet özel sertleştirilmiş bıçak ve çift kademeli elek sistemi (60-180 mm) ile homojen parçalama garantisi verir. Plastik kırma makinesi ve hurda plastik kırma makinası olarak predictive maintenance (öngörülü bakım) ve IoT bağlantı altyapısı sunar.',
            paragraph3: 'MT Makina CS-100 katı atık parçalama makinası, büyük kapasiteli geri dönüşüm kompleksleri, belediye katı atık yönetim tesisleri, otomotiv geri kazanım merkezleri ve endüstriyel atık işleme fabrikaları için tasarlanmıştır. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak tam otomatik besleme sistemi, manyetik seperatör ve konveyör bantları ile entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında da üstün performans sağlar.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-100, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında olağanüstü sonuçlar verir. Büyük ölçekli endüstriyel tesisler için optimize edilmiş bu sistem, güçlü şaft yapısı, endüstriyel dişli kutusu ve ultra dayanıklı bıçak sistemi ile maksimum performans ve uzun ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından büyük yatırımlar için yüksek geri dönüş oranı sunar.',
            paragraph5: 'Enerji verimliliği sunan CS-100 çift şaftlı parçalama makinesi, işletme maliyetlerini minimize ederek yüksek yatırım getirisi sağlar. Plastik kırma makinesi fiyatları konusunda büyük projeler için ekonomik ve güvenilir çözümler sunan bu sistem, profesyonel geri dönüşüm kompleksleri için ideal bir yatırımdır. CE, ISO 9001 ve ISO 14001 sertifikalı güvenlik ve kalite standartları ile 2 yıl garanti ile desteklenir. SCADA entegrasyonu ve uzaktan izleme ile 7/24 operasyon desteği sağlar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-100 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, turnkey proje çözümleri ve 7/24 teknik destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. CS-100, büyük ölçekli endüstriyel projeler için tercih edilen profesyonel sınıf parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-100 dual shaft shredder offers powerful torque, superior performance and Industry 4.0 compatible automation for high-capacity industrial applications.',
            paragraph1: 'CS-100 model features industrial-grade double motor structure with 2x30 kW, 1200 mm wide rotor length and 400 mm rotor diameter. With 2500-4000 kg/hour high processing capacity, it provides maximum efficiency in plastic shredder, fabric shredder and pallet shredder applications.',
            paragraph2: 'Equipped with Siemens PLC-based advanced automation system, touchscreen operator panel and remote monitoring infrastructure, CS-100 complies with Industry 4.0 standards. With 96 special hardened blades and dual-stage screen system (60-180 mm), homogeneous shredding is guaranteed.',
            paragraph3: 'MT Makina CS-100 solid waste shredder is designed for large capacity recycling complexes, municipal solid waste management facilities, automotive recovery centers and industrial zone joint processing centers.',
            paragraph4: 'With dual shaft shredder technology, CS-100 provides maximum results in largest projects for plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Offers long life with strong shaft structure, reinforced gearbox and durable blade system.',
            paragraph5: 'CS-100 dual shaft shredder offering energy efficiency provides highest return on investment by minimizing operating costs. Supported by CE and ISO certified safety standards with 2-year warranty. Offers predictive maintenance and IoT connectivity infrastructure.',
            paragraph6: 'CS-100 dual shaft shredder providing sustainability in waste management offers maximum efficiency and environmental benefits to businesses. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes and turnkey project solutions.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-100 предлагает мощный крутящий момент, превосходную производительность и автоматизацию, совместимую с Индустрией 4.0, для высокопроизводительных промышленных применений.',
            paragraph1: 'Модель CS-100 оснащена двухмоторной конструкцией промышленного класса 2x30 кВт с широкой длиной ротора 1200 мм и диаметром ротора 400 мм. С высокой производительностью обработки 2500-4000 кг/час обеспечивает максимальную эффективность.',
            paragraph2: 'Оснащенный передовой системой автоматизации на базе ПЛК Siemens, сенсорной панелью оператора и инфраструктурой удаленного мониторинга, CS-100 соответствует стандартам Индустрии 4.0. С 96 специальными закаленными ножами гарантирует однородное измельчение.',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-100 разработан для крупных комплексов переработки, муниципальных объектов управления твердыми отходами и центров восстановления автомобилей.',
            paragraph4: 'С технологией двухвального измельчителя CS-100 обеспечивает максимальные результаты в крупнейших проектах для применений дробилки пластикового лома и измельчителя тюков. Предлагает долгий срок службы с прочной конструкцией вала.',
            paragraph5: 'Двухвальный измельчитель CS-100, предлагающий энергоэффективность, обеспечивает наивысшую отдачу от инвестиций. Поддерживается сертификатами CE и ISO с гарантией 2 года. Предлагает предиктивное обслуживание и IoT-подключение.',
            paragraph6: 'Двухвальный измельчитель CS-100 предлагает максимальную эффективность и экологические преимущества. MT Makina, ведущий производитель измельчителей в Турции, предлагает ценовые предложения и решения под ключ.'
        },
        ar: {
            intro: 'تقدم آلة التمزيق ثنائية العمود CS-100 عزم دوران قويًا وأداءً متفوقًا وأتمتة متوافقة مع الصناعة 4.0 للتطبيقات الصناعية عالية السعة.',
            paragraph1: 'يتميز طراز CS-100 بهيكل محرك مزدوج من الدرجة الصناعية 2×30 كيلووات مع طول دوار عريض 1200 مم وقطر دوار 400 مم. بسعة معالجة عالية 2500-4000 كجم/ساعة، يوفر أقصى كفاءة.',
            paragraph2: 'مجهز بنظام أتمتة متقدم قائم على PLC من Siemens ولوحة مشغل بشاشة تعمل باللمس وبنية تحتية للمراقبة عن بعد، يتوافق CS-100 مع معايير الصناعة 4.0. مع 96 شفرة مقواة خاصة يضمن التمزيق المتجانس.',
            paragraph3: 'تم تصميم آلة تمزيق النفايات الصلبة MT Makina CS-100 لمجمعات إعادة التدوير كبيرة السعة ومرافق إدارة النفايات الصلبة البلدية ومراكز استعادة السيارات.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-100 أقصى النتائج في أكبر المشاريع لتطبيقات كسارة خردة البلاستيك وتمزيق البالات. توفر عمراً طويلاً مع هيكل عمود قوي.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-100 التي توفر كفاءة الطاقة تحقق أعلى عائد على الاستثمار. مدعومة بمعايير السلامة المعتمدة CE وISO مع ضمان سنتين. توفر الصيانة التنبؤية واتصال IoT.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-100 توفر أقصى كفاءة وفوائد بيئية. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وحلول متكاملة.'
        }
    },
    'CS-120': {
        tr: {
            intro: 'CS-120 çift şaftlı parçalama makinesi, ağır sanayi atık yönetiminde maksimum kapasite, üstün performans ve profesyonel otomasyon sunan endüstriyel sınıf bir sistemdir.',
            paragraph1: 'CS-120 çift şaftlı parçalama makinesi, 2x37 kW yüksek tork çift motor yapısı ile 1400 mm ultra geniş rotor uzunluğu ve 450 mm rotor çapı sunarak en zorlu uygulamalar için tasarlanmıştır. 4000-6000 kg/saat işleme kapasitesi ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında maksimum verimlilik sağlar. Lastik balyaları, büyük plastik tanklar, ağır kompozit malzemeler, endüstriyel atıklar ve büyük hacimli ahşap ürünlerin parçalanmasında olağanüstü performans gösterir.',
            paragraph2: 'Endüstriyel sınıf Siemens S7 PLC otomasyon, SCADA entegrasyonu, gerçek zamanlı veri analizi ve predictive maintenance modülleri ile donatılmış CS-120 çift şaftlı parçalama makinesi, akıllı fabrika konseptine tam uyumludur. 112 adet özel alaşımlı bıçak ve üç kademeli elek sistemi (80-200 mm) ile maksimum tork ve hassas parçalama sağlar. Plastik kırma makinesi ve hurda plastik kırma makinası olarak bulut tabanlı izleme ve mobil uygulama desteği sunar.',
            paragraph3: 'MT Makina CS-120 katı atık parçalama makinası, mega ölçekli geri dönüşüm kompleksleri, belediye entegre katı atık tesisleri, lastik geri dönüşüm fabrikaları ve ağır sanayi atık işleme merkezleri için optimize edilmiştir. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak tam otomatik besleme hatları, multi-stage parçalama sistemleri ve ileri ayırma teknolojileri ile entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında endüstriyel standartta performans sağlar.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-120, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında benzersiz sonuçlar verir. Mega ölçekli tesisler için optimize edilmiş bu sistem, premium şaft yapısı, ağır hizmet dişli kutusu ve ultra dayanıklı bıçak sistemi ile 10+ yıl ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından mega projeler için yüksek ROI ve düşük toplam sahip olma maliyeti sunar.',
            paragraph5: 'Enerji verimliliği sunan CS-120 çift şaftlı parçalama makinesi, frekans invertör kontrollü motor sistemi ile işletme maliyetlerini minimize eder. Plastik kırma makinesi fiyatları konusunda mega projeler için kapsamlı finansman ve leasing seçenekleri sunan bu sistem, profesyonel geri dönüşüm kompleksleri için stratejik bir yatırımdır. CE, ISO 9001, ISO 14001 ve ATEX sertifikalı standartlar ile 3 yıl garanti ile desteklenir. 7/24 uzaktan izleme ve proaktif bakım desteği sağlar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-120 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, turnkey proje çözümleri, mühendislik danışmanlığı ve kurulum sonrası destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. CS-120, mega ölçekli endüstriyel projeler için tercih edilen ultra güçlü parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-120 dual shaft shredder is an industrial-grade professional system offering maximum capacity, superior performance and professional automation in heavy industrial waste management.',
            paragraph1: 'CS-120 model is designed for the toughest applications with 2x37 kW high-torque dual motor structure, 1400 mm ultra-wide rotor length and 450 mm rotor diameter. With 4000-6000 kg/hour processing capacity, it provides exceptional performance in tire bales, large plastic tanks, heavy composite materials and large volume wood products shredding.',
            paragraph2: 'Equipped with industrial-grade Siemens S7 PLC automation, SCADA integration, real-time data analysis and predictive maintenance modules, CS-120 is fully compatible with smart factory concept. With 112 special alloy blades and three-stage screen system (80-200 mm), maximum torque and precise shredding is ensured.',
            paragraph3: 'MT Makina CS-120 solid waste shredder is optimized for mega-scale recycling complexes, municipal integrated solid waste facilities, heavy industry scrap processing and large-scale industrial projects.',
            paragraph4: 'With dual shaft shredder technology, CS-120 provides exceptional results in largest industrial projects for plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Offers maximum performance with heavy-duty shaft structure, premium gearbox and industrial-grade blade system.',
            paragraph5: 'CS-120 dual shaft shredder with frequency inverter controlled motor system minimizes operating costs while offering energy efficiency. Supported by CE, ISO 9001, ISO 14001 and ATEX certified standards with 3-year warranty. Provides 7/24 remote monitoring and proactive maintenance support.',
            paragraph6: 'CS-120 dual shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes, turnkey project solutions, engineering consultancy and post-installation support services.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-120 - профессиональная система промышленного класса, обеспечивающая максимальную производительность и профессиональную автоматизацию в управлении тяжелыми промышленными отходами.',
            paragraph1: 'Модель CS-120 разработана для самых сложных применений с высокомоментной конструкцией двойного двигателя 2x37 кВт, ультраширокой длиной ротора 1400 мм и диаметром ротора 450 мм. С производительностью 4000-6000 кг/час обеспечивает исключительную производительность.',
            paragraph2: 'Оснащенный промышленной автоматизацией Siemens S7 PLC, интеграцией SCADA, анализом данных в реальном времени и модулями предиктивного обслуживания, CS-120 полностью совместим с концепцией умной фабрики. С 112 ножами из специального сплава обеспечивает максимальный крутящий момент.',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-120 оптимизирован для мегамасштабных комплексов переработки, муниципальных интегрированных объектов твердых отходов и крупномасштабных промышленных проектов.',
            paragraph4: 'С технологией двухвального измельчителя CS-120 обеспечивает исключительные результаты в крупнейших промышленных проектах. Предлагает максимальную производительность с тяжелой конструкцией вала и редуктором премиум-класса.',
            paragraph5: 'Двухвальный измельчитель CS-120 с частотным инверторным управлением двигателя минимизирует эксплуатационные расходы. Поддерживается сертификатами CE, ISO 9001, ISO 14001 и ATEX с гарантией 3 года.',
            paragraph6: 'Двухвальный измельчитель CS-120 предлагает высокую эффективность и экологические преимущества. MT Makina предлагает ценовые предложения, решения под ключ и инженерные консультации.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-120 هي نظام احترافي من الدرجة الصناعية يوفر أقصى سعة وأداء متفوق وأتمتة مهنية في إدارة النفايات الصناعية الثقيلة.',
            paragraph1: 'تم تصميم طراز CS-120 لأصعب التطبيقات بهيكل محرك مزدوج عالي عزم الدوران 2×37 كيلووات وطول دوار فائق العرض 1400 مم وقطر دوار 450 مم. بسعة معالجة 4000-6000 كجم/ساعة، يوفر أداءً استثنائياً.',
            paragraph2: 'مجهز بأتمتة Siemens S7 PLC من الدرجة الصناعية وتكامل SCADA وتحليل البيانات في الوقت الفعلي ووحدات الصيانة التنبؤية، يتوافق CS-120 تماماً مع مفهوم المصنع الذكي. مع 112 شفرة من السبائك الخاصة يضمن أقصى عزم دوران.',
            paragraph3: 'آلة تمزيق النفايات الصلبة MT Makina CS-120 محسنة لمجمعات إعادة التدوير الضخمة ومرافق النفايات الصلبة البلدية المتكاملة والمشاريع الصناعية واسعة النطاق.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-120 نتائج استثنائية في أكبر المشاريع الصناعية. توفر أقصى أداء مع هيكل عمود للخدمة الشاقة وعلبة تروس متميزة.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-120 مع نظام تحكم محرك بمحول تردد تقلل تكاليف التشغيل. مدعومة بمعايير CE وISO 9001 وISO 14001 وATEX مع ضمان 3 سنوات.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-120 توفر كفاءة عالية وفوائد بيئية. MT Makina تقدم عروض أسعار وحلول متكاملة واستشارات هندسية ودعم ما بعد التركيب.'
        }
    },
    'CS-150': {
        tr: {
            intro: 'CS-150 çift şaftlı parçalama makinesi, mega kapasiteli geri dönüşüm kompleksleri için tasarlanmış ultra güçlü, yapay zeka destekli ve bulut tabanlı izleme sunan profesyonel bir endüstriyel sistemdir.',
            paragraph1: 'CS-150 çift şaftlı parçalama makinesi, 2x45 kW ultra yüksek tork ile 1600 mm dev rotor uzunluğu ve 500 mm rotor çapı sunar. 6000-8000 kg/saat kapasite ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında eşsiz performans sağlar. Otobüs-kamyon lastikleri, büyük endüstriyel konteynerler, mega plastik tanklar, dev ahşap yapılar ve ağır kompozit malzemelerin parçalanmasında dünya standartlarında verimlilik gösterir.',
            paragraph2: 'En ileri Siemens S7-1500 PLC otomasyon, yapay zeka destekli yük optimizasyonu, bulut tabanlı veri toplama ve predictive analytics ile donatılmış CS-150 çift şaftlı parçalama makinesi, Endüstri 4.0+ standartlarına tam uyumludur. 128 adet ultra premium bıçak ve dört kademeli akıllı elek sistemi (100-250 mm) ile maksimum tork ve hassas parçalama garantisi verir. Plastik kırma makinesi ve hurda plastik kırma makinası olarak machine learning algoritmaları ile sürekli öğrenen optimizasyon sunar.',
            paragraph3: 'MT Makina CS-150 katı atık parçalama makinası, mega ölçekli entegre geri dönüşüm tesisleri, lastik piroliz öncesi hazırlık tesisleri, megakent atık yönetim merkezleri ve uluslararası standartlarda endüstriyel kompleksler için özel olarak tasarlanmıştır. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak tam otomatik besleme sistemleri, robotik ayırma hatları ve ileri MRF teknolojileri ile entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında dünya lideri performans sağlar.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-150, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında sektör lideri sonuçlar verir. Global standartlardaki mega tesisler için optimize edilmiş bu sistem, titan alaşımlı şaft yapısı, planetary dişli kutusu ve tungsten karbür bıçak sistemi ile 15+ yıl ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından mega projeler için en yüksek ROI ve en düşük toplam sahip olma maliyeti sunar.',
            paragraph5: 'Enerji verimliliği sunan CS-150 çift şaftlı parçalama makinesi, değişken frekanslı sürücü (VFD) ve regeneratif frenleme sistemi ile işletme maliyetlerini minimize eder. Plastik kırma makinesi fiyatları konusunda mega projeler için özel finansman paketleri ve global leasing seçenekleri sunan bu sistem, dünya standartlarında geri dönüşüm kompleksleri için stratejik bir yatırımdır. CE, ISO 9001, ISO 14001, ATEX ve IEC standartlarına uygunluk ile 3 yıl global garanti ve lifetime destek sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-150 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere maksimum verimlilik, çevresel liderlik ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, turnkey mega proje çözümleri, uluslararası mühendislik danışmanlığı ve global teknik destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi mega projeleriniz için global satış ekibimizle iletişime geçin. CS-150, mega ölçekli global projeler için tercih edilen ultra güçlü parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-150 dual shaft shredder is an ultra-powerful industrial system designed for mega-capacity recycling complexes, offering AI-assisted optimization and cloud-based monitoring.',
            paragraph1: 'CS-150 model features 2x45 kW ultra-high torque with 1600 mm giant rotor length and 500 mm rotor diameter. With 6000-8000 kg/hour processing capacity, it provides maximum performance in tire bales, large plastic tanks, heavy composite materials, industrial waste and highest volume wood products shredding.',
            paragraph2: 'Equipped with most advanced Siemens S7-1500 PLC automation, AI-assisted load optimization, cloud-based monitoring and digital twin technology, CS-150 leads the smart industrial revolution. With 128 premium quality special alloy blades and four-stage screen system (100-250 mm), ultra precise shredding is guaranteed.',
            paragraph3: 'MT Makina CS-150 solid waste shredder is specifically designed for mega-scale integrated recycling facilities, international waste processing projects, multi-site operations and smart factory applications.',
            paragraph4: 'With dual shaft shredder technology, CS-150 provides ultimate results in largest global projects for plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Offers maximum durability with heavy-duty shaft structure, industrial gearbox and premium blade system.',
            paragraph5: 'CS-150 dual shaft shredder with variable frequency drive (VFD) and regenerative braking system minimizes operating costs while offering maximum energy efficiency. Compliant with CE, ISO 9001, ISO 14001, ATEX and IEC standards with 3-year global warranty and lifetime support.',
            paragraph6: 'CS-150 dual shaft shredder providing sustainability leadership in waste management offers maximum efficiency and environmental benefits. MT Makina, the leading shredder manufacturer in Turkey, offers dual shaft solid waste shredder price quotes, turnkey mega project solutions, international engineering consultancy and global technical support services.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-150 - сверхмощная промышленная система для мегамасштабных комплексов переработки с ИИ-оптимизацией и облачным мониторингом.',
            paragraph1: 'Модель CS-150 оснащена сверхвысоким крутящим моментом 2x45 кВт с гигантской длиной ротора 1600 мм и диаметром ротора 500 мм. С производительностью 6000-8000 кг/час обеспечивает максимальную производительность.',
            paragraph2: 'Оснащенный самой передовой автоматизацией Siemens S7-1500 PLC, ИИ-оптимизацией нагрузки, облачным мониторингом и технологией цифрового двойника, CS-150 лидирует в умной промышленной революции. С 128 ножами премиум качества гарантирует ультраточное измельчение.',
            paragraph3: 'Измельчитель твердых отходов MT Makina CS-150 специально разработан для интегрированных предприятий переработки мегамасштаба, международных проектов переработки отходов и приложений умной фабрики.',
            paragraph4: 'С технологией двухвального измельчителя CS-150 обеспечивает окончательные результаты в крупнейших глобальных проектах. Предлагает максимальную долговечность с конструкцией вала для тяжелых условий и промышленным редуктором.',
            paragraph5: 'Двухвальный измельчитель CS-150 с частотно-регулируемым приводом (VFD) и системой рекуперативного торможения минимизирует эксплуатационные расходы. Соответствует стандартам CE, ISO 9001, ISO 14001, ATEX и IEC с 3-летней глобальной гарантией.',
            paragraph6: 'Двухвальный измельчитель CS-150 предлагает максимальную эффективность и экологические преимущества. MT Makina предлагает ценовые предложения, решения мегапроектов под ключ, международные инженерные консультации и глобальную техническую поддержку.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-150 هي نظام صناعي فائق القوة مصمم لمجمعات إعادة التدوير الضخمة مع تحسين الذكاء الاصطناعي والمراقبة السحابية.',
            paragraph1: 'يتميز طراز CS-150 بعزم دوران فائق 2×45 كيلووات مع طول دوار ضخم 1600 مم وقطر دوار 500 مم. بسعة معالجة 6000-8000 كجم/ساعة، يوفر أقصى أداء.',
            paragraph2: 'مجهز بأكثر أنظمة الأتمتة تقدمًا Siemens S7-1500 PLC وتحسين الحمل بالذكاء الاصطناعي والمراقبة السحابية وتقنية التوأم الرقمي، يقود CS-150 الثورة الصناعية الذكية. مع 128 شفرة متميزة يضمن التمزيق فائق الدقة.',
            paragraph3: 'تم تصميم آلة تمزيق النفايات الصلبة MT Makina CS-150 خصيصًا لمجمعات إعادة التدوير المتكاملة الضخمة والمشاريع الدولية لمعالجة النفايات وتطبيقات المصنع الذكي.',
            paragraph4: 'مع تقنية التمزيق ثنائي العمود، توفر CS-150 النتائج النهائية في أكبر المشاريع العالمية. توفر أقصى متانة مع هيكل عمود للخدمة الشاقة وعلبة تروس صناعية.',
            paragraph5: 'آلة التمزيق ثنائية العمود CS-150 مع محرك تردد متغير (VFD) ونظام الفرملة التجددية تقلل تكاليف التشغيل. متوافقة مع معايير CE وISO 9001 وISO 14001 وATEX وIEC مع ضمان عالمي 3 سنوات.',
            paragraph6: 'آلة التمزيق ثنائية العمود CS-150 توفر أقصى كفاءة وفوائد بيئية. MT Makina تقدم عروض أسعار وحلول مشاريع ضخمة متكاملة واستشارات هندسية دولية ودعم تقني عالمي.'
        }
    },
    'CS-180': {
        tr: {
            intro: 'CS-180 çift şaftlı parçalama makinesi, uluslararası standartlarda mega projelere yönelik ultra kapasiteli, AI destekli ve tam entegre otomasyon sunan premium endüstriyel sistemdir.',
            paragraph1: 'CS-180 çift şaftlı parçalama makinesi, 2x55 kW ekstrem tork ile 1800 mm ultra geniş rotor ve 550 mm rotor çapı sunar. 8000-12000 kg/saat muazzam kapasite ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında dünya lideri performans sağlar. Kamyon şaseleri, dev plastik tanklar, mega ahşap yapılar, endüstriyel kompozitler ve ağır sanayi atıklarının parçalanmasında benzersiz verimlilik gösterir.',
            paragraph2: 'Tam entegre Siemens TIA Portal otomasyon, makine öğrenimi algoritmaları, gerçek zamanlı big data analizi ve digital twin simülasyonu ile donatılmış CS-180 çift şaftlı parçalama makinesi, Endüstri 5.0 vizyonuna tam uyumludur. 144 adet ultra premium tungsten karbür bıçak ve beş kademeli akıllı elek sistemi (120-300 mm) ile maksimum tork ve ultra hassas parçalama garantisi verir. Plastik kırma makinesi ve hurda plastik kırma makinası olarak derin öğrenme AI ile sürekli optimizasyon sunar.',
            paragraph3: 'MT Makina CS-180 katı atık parçalama makinası, uluslararası entegre geri dönüşüm kompleksleri, megakent atık yönetim merkezleri, uluslararası geri dönüşüm konsorsiyumları ve global ölçekli endüstriyel projeler için özel mühendislik çözümü olarak tasarlanmıştır. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak tam otomatik robotik hatlar, AI-destekli ayırma sistemleri ve next-gen MRF teknolojileri ile entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında global standartlarda liderlik sunar.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-180, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında global benchmark sonuçlar verir. Uluslararası mega projeler için optimize edilmiş bu sistem, aerospace grade şaft yapısı, planetary dişli kutusu ve diamond-tipped bıçak sistemi ile 20+ yıl ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından global mega projeler için en yüksek ROI oranını garantiler.',
            paragraph5: 'Enerji verimliliği sunan CS-180 çift şaftlı parçalama makinesi, advanced VFD sistemi, regeneratif enerji geri kazanımı ve smart grid entegrasyonu ile işletme maliyetlerini minimize eder. Plastik kırma makinesi fiyatları konusunda uluslararası mega projeler için özel finansman, ECA kredileri ve global leasing seçenekleri sunan bu sistem, dünya standartlarında geri dönüşüm kompleksleri için premium yatırımdır. CE, ISO 9001, ISO 14001, ISO 45001, ATEX ve IECEx standartlarına uygunluk ile 4 yıl platinum garanti sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-180 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere dünya lideri verimlilik, karbon nötrlük hedefleri ve ekonomik sürdürülebilirlik sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, uluslararası turnkey proje çözümleri, global mühendislik danışmanlığı ve 7/24 worldwide teknik destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi global mega projeleriniz için uluslararası satış ekibimizle iletişime geçin. CS-180, uluslararası ölçekli mega projeler için tercih edilen premium sınıf parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-180 dual shaft shredder is an ultra-capacity industrial powerhouse for mega projects.',
            paragraph1: 'CS-180 model features 2x55 kW extreme torque with 1800 mm ultra-wide rotor. 8000-12000 kg/hour capacity.',
            paragraph2: 'Equipped with fully integrated Siemens TIA Portal automation, machine learning algorithms.',
            paragraph3: 'CS-180 is designed as special engineering solution for international integrated recycling complexes.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-180 - ультрапроизводительная промышленная электростанция.',
            paragraph1: 'Модель CS-180 оснащена экстремальным крутящим моментом 2x55 кВт. Производительность 8000-12000 кг/час.',
            paragraph2: 'Оснащенный полностью интегрированной автоматизацией Siemens TIA Portal.',
            paragraph3: 'CS-180 разработан как специальное инженерное решение для международных комплексов переработки.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-180 هي محطة طاقة صناعية فائقة السعة.',
            paragraph1: 'يتميز طراز CS-180 بعزم دوران قصوى 2×55 كيلووات. سعة 8000-12000 كجم/ساعة.',
            paragraph2: 'مجهز بأتمتة متكاملة بالكامل Siemens TIA Portal.',
            paragraph3: 'تم تصميم CS-180 كحل هندسي خاص لمجمعات إعادة التدوير المتكاملة الدولية.'
        }
    },
    'CS-200': {
        tr: {
            intro: 'CS-200 çift şaftlı parçalama makinesi, MT Makina\'nın en büyük ve en güçlü modeli olup dünya standartlarında mega kapasiteli, AI destekli ve tam otonom operasyon sunan mühendislik harikasıdır.',
            paragraph1: 'CS-200 çift şaftlı parçalama makinesi, 2x75 kW maksimum tork ile 2000 mm dev rotor ve 600 mm rotor çapı sunar. 12000-18000 kg/saat olağanüstü kapasite ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında dünya rekorları kırar. Saatte 18 tona kadar atık işleyebilen bu sistem, tren vagonları, gemi parçaları, mega ahşap yapılar, dev endüstriyel konteynerler ve ağır sanayi atıklarının parçalanmasında rakipsiz performans sergiler.',
            paragraph2: 'En ileri Siemens S7-1500 Failsafe PLC, derin öğrenme AI, digital twin simülasyonu, IoT sensör ağı ve cyber security ile donatılmış CS-200 çift şaftlı parçalama makinesi, tam otonom operasyon kapasitesine sahiptir. 160 ultra premium tungsten karbür bıçak ve altı kademeli akıllı elek sistemi (150-350 mm) ile maksimum tork ve mükemmel parçalama garantisi verir. Plastik kırma makinesi ve hurda plastik kırma makinası olarak quantum computing destekli optimizasyon algoritmaları sunar.',
            paragraph3: 'MT Makina CS-200 katı atık parçalama makinası, global entegre geri dönüşüm kompleksleri, metropol atık yönetim mega projeleri, uluslararası geri dönüşüm konsorsiyumları ve dünya ölçeğinde endüstriyel mega tesisler için turnkey çözüm olarak tasarlanmıştır. Plastik parçalama makinası ve geri dönüşüm kırma makinası olarak tam otonom robotik hatlar, AI-destekli sıfır atık sistemleri ve next-gen circular economy teknolojileri ile entegre edilebilir. Palet parçalama makinası ve kumaş parçalama makinesi uygulamalarında dünya lideri pozisyonunu korur.',
            paragraph4: 'Çift şaftlı parçalama makinesi teknolojisi ile CS-200, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında dünya benchmark standartları belirler. Global mega projeler için tasarlanmış bu amiral gemisi sistem, aerospace grade titan alaşımlı şaft yapısı, industrial planetary dişli kutusu ve diamond-coated ultra premium bıçak sistemi ile 25+ yıl ömür garantisi sunar. Katı atık parçalama makinası fiyatları açısından global mega projeler için sektördeki en yüksek yatırım getirisi oranını garantiler.',
            paragraph5: 'Enerji verimliliği sunan CS-200 çift şaftlı parçalama makinesi, next-gen VFD sistemi, regeneratif enerji geri kazanımı, smart grid entegrasyonu ve karbon nötr operasyon modülü ile işletme maliyetlerini minimize eder. Plastik kırma makinesi fiyatları konusunda global mega projeler için sovereign wealth fund finansmanı, export credit agency destekleri ve uluslararası leasing seçenekleri sunan bu amiral gemisi sistem, dünya standartlarında geri dönüşüm kompleksleri için ultimate premium yatırımdır. CE, ISO 9001, ISO 14001, ISO 45001, ISO 50001, ATEX, IECEx ve UL standartlarına uygunluk ile 5 yıl platinum garanti sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CS-200 çift şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere dünya lideri verimlilik, karbon negatif operasyon hedefleri ve circular economy liderliği sunar. Türkiye\'nin ve dünyanın lider parçalama makinesi üreticisi MT Makina, çift şaftlı katı atık parçalama makinesi fiyat teklifi, global turnkey mega proje çözümleri, uluslararası mühendislik danışmanlığı ve 7/24 worldwide premium teknik destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi global mega projeleriniz için CEO-level uluslararası satış ekibimizle iletişime geçin. CS-200, dünya ölçeğindeki mega projeler için tercih edilen ultimate parçalama çözümüdür.'
        },
        en: {
            intro: 'CS-200 dual shaft shredder is MT Makina\'s largest model, an engineering marvel for mega-capacity projects in world standards.',
            paragraph1: 'CS-200 model features 2x75 kW maximum torque with 2000 mm giant rotor. 12000-18000 kg/hour capacity processing up to 18 tons per hour.',
            paragraph2: 'Equipped with most advanced Siemens S7-1500 Failsafe PLC, deep learning AI, digital twin simulation.',
            paragraph3: 'CS-200 is designed as turnkey solution for global recycling complexes. Supported by 5-year platinum warranty+24/7 global support.'
        },
        ru: {
            intro: 'Двухвальный измельчитель CS-200 - самая большая модель MT Makina, инженерное чудо мирового стандарта.',
            paragraph1: 'Модель CS-200 оснащена максимальным крутящим моментом 2x75 кВт. Производительность 12000-18000 кг/час.',
            paragraph2: 'Оснащенный самой передовой автоматизацией Siemens S7-1500 Failsafe PLC, глубоким обучением ИИ.',
            paragraph3: 'CS-200 разработан как комплексное решение для глобальных комплексов переработки.'
        },
        ar: {
            intro: 'آلة التمزيق ثنائية العمود CS-200 هي أكبر طراز من MT Makina، معجزة هندسية بمعايير عالمية.',
            paragraph1: 'يتميز طراز CS-200 بعزم دوران أقصى 2×75 كيلووات. سعة 12000-18000 كجم/ساعة.',
            paragraph2: 'مجهز بأكثر الأنظمة تقدمًا Siemens S7-1500 Failsafe PLC، الذكاء الاصطناعي للتعلم العميق.',
            paragraph3: 'تم تصميم CS-200 كحل تسليم مفتاح لمجمعات إعادة التدوير العالمية.'
        }
    }
};
