import { MultilingualModelDescription } from '../../types/descriptionTypes';

export const mobileDescriptions: { [modelName: string]: MultilingualModelDescription } = {
    'TSM-150': {
        tr: {
            intro: 'TSM-150 tek şaftlı mobil kırıcı, şantiye ve saha uygulamaları için taşınabilir, kompakt ve hızlı kurulum sağlayan profesyonel bir mobil parçalama çözümüdür.',
            paragraph1: 'TSM-150 tek şaftlı mobil kırıcı, 300 kW (400 HP) yüksek performanslı dizel motor gücü ile 1500 mm rotor genişliği ve paletli mobil şase üzerine monte edilmiş kompakt tasarıma sahiptir. 15-25 ton/saat işleme kapasitesi ile inşaat atıkları, ahşap atıklar, evsel atıklar, organik atıklar, kağıt-karton ve ambalaj atıklarının sahada parçalanmasını sağlar. Mobil kırıcı ve mobil parçalama makinesi olarak tekerlekli veya paletli şase seçeneği ile zorlu arazilerde bile kolay taşınabilir.',
            paragraph2: 'PLC kontrollü otomasyon sistemi, uzaktan kumanda ile çalıştırma, otomatik aşırı yük koruması, çift yönlü ters çalışma (Auto-Reverse) ve acil durum durdurma fonksiyonu ile donatılmış TSM-150 mobil shredder, şantiye güvenliği standartlarını karşılar. 36 adet yüksek dayanıklı kesici bıçak ve hidrolik itici sistem ile kesintisiz besleme garantisi verir. Manyetik seperatör entegrasyonu ile metal ayrıştırma imkanı sunar. Değiştirilebilir elek sistemi (30-100 mm) ile istenilen çıkış boyutu ayarlanabilir.',
            paragraph3: 'MT Makina TSM-150 mobil kırıcı, inşaat şantiyeleri, afet bölgeleri, geçici geri dönüşüm tesisleri, belediye mobil atık işleme birimleri ve olay alanlarında hızlı atık yönetimi için optimize edilmiştir. Mobil atık kırma makinesi olarak hızlı kurulum (2-3 saat), kolay taşıma ve minimal altyapı gereksinimi ile projelere hızlı başlama imkanı sağlar. Senkronize kesim sistemi sayesinde malzeme sıkışmalarını önler ve homojen parçalama sağlar.',
            paragraph4: 'Mobil kırıcı teknolojisi ile TSM-150, ağaç kökleri parçalama, orman atıkları parçalama, moloz kırma, palet parçalama ve karışık atık işleme uygulamalarında üstün performans gösterir. Tek şaftlı mobil parçalama makinesi olarak düşük hız-yüksek tork prensibi ile çalışarak enerji verimliliği sağlar. GPS takip sistemi ve telematik modüller ile filo yönetimi ve performans izleme mümkündür. Toz bastırma sistemi ile çevre dostu çalışma garantisi verir.',
            paragraph5: 'Enerji verimliliği sunan TSM-150 mobil kırıcı, optimize edilmiş yakıt tüketimi ile işletme maliyetlerini minimize eder ve yüksek yatırım getirisi sağlar. Aşınmaya dayanıklı premium bileşenler ve otomatik yağlama sistemi sayesinde minimum bakım gerektirir. Dayanıklı paletli şase ve kaliteli bileşenleri ile 10+ yıl uzun ömürlü kullanım sunar. Mobil kırıcı fiyatları ve mobil parçalama makinesi fiyatları açısından orta ölçekli projeler için ekonomik bir yatırım sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSM-150 tek şaftlı mobil kırıcı, sahada geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, lojistik tasarrufu ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, mobil kırıcı fiyat teklifi, sahada parçalama tesisi kiralama ve 7/24 teknik destek hizmetleri sunmaktadır. Mobil shredder, mobil atık kırma makinesi ve inşaat şantiyesi parçalama projeleriniz için profesyonel danışmanlık ekibimizle iletişime geçin. CE sertifikası ve 2 yıl garanti ile desteklenir.'
        },
        en: {
            intro: 'TSM-150 single shaft mobile crusher is a professional, portable and compact solution for construction sites and field applications.',
            paragraph1: 'TSM-150 model features 300 kW (400 HP) high-performance diesel engine power with 1500 mm rotor width and reinforced tracked mobile chassis. With 15-25 ton/hour processing capacity, it shows superior performance in construction waste, wood, pallets, tree roots and mixed waste shredding.',
            paragraph2: 'Equipped with PLC automation system, remote control, automatic overload protection and bi-directional reverse function, TSM-150 meets construction site safety standards. With 32 ultra-durable cutting blades and replaceable screen system, different output sizes can be achieved.',
            paragraph3: 'MT Makina TSM-150 mobile crusher is optimized for construction sites, disaster areas, temporary recycling facilities and field operations. Tracked system provides safe movement even on rough terrain.',
            paragraph4: 'With mobile crusher technology, TSM-150 provides effective solutions in on-site waste processing. Compact design allows easy transport and quick setup. Dust suppression system ensures environmentally friendly operation.',
            paragraph5: 'TSM-150 mobile crusher offering fuel efficiency minimizes operating costs with optimized diesel consumption. Low maintenance requirements and durable components provide high return on investment.',
            paragraph6: 'TSM-150 mobile crusher providing sustainability in field waste management offers high efficiency to businesses. MT Makina offers mobile crusher price quotes and 7/24 technical support. Supported by CE certified safety standards.'
        },
        ru: {
            intro: 'Мобильная дробилка TSM-150 с одним валом - профессиональное портативное компактное решение для строительных площадок и полевых применений.',
            paragraph1: 'Модель TSM-150 оснащена высокопроизводительным двигателем 300 кВт (400 л.с.) с шириной ротора 1500 мм и усиленным гусеничным мобильным шасси. С производительностью 15-25 тонн/час демонстрирует превосходную эффективность.',
            paragraph2: 'Оснащен системой автоматизации ПЛК, дистанционным управлением, автоматической защитой от перегрузки и функцией двунаправленного реверса, TSM-150 соответствует стандартам безопасности строительных площадок.',
            paragraph3: 'MT Makina TSM-150 мобильная дробилка оптимизирована для строительных площадок, зон бедствий, временных перерабатывающих объектов и полевых операций.',
            paragraph4: 'С технологией мобильной дробилки TSM-150 обеспечивает эффективные решения в обработке отходов на месте. Компактный дизайн позволяет легкую транспортировку и быструю установку.',
            paragraph5: 'Мобильная дробилка TSM-150, предлагающая топливную эффективность, минимизирует эксплуатационные расходы. Низкие требования к обслуживанию и долговечные компоненты.',
            paragraph6: 'Мобильная дробилка TSM-150 предлагает высокую эффективность предприятиям. MT Makina предлагает ценовые предложения и техническую поддержку 7/24. Поддерживается сертификатом CE.'
        },
        ar: {
            intro: 'كسارة TSM-150 المتنقلة أحادية العمود حل احترافي محمول ومدمج لمواقع البناء والتطبيقات الميدانية.',
            paragraph1: 'يتميز طراز TSM-150 بمحرك عالي الأداء 300 كيلووات (400 حصان) مع عرض دوار 1500 مم وهيكل متنقل مجنزر معزز. بسعة معالجة 15-25 طن/ساعة، يظهر أداءً فائقاً.',
            paragraph2: 'مجهز بنظام أتمتة PLC وتحكم عن بعد وحماية تلقائية من الحمل الزائد ووظيفة العكس ثنائية الاتجاه، يلبي TSM-150 معايير سلامة مواقع البناء.',
            paragraph3: 'MT Makina TSM-150 كسارة متنقلة محسنة لمواقع البناء ومناطق الكوارث ومرافق إعادة التدوير المؤقتة والعمليات الميدانية.',
            paragraph4: 'مع تقنية الكسارة المتنقلة، توفر TSM-150 حلولاً فعالة في معالجة النفايات في الموقع. التصميم المدمج يسمح بالنقل السهل والإعداد السريع.',
            paragraph5: 'كسارة TSM-150 المتنقلة التي توفر كفاءة الوقود تقلل تكاليف التشغيل. متطلبات صيانة منخفضة ومكونات متينة.',
            paragraph6: 'كسارة TSM-150 المتنقلة توفر كفاءة عالية للشركات. MT Makina تقدم عروض أسعار ودعم تقني 7/24. مدعومة بمعايير CE.'
        }
    },
    'TSM-300': {
        tr: {
            intro: 'TSM-300 tek şaftlı mobil kırıcı, büyük kapasiteli saha projeleri için yüksek performans, üstün mobilite ve endüstriyel dayanıklılık sunan profesyonel bir mobil parçalama sistemidir.',
            paragraph1: 'TSM-300 tek şaftlı mobil kırıcı, 450 kW (600 HP) ultra güçlü dizel motor yapısı ile 3000 mm geniş rotor uzunluğu ve takviyeli paletli mobil şase üzerine monte edilmiş gelişmiş tasarıma sahiptir. 30-50 ton/saat yüksek işleme kapasitesi ile endüstriyel inşaat atıkları, büyük ahşap parçalar, ağaç kökleri, karışık belediye atıkları, endüstriyel ambalaj atıkları, organik atıklar ve hacimli atıkların sahada parçalanmasında üstün performans gösterir. Mobil kırıcı ve mobil parçalama makinesi olarak güçlendirilmiş paletli sistem ile en engebeli arazilerde bile güvenli hareket sağlar.',
            paragraph2: 'Siemens PLC tabanlı gelişmiş otomasyon, uzaktan izleme ve kontrol, gerçek zamanlı performans analizi, otomatik aşırı yük algılama, çift yönlü ters çalışma ve sıkışma önleme sistemi ile donatılmış TSM-300 mobil shredder, 7/24 saha operasyonları için tasarlanmıştır. 48 adet ultra dayanıklı kesici bıçak, çift hidrolik itici sistem ve büyük kapasiteli bunker ile kesintisiz üretim garantisi verir. Otomatik yağlama sistemi ile minimum bakım gerektirir. Değiştirilebilir elek sistemi (50-150 mm) ile istenilen çıkış boyutu ayarlanabilir.',
            paragraph3: 'MT Makina TSM-300 mobil kırıcı, büyük inşaat projeleri, baraj şantiyeleri, maden sahaları, büyük ölçekli belediye atık yönetimi, afet sonrası enkaz temizliği ve geçici büyük kapasiteli geri dönüşüm merkezleri için optimize edilmiştir. Mobil atık kırma makinesi olarak modüler yapısı sayesinde konveyör besleyici, seperatör sistemleri ve elek üniteleri ile kolayca entegre edilebilir. GPS takip sistemi ve telematik modüller ile filo yönetimi ve performans izleme mümkündür.',
            paragraph4: 'Mobil kırıcı teknolojisi ile TSM-300, orman atıkları parçalama, ağaç kökleri kırma, bina yıkım atıkları, beton kırma, asfalt parçalama ve karışık inşaat atıkları işleme uygulamalarında benzersiz performans gösterir. Tek şaftlı mobil parçalama makinesi olarak düşük hız-yüksek tork prensibi ile çalışarak enerji verimliliği ve homojen parçalama sağlar. Manyetik seperatör ve konveyör bandı entegrasyonu ile tam otomatik ayırma hattı kurulabilir. Toz bastırma sistemi ile çevre dostu çalışma garantisi verir.',
            paragraph5: 'Enerji verimliliği sunan TSM-300 mobil kırıcı, optimize edilmiş yakıt tüketimi ve regeneratif sistemler ile işletme maliyetlerini minimize eder. Aşınmaya dayanıklı premium bileşenler, sağlamlaştırılmış şase ve otomatik yağlama sistemi sayesinde minimum bakım gerektirir. Dayanıklı paletli şase ve kaliteli bileşenleri ile 15+ yıl uzun ömürlü kullanım sunar. Mobil kırıcı fiyatları ve mobil parçalama makinesi fiyatları açısından büyük projeler için yüksek yatırım getirisi sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSM-300 tek şaftlı mobil kırıcı, sahada geri dönüşüm süreçlerini optimize ederek işletmelere maksimum verimlilik, lojistik tasarrufu ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, mobil kırıcı fiyat teklifi, turnkey saha projeleri ve 7/24 teknik destek hizmetleri sunmaktadır. Mobil shredder, mobil atık kırma makinesi, maden sahası ve büyük inşaat projesi parçalama ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. ISO 9001, CE sertifikaları ve 2 yıl garanti ile desteklenir.'
        },
        en: {
            intro: 'TSM-300 single shaft mobile crusher is an industrial system offering high performance and superior mobility for large capacity field projects.',
            paragraph1: 'TSM-300 model features 450 kW (600 HP) ultra-powerful diesel engine structure with 3000 mm wide rotor length and reinforced tracked mobile chassis. With 30-50 ton/hour high processing capacity, it shows superior performance in shredding industrial construction waste, large wood pieces, tree roots and mixed municipal waste.',
            paragraph2: 'Equipped with Siemens PLC-based advanced automation, remote monitoring and control, real-time performance analysis and automatic overload detection, TSM-300 is designed for 7/24 field operations. With 48 ultra-durable cutting blades and dual hydraulic pusher system.',
            paragraph3: 'MT Makina TSM-300 mobile crusher is optimized for large construction projects, dam sites, mining fields, large-scale municipal waste management and post-disaster debris cleanup. Can be integrated with GPS tracking and telematics modules.',
            paragraph4: 'With mobile crusher technology, TSM-300 provides unique performance in forest waste shredding, tree root crushing, building demolition waste and mixed construction waste processing. Dust suppression system ensures environmentally friendly operation.',
            paragraph5: 'TSM-300 mobile crusher offering energy efficiency minimizes operating costs with optimized fuel consumption. Durable tracked chassis and premium components offer 15+ years long service life.',
            paragraph6: 'TSM-300 mobile crusher providing sustainability in waste management offers maximum efficiency and logistics savings. MT Makina offers mobile crusher price quotes, turnkey field projects and 7/24 technical support. Supported by ISO 9001, CE certifications with 2-year warranty.'
        },
        ru: {
            intro: 'Мобильная дробилка TSM-300 с одним валом - промышленная система с высокой производительностью и превосходной мобильностью для крупных полевых проектов.',
            paragraph1: 'Модель TSM-300 оснащена сверхмощным двигателем 450 кВт (600 л.с.) с широкой длиной ротора 3000 мм и усиленным гусеничным мобильным шасси. С производительностью 30-50 тонн/час демонстрирует превосходную эффективность.',
            paragraph2: 'Оснащен передовой автоматизацией Siemens PLC, удаленным мониторингом и управлением, анализом производительности в реальном времени, TSM-300 разработан для круглосуточных полевых операций.',
            paragraph3: 'MT Makina TSM-300 мобильная дробилка оптимизирована для крупных строительных проектов, плотин, горнодобывающих площадок и крупномасштабного управления отходами.',
            paragraph4: 'С технологией мобильной дробилки TSM-300 обеспечивает уникальную производительность в измельчении лесных отходов, корней деревьев и строительных отходов.',
            paragraph5: 'Мобильная дробилка TSM-300, предлагающая энергоэффективность, минимизирует эксплуатационные расходы с оптимизированным расходом топлива. Срок службы 15+ лет.',
            paragraph6: 'Мобильная дробилка TSM-300 предлагает максимальную эффективность и экономию логистики. MT Makina предлагает решения под ключ и техническую поддержку 7/24. Поддерживается сертификатами ISO 9001, CE с гарантией 2 года.'
        },
        ar: {
            intro: 'كسارة TSM-300 المتنقلة أحادية العمود نظام صناعي يوفر أداءً عالياً وحركية فائقة للمشاريع الميدانية كبيرة السعة.',
            paragraph1: 'يتميز طراز TSM-300 بهيكل محرك فائق القوة 450 كيلووات (600 حصان) مع طول دوار واسع 3000 مم وهيكل متنقل مجنزر معزز. بسعة معالجة 30-50 طن/ساعة، يظهر أداءً فائقاً.',
            paragraph2: 'مجهز بأتمتة Siemens PLC المتقدمة والمراقبة والتحكم عن بعد وتحليل الأداء في الوقت الفعلي، تم تصميم TSM-300 للعمليات الميدانية على مدار الساعة طوال أيام الأسبوع.',
            paragraph3: 'MT Makina TSM-300 كسارة متنقلة محسنة لمشاريع البناء الكبيرة ومواقع السدود وحقول التعدين وإدارة النفايات البلدية واسعة النطاق.',
            paragraph4: 'مع تقنية الكسارة المتنقلة، توفر TSM-300 أداءً فريداً في تمزيق نفايات الغابات وجذور الأشجار ونفايات البناء المختلطة.',
            paragraph5: 'كسارة TSM-300 المتنقلة الموفرة للطاقة تقلل تكاليف التشغيل مع استهلاك وقود محسن. عمر خدمة 15+ سنة.',
            paragraph6: 'كسارة TSM-300 المتنقلة توفر أقصى كفاءة ووفورات لوجستية. MT Makina تقدم حلول مشاريع متكاملة ودعم تقني 7/24. مدعومة بشهادات ISO 9001 وCE مع ضمان سنتين.'
        }
    },
    'CSM-150': {
        tr: {
            intro: 'CSM-150 çift şaftlı mobil kırıcı, orta kapasite saha uygulamaları için ön parçalama, hassas boyutlandırma ve homojen çıkış sunan çok yönlü bir mobil parçalama sistemidir.',
            paragraph1: 'CSM-150 çift şaftlı mobil kırıcı, 2x132 kW (toplam 264 kW / 350 HP) çift dizel motor yapısı ile 1500 mm rotor uzunluğu ve paletli mobil şase üzerine entegre edilmiş çift şaft teknolojisine sahiptir. 20-35 ton/saat işleme kapasitesi ile endüstriyel plastik atıklar, ahşap paletler, karışık ambalaj atıkları, inşaat atıkları, elektronik atıklar ve kontrollü boyutlandırma gerektiren malzemelerin sahada parçalanmasını sağlar. Mobil kırıcı ve mobil parçalama makinesi olarak çift şaft sistemi ile homojen ve kontrollü parçalama garantisi verir.',
            paragraph2: 'PLC kontrollü senkronize çift şaft çalışma sistemi, uzaktan kumanda, otomatik sıkışma önleme (Anti-Jamming), çift yönlü ters dönüş (Auto-Reverse) fonksiyonu ve acil durum durdurma ile donatılmış CSM-150 mobil shredder, güvenli ve verimli saha operasyonları sağlar. 2x24 adet (toplam 48) özel alaşımlı kesici bıçak, hidrolik sıkıştırma sistemi ve değiştirilebilir elek üniteleri (20-80 mm) ile istenen çıkış boyutu ayarlanabilir. Toz kontrol sistemi ile çevre dostu çalışma sağlar.',
            paragraph3: 'MT Makina CSM-150 çift şaftlı mobil kırıcı, orta ölçekli inşaat şantiyeleri, plastik geri dönüşüm sahaları, ahşap işleme tesisleri, elektronik atık toplama merkezleri ve geçici parçalama ihtiyaçları için optimize edilmiştir. Mobil atık kırma makinesi olarak hızlı kurulum (3-4 saat), kolay konumlama ve minimal operatör gerektiren kullanımı ile projeler arası hızlı geçiş sağlar. GPS takip sistemi ve telematik modüller ile filo yönetimi ve performans izleme mümkündür.',
            paragraph4: 'Çift şaftlı mobil kırıcı teknolojisi ile CSM-150, palet parçalama, plastik konteyner kırma, elektronik atık parçalama, ambalaj atıkları işleme ve karışık endüstriyel atık parçalama uygulamalarında homojen çıkış boyutu garantisi verir. Senkronize çalışan çift şaft yapısı, malzeme kaçışını önler ve her boyuttaki parçanın eşit şekilde işlenmesini sağlar. Manyetik seperatör entegrasyonu ile metal ayrıştırma imkanı sunar. Konveyör bandı ve seperatör sistemleri ile tam otomatik hat kurulabilir.',
            paragraph5: 'Enerji verimliliği sunan CSM-150 çift şaftlı mobil kırıcı, optimize edilmiş yakıt tüketimi ve senkronize motor çalışması ile işletme maliyetlerini minimize eder. Aşınmaya dayanıklı premium bileşenler, çift şaftlı dayanıklı yapı ve otomatik yağlama sistemi sayesinde minimum bakım gerektirir. Güçlendirilmiş paletli şase ve kaliteli bileşenleri ile 12+ yıl uzun ömürlü kullanım sunar. Mobil kırıcı fiyatları ve mobil parçalama makinesi fiyatları açısından orta-büyük projeler için ideal yatırım sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CSM-150 çift şaftlı mobil kırıcı, sahada geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, hassas boyutlandırma ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı mobil kırıcı fiyat teklifi, turnkey saha projeleri ve 7/24 teknik destek hizmetleri sunmaktadır. Mobil shredder, çift şaftlı mobil atık kırma makinesi ve elektronik atık parçalama projeleriniz için profesyonel danışmanlık ekibimizle iletişime geçin. CE ve ISO sertifikaları ile 2 yıl garanti ile desteklenir.'
        },
        en: {
            intro: 'CSM-150 dual shaft mobile crusher is a versatile mobile shredding system offering pre-shredding, precise sizing and homogeneous output for medium capacity field applications.',
            paragraph1: 'CSM-150 model features 2x132 kW (total 264 kW / 350 HP) dual diesel motor structure with 1500 mm rotor length and tracked mobile chassis. With 20-35 ton/hour processing capacity, it shows superior performance in industrial plastic waste, wood pallets, mixed packaging waste and electronic waste shredding.',
            paragraph2: 'Equipped with PLC-controlled synchronized dual shaft operating system, remote control, automatic anti-jamming system and auto-reverse function, CSM-150 ensures safe and efficient field operations. With 2x24 (total 48) special alloy cutting blades.',
            paragraph3: 'MT Makina CSM-150 mobile crusher is optimized for medium construction sites, plastic recycling fields, wood processing facilities and field recycling centers. Dual shaft system guarantees homogeneous and controlled shredding.',
            paragraph4: 'With dual shaft mobile crusher technology, CSM-150 provides controlled output size guarantee. Synchronized working shafts completely prevent material escape and ensure equal processing of all sizes.',
            paragraph5: 'CSM-150 mobile crusher offering energy efficiency minimizes operating costs with frequency inverter controlled motor system. Premium components require minimum maintenance.',
            paragraph6: 'CSM-150 mobile crusher offers environmental leadership with dust control system. MT Makina offers mobile crusher price quotes, turnkey projects and 7/24 technical support. Supported by CE, ISO 9001 certifications with 2-year warranty.'
        },
        ru: {
            intro: 'Двухвальная мобильная дробилка CSM-150 - универсальная система измельчения для полевых применений средней мощности.',
            paragraph1: 'Модель CSM-150 оснащена двойной моторной структурой 2x132 кВт (всего 264 кВт / 350 л.с.) с длиной ротора 1500 мм и гусеничным мобильным шасси. С производительностью 20-35 тонн/час демонстрирует превосходную эффективность.',
            paragraph2: 'Оснащен системой синхронизированной работы двух валов с ПЛК-управлением, дистанционным управлением, автоматическим предотвращением заклинивания и функцией автореверса.',
            paragraph3: 'MT Makina CSM-150 мобильная дробилка оптимизирована для средних строительных площадок, полей переработки пластика и деревообрабатывающих объектов.',
            paragraph4: 'С технологией двухвальной мобильной дробилки CSM-150 обеспечивает гарантию контролируемого размера выхода. Синхронизированные валы предотвращают утечку материала.',
            paragraph5: 'Мобильная дробилка CSM-150, предлагающая энергоэффективность, минимизирует эксплуатационные расходы. Компоненты премиум-класса требуют минимального обслуживания.',
            paragraph6: 'Мобильная дробилка CSM-150 обеспечивает экологическое лидерство. MT Makina предлагает решения под ключ и техническую поддержку 7/24. Поддерживается сертификатами CE, ISO 9001 с гарантией 2 года.'
        },
        ar: {
            intro: 'كسارة CSM-150 المتنقلة ثنائية العمود نظام متعدد الاستخدامات للتطبيقات الميدانية متوسطة السعة.',
            paragraph1: 'يتميز طراز CSM-150 بهيكل محرك مزدوج 2x132 كيلووات (إجمالي 264 كيلووات / 350 حصان) مع طول دوار 1500 مم وهيكل متنقل مجنزر. بسعة معالجة 20-35 طن/ساعة، يظهر أداءً فائقاً.',
            paragraph2: 'مجهز بنظام تشغيل عمود مزدوج متزامن بتحكم PLC وتحكم عن بعد ومنع الانسداد التلقائي ووظيفة العكس التلقائي.',
            paragraph3: 'MT Makina CSM-150 كسارة متنقلة محسنة لمواقع البناء متوسطة الحجم وحقول إعادة تدوير البلاستيك ومرافق معالجة الخشب.',
            paragraph4: 'مع تقنية الكسارة المتنقلة ثنائية العمود، توفر CSM-150 ضمان حجم الإخراج المتحكم فيه. الأعمدة المتزامنة تمنع تسرب المواد.',
            paragraph5: 'كسارة CSM-150 المتنقلة الموفرة للطاقة تقلل تكاليف التشغيل. المكونات المتميزة تتطلب صيانة دنيا.',
            paragraph6: 'كسارة CSM-150 المتنقلة توفر قيادة بيئية. MT Makina تقدم حلول متكاملة ودعم تقني 7/24. مدعومة بشهادات CE وISO 9001 مع ضمان سنتين.'
        }
    },
    'CSM-200': {
        tr: {
            intro: 'CSM-200 çift şaftlı mobil kırıcı, büyük kapasiteli saha operasyonları için maksimum güç, hassas kontrol, homojen çıkış ve Endüstri 4.0 uyumluluğu sunan profesyonel bir mobil parçalama çözümüdür.',
            paragraph1: 'CSM-200 çift şaftlı mobil kırıcı, 2x200 kW (toplam 400 kW / 530 HP) yüksek güç çift dizel motor sistemi ile 2000 mm ultra geniş rotor uzunluğu ve güçlendirilmiş paletli mobil şase üzerine entegre edilmiş ağır hizmet tipi çift şaft teknolojisine sahiptir. 40-60 ton/saat ultra yüksek işleme kapasitesi ile endüstriyel plastik bloklar, büyük ahşap yapılar, metal-plastik karışım atıklar, büyük inşaat atıkları, endüstriyel ambalaj atıkları ve yüksek hacimli geri dönüşüm projelerinde olağanüstü performans gösterir. Mobil kırıcı ve mobil parçalama makinesi olarak çift hidrolik itici sistem ile sürekli ve kesintisiz besleme garantisi verir.',
            paragraph2: 'Siemens PLC tabanlı ileri düzey otomasyon, SCADA entegrasyonu, uzaktan gerçek zamanlı izleme, yapay zeka destekli sıkışma önleme (AI Anti-Jamming), otomatik bıçak koruma sistemi ve predictive maintenance modülleri ile donatılmış CSM-200 mobil shredder, Endüstri 4.0 standartlarında saha operasyonları için tasarlanmıştır. 2x36 adet (toplam 72) ultra premium kesici bıçak, otomatik bıçak boşluk ayarı, çoklu elek sistemi (10-100 mm değiştirilebilir) ve otomatik yağlama ile maksimum verimlilik sağlar. Gelişmiş toz bastırma ve ses izolasyon sistemleri ile çevre dostu çalışma garantisi verir.',
            paragraph3: 'MT Makina CSM-200 çift şaftlı mobil kırıcı, büyük endüstriyel inşaat projeleri, mega geri dönüşüm sahaları, plastik işleme tesisleri, ahşap atık işleme merkezleri, maden sahaları, afet sonrası büyük ölçekli enkaz yönetimi ve entegre mobil geri dönüşüm hatları için turnkey çözüm olarak tasarlanmıştır. Mobil atık kırma makinesi olarak tam otomatik konveyör entegrasyonu, manyetik seperatör, eddy current ve optik seperatör eklentileri mümkündür. GPS takip sistemi ve telematik modüller ile filo yönetimi ve performans izleme mümkündür.',
            paragraph4: 'Çift şaftlı mobil kırıcı teknolojisi ile CSM-200, ağır hizmet palet parçalama, büyük plastik konteyner kırma, beyaz eşya parçalama, lastik parçalama, endüstriyel atık işleme ve karışık mega atık parçalama uygulamalarında dünya standartlarında homojen çıkış boyutu garantisi verir. Senkronize çalışan çift şaft yapısı, malzeme kaçışını tamamen önler ve her boyuttaki parçanın eşit şekilde işlenmesini sağlar. Manyetik ve eddy current seperatör entegrasyonu ile demir ve demir dışı metal ayrıştırma imkanı sunar. Robotik yükleme ve konveyör sistemleri ile tam otomatik üretim hattı kurulabilir.',
            paragraph5: 'Enerji verimliliği sunan CSM-200 çift şaftlı mobil kırıcı, frekans invertör kontrollü motor sistemi ve regeneratif enerji geri kazanımı ile işletme maliyetlerini minimize eder. Aşınmaya dayanıklı ultra premium bileşenler, ağır hizmet tipi çift şaftlı yapı ve otomatik yağlama sistemi sayesinde minimum bakım gerektirir. Güçlendirilmiş paletli şase ve kaliteli bileşenleri ile 15+ yıl uzun ömürlü kullanım sunar. Mobil kırıcı fiyatları ve mobil parçalama makinesi fiyatları açısından mega projeler için dünya standartlarında yatırım sunar.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan CSM-200 çift şaftlı mobil kırıcı, sahada geri dönüşüm süreçlerini optimize ederek işletmelere maksimum verimlilik, hassas boyutlandırma, karbon nötrlük hedefleri ve çevresel liderlik sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, çift şaftlı mobil kırıcı fiyat teklifi, global turnkey mega proje çözümleri ve 7/24 worldwide teknik destek hizmetleri sunmaktadır. Mobil shredder, çift şaftlı mobil atık kırma makinesi, mega saha projeleri ve entegre mobil geri dönüşüm hattı ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. Tüm uluslararası güvenlik standartları (CE, ISO 9001, ISO 14001) ve 3 yıl garanti+7/24 teknik destek ile desteklenir.'
        },
        en: {
            intro: 'CSM-200 dual shaft mobile crusher is a professional mobile solution offering maximum power, precise control and Industry 4.0 compatibility for large capacity field operations.',
            paragraph1: 'CSM-200 model features 2x200 kW (total 400 kW / 530 HP) high-power dual diesel motor system with 2000 mm ultra-wide rotor length and reinforced tracked mobile chassis. With 40-60 ton/hour ultra-high processing capacity, it shows extraordinary performance in large construction waste and high-volume recycling projects.',
            paragraph2: 'Equipped with Siemens PLC-based advanced automation, SCADA integration, real-time remote monitoring and AI-assisted jam prevention, CSM-200 is designed for Industry 4.0 standard field operations. With 2x36 (total 72) ultra-premium cutting blades.',
            paragraph3: 'MT Makina CSM-200 dual shaft mobile crusher is designed as turnkey solution for large industrial construction projects, mega recycling fields, plastic processing facilities and wood waste processing centers.',
            paragraph4: 'With dual shaft mobile crusher technology, CSM-200 provides world-standard homogeneous output size guarantee. Synchronized dual shaft structure completely prevents material escape and ensures equal processing.',
            paragraph5: 'CSM-200 mobile crusher offering energy efficiency minimizes operating costs with frequency inverter controlled motor system and regenerative energy recovery. Reinforced tracked chassis offers 15+ years service life.',
            paragraph6: 'CSM-200 mobile crusher offers maximum efficiency, precise sizing and environmental leadership. MT Makina offers dual shaft mobile crusher price quotes, global turnkey mega project solutions and 7/24 worldwide technical support. Supported by all international safety standards (CE, ISO 9001, ISO 14001) with 3-year warranty.'
        },
        ru: {
            intro: 'Мобильная дробилка CSM-200 с двумя валами - профессиональное решение, предлагающее максимальную мощность, точный контроль и совместимость с Индустрией 4.0 для крупных полевых операций.',
            paragraph1: 'Модель CSM-200 оснащена мощной двойной моторной системой 2x200 кВт (всего 400 кВт / 530 л.с.) с ультра-широкой длиной ротора 2000 мм и усиленным гусеничным шасси. С производительностью 40-60 тонн/час демонстрирует выдающуюся эффективность.',
            paragraph2: 'Оснащен передовой автоматизацией Siemens PLC, интеграцией SCADA, удаленным мониторингом в реальном времени и предотвращением заклинивания с помощью ИИ, CSM-200 разработан для стандартов Индустрии 4.0.',
            paragraph3: 'MT Makina CSM-200 двухвальная мобильная дробилка разработана как комплексное решение для крупных промышленных проектов, мега полей переработки и центров обработки древесных отходов.',
            paragraph4: 'С технологией двухвальной мобильной дробилки CSM-200 обеспечивает гарантию однородного размера выхода мирового стандарта. Синхронизированная структура полностью предотвращает утечку материала.',
            paragraph5: 'Мобильная дробилка CSM-200, предлагающая энергоэффективность, минимизирует эксплуатационные расходы с инверторным управлением и рекуперацией энергии. Срок службы 15+ лет.',
            paragraph6: 'Мобильная дробилка CSM-200 предлагает максимальную эффективность и экологическое лидерство. MT Makina предлагает глобальные решения под ключ и техническую поддержку 7/24. Поддерживается сертификатами CE, ISO с гарантией 3 года.'
        },
        ar: {
            intro: 'كسارة CSM-200 المتنقلة ثنائية العمود حل محمول احترافي يوفر أقصى قوة وتحكم دقيق وتوافق الصناعة 4.0 للعمليات الميدانية الكبيرة.',
            paragraph1: 'يتميز طراز CSM-200 بنظام محرك مزدوج عالي القوة 2×200 كيلووات (إجمالي 400 كيلووات / 530 حصان) مع طول دوار فائق الاتساع 2000 مم وهيكل مجنزر معزز. بسعة معالجة 40-60 طن/ساعة، يظهر أداءً استثنائياً.',
            paragraph2: 'مجهز بأتمتة Siemens PLC المتقدمة وتكامل SCADA ومراقبة عن بعد في الوقت الفعلي ومنع الانسداد بمساعدة الذكاء الاصطناعي، تم تصميم CSM-200 لمعايير الصناعة 4.0.',
            paragraph3: 'MT Makina CSM-200 كسارة متنقلة ثنائية العمود مصممة كحل متكامل لمشاريع البناء الصناعية الكبيرة وحقول إعادة التدوير الضخمة ومراكز معالجة نفايات الخشب.',
            paragraph4: 'مع تقنية الكسارة المتنقلة ثنائية العمود، توفر CSM-200 ضمان حجم الإخراج المتجانس بمعايير عالمية. الهيكل المتزامن يمنع تسرب المواد تماماً.',
            paragraph5: 'كسارة CSM-200 المتنقلة الموفرة للطاقة تقلل تكاليف التشغيل مع التحكم بالتردد واسترداد الطاقة. عمر خدمة 15+ سنة.',
            paragraph6: 'كسارة CSM-200 المتنقلة توفر أقصى كفاءة وقيادة بيئية. MT Makina تقدم حلول عالمية متكاملة ودعم تقني 7/24. مدعومة بشهادات CE وISO مع ضمان 3 سنوات.'
        }
    }
};
