import { MultilingualModelDescription } from '../../types/descriptionTypes';

export const singleShaftDescriptions: { [modelName: string]: MultilingualModelDescription } = {
    'TSH-60': {
        tr: {
            intro: 'TSH-60 tek şaftlı katı atık parçalama makinesi, küçük ve orta ölçekli geri dönüşüm tesisleri ile plastik işleme fabrikaları için özel olarak tasarlanmış kompakt ve güçlü bir endüstriyel parçalama çözümüdür.',
            paragraph1: 'TSH-60 tek şaftlı parçalama makinesi, 15-30 kW motor gücü ve 600x1100 mm parçalama alanı ile plastik parçalama makinesi, kumaş parçalama makinesi, kağıt parçalama makinesi ve palet parçalama makinesi uygulamalarında yüksek verimlilik sağlar. 500-800 kg/saat işleme kapasitesi ile plastik kırma makinesi ve hurda plastik kırma makinası işlevlerini tek bir makinede birleştirir. Bu tek şaftlı parçalama makinesi, PET şişeler, PP-PE malzemeler, HDPE kapaklar, film plastikler, tekstil atıkları, kağıt-karton, ambalaj malzemeleri ve hafif ahşap atıkların parçalanmasında üstün performans gösterir. Yüksek tork ve düşük hız kombinasyonu sayesinde plastik parçalama makinası, geri dönüşüm kırma makinası ve katı atık parçalama makinası olarak güvenle kullanılabilir.',
            paragraph2: 'Gelişmiş PLC kontrollü otomasyon sistemi ile donatılmış TSH-60 tek şaftlı parçalama makinesi, otomatik ters çalışma fonksiyonu, aşırı yük koruması ve gerçek zamanlı motor yük izleme özellikleri ile kesintisiz üretim garantisi verir. Plastik kırma makinesi fiyatları açısından ekonomik bir yatırım olan bu sistem, hidrolik baskı mekanizması sayesinde büyük ve zorlu atıkların bile verimli şekilde işlenmesini sağlar. Tahliye helezonları, konveyör bantları ve metal ayırıcılar ile tam uyumlu olan makine, entegre geri dönüşüm hatları için idealdir. Optimize edilmiş kesici geometrisi ve uzun rotor yapısı, homojen parçalama ve düşük enerji tüketimi sağlar.',
            paragraph3: 'MT Makina TSH-60 katı atık parçalama makinası, 600 mm rotor uzunluğu, 24 adet sertleştirilmiş çelik bıçak, otomatik yağlama sistemi ve güçlendirilmiş rulman yapısı ile minimum bakım gerektirir. Değiştirilebilir elek sistemi (20-60 mm) ile farklı çıkış boyutları ayarlanabilir. Bu tek şaftlı katı atık parçalama makinesi, plastik hurda kırma makinası, balya parçalama makinası ve kauçuk parçalama makinası uygulamalarında da etkili sonuçlar verir. Kompakt tasarımı sayesinde sınırlı alanlarda bile verimli çalışır ve mevcut üretim hatlarına kolayca entegre edilir.',
            paragraph4: 'Tek şaftlı parçalama makinesi teknolojisi, geniş elek yüzeyi ve optimize edilmiş kesici geometrisi ile yüksek verimlilik sunar. TSH-60 modeli, plastik geri dönüşüm tesisleri, ahşap atık işleme merkezleri, kağıt-karton geri kazanım üniteleri, tekstil geri dönüşüm fabrikaları ve ambalaj atığı işleme tesisleri için ideal bir yatırımdır. Güçlü tahrik motorları ve dayanıklı kesme aletleri sayesinde zorlu koşullarda bile güvenilir performans sergiler. Katı atık parçalama makinası fiyatları konusunda rekabetçi fiyatlandırma ve düşük işletme maliyeti sunar.',
            paragraph5: 'TSH-60 tek şaftlı parçalama makinesi, enerji verimliliği sunan özel bıçak tasarımı ve otomatik kapanma özelliği ile işletme maliyetlerini minimize eder. Hurda lastik parçalama makinası, palet parçalama makinası ve kumaş parçalama makinesi gibi çeşitli uygulamalarda enerji tüketimini düşük tutarak yüksek verimlilik sağlar. Elektronik atık, e-atık ve karma atık ön işleme projelerinde de başarıyla kullanılabilir. CE sertifikalı güvenlik standartları ve 2 yıl garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-60, geri dönüşüm süreçlerini optimize ederek işletmelere çevresel ve ekonomik avantajlar sunar. Plastik parçalama makinesi fiyat teklifi almak için MT Makina ile iletişime geçebilirsiniz. Türkiye\'nin lider parçalama makinesi üreticisi olarak, tek şaftlı katı atık parçalama makinesi, çift şaftlı parçalama makinesi ve dört şaftlı parçalama makinesi modelleri ile geniş bir ürün yelpazesi sunuyoruz. TSH-60, küçük ölçekli geri dönüşüm tesisleri ve start-up projeler için mükemmel bir başlangıç yatırımıdır.'
        },
        en: {
            intro: 'TSH-60 single shaft solid waste shredder is a compact and powerful industrial shredding solution specially designed for small and medium recycling facilities and plastic processing plants.',
            paragraph1: 'TSH-60 single shaft shredder, with 15-30 kW motor power and 600x1100 mm shredding area, provides high efficiency in plastic shredder, fabric shredder, paper shredder and pallet shredder applications. With 500-800 kg/hour processing capacity, it combines plastic crusher and scrap plastic crusher functions in one machine. This single shaft shredder shows superior performance in shredding PET bottles, PP-PE materials, HDPE caps, film plastics, textile waste, paper-cardboard, packaging materials and light wood waste.',
            paragraph2: 'Equipped with advanced PLC controlled automation system, TSH-60 single shaft shredder guarantees uninterrupted production with automatic reverse function, overload protection and real-time motor load monitoring features. Being an economical investment in terms of plastic crusher prices, this system ensures efficient processing of large and difficult wastes thanks to hydraulic pressure mechanism. Fully compatible with discharge screws, conveyor belts and metal separators, the machine is ideal for integrated recycling lines.',
            paragraph3: 'MT Makina TSH-60 solid waste shredder has 600 mm rotor length, 24 hardened steel blades, automatic lubrication system and reinforced bearing structure requiring minimum maintenance. Different output sizes can be adjusted with replaceable screen system (20-60 mm). This single shaft solid waste shredder also provides effective results in plastic scrap crusher, bale shredder and rubber shredder applications. Thanks to its compact design, it works efficiently even in limited spaces and easily integrates into existing production lines.',
            paragraph4: 'Single shaft shredder technology offers high efficiency with wide screen surface and optimized cutter geometry. TSH-60 model is an ideal investment for plastic recycling facilities, wood waste processing centers, paper-cardboard recovery units, textile recycling factories and packaging waste processing facilities. It demonstrates reliable performance even in harsh conditions thanks to powerful drive motors and durable cutting tools. Offers competitive pricing and low operating costs in terms of solid waste shredder prices.',
            paragraph5: 'TSH-60 single shaft shredder minimizes operating costs with special blade design and automatic shutdown feature offering energy efficiency. It provides low energy consumption and high efficiency in various applications such as scrap tire shredder, pallet shredder and fabric shredder. It can also be successfully used in electronic waste, e-waste and mixed waste pre-processing projects. Supported by CE certified safety standards and 2-year warranty.',
            paragraph6: 'TSH-60 providing sustainability in waste management offers environmental and economic advantages to businesses by optimizing recycling processes. You can contact MT Makina for plastic shredder price quote. As Turkey\'s leading shredder manufacturer, we offer a wide product range with single shaft solid waste shredder, dual shaft shredder and quad shaft shredder models. TSH-60 is an excellent starter investment for small-scale recycling facilities and start-up projects.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-60 - компактное и мощное промышленное решение для измельчения, специально разработанное для малых и средних перерабатывающих предприятий и заводов по переработке пластмасс.',
            paragraph1: 'Одновальный измельчитель TSH-60 с мощностью двигателя 15-30 кВт и зоной измельчения 600x1100 мм обеспечивает высокую эффективность в применениях измельчителя пластика, ткани, бумаги и поддонов. С производительностью 500-800 кг/час он объединяет функции дробилки пластика и дробилки пластикового лома в одной машине. Этот одновальный измельчитель демонстрирует превосходную производительность при измельчении ПЭТ-бутылок, материалов PP-PE, крышек HDPE, пленочных пластиков, текстильных отходов, бумаги-картона и легких древесных отходов.',
            paragraph2: 'Оснащенный усовершенствованной системой автоматизации с ПЛК-управлением, одновальный измельчитель TSH-60 гарантирует бесперебойное производство благодаря функции автоматического реверса, защите от перегрузки и мониторингу нагрузки двигателя в реальном времени. Являясь экономичной инвестицией по ценам дробилок пластика, эта система обеспечивает эффективную переработку крупных и сложных отходов благодаря гидравлическому механизму прессования.',
            paragraph3: 'Измельчитель твердых отходов MT Makina TSH-60 имеет длину ротора 600 мм, 24 закаленных стальных ножа, автоматическую систему смазки и усиленную конструкцию подшипников, требующую минимального обслуживания. Различные размеры на выходе можно регулировать с помощью сменной системы сит (20-60 мм). Этот одновальный измельчитель твердых отходов также обеспечивает эффективные результаты в применениях дробилки пластикового лома, измельчителя тюков и измельчителя резины.',
            paragraph4: 'Технология одновального измельчителя предлагает высокую эффективность благодаря широкой поверхности сита и оптимизированной геометрии резака. Модель TSH-60 является идеальной инвестицией для предприятий по переработке пластика, центров обработки древесных отходов, подразделений восстановления бумаги-картона, текстильных перерабатывающих заводов и предприятий по переработке упаковочных отходов.',
            paragraph5: 'Одновальный измельчитель TSH-60 минимизирует эксплуатационные расходы благодаря специальной конструкции ножей и функции автоматического отключения, обеспечивающей энергоэффективность. Он также может успешно использоваться в проектах по переработке электронных отходов и смешанных отходов. Поддерживается сертифицированными стандартами безопасности CE и 2-летней гарантией.',
            paragraph6: 'TSH-60, обеспечивающий устойчивость в управлении отходами, предлагает экологические и экономические преимущества предприятиям, оптимизируя процессы переработки. Вы можете связаться с MT Makina для получения ценового предложения на измельчитель пластика. Как ведущий производитель измельчителей Турции, мы предлагаем широкий ассортимент продукции с моделями одновальных, двухвальных и четырехвальных измельчителей твердых отходов. TSH-60 - отличная стартовая инвестиция для малых перерабатывающих предприятий и стартап-проектов.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-60 هي حل تمزيق صناعي مدمج وقوي مصمم خصيصاً لمرافق إعادة التدوير الصغيرة والمتوسطة ومصانع معالجة البلاستيك.',
            paragraph1: 'آلة التمزيق أحادية العمود TSH-60 بقوة محرك 15-30 كيلووات ومنطقة تمزيق 600×1100 مم توفر كفاءة عالية في تطبيقات تمزيق البلاستيك والأقمشة والورق والمنصات. بسعة معالجة 500-800 كجم/ساعة، تجمع بين وظائف كسارة البلاستيك وكسارة خردة البلاستيك في آلة واحدة. تظهر أداءً متفوقاً في تمزيق زجاجات PET ومواد PP-PE وأغطية HDPE والبلاستيك الفيلمي ونفايات المنسوجات والورق-الكرتون ومواد التعبئة والتغليف ونفايات الخشب الخفيفة.',
            paragraph2: 'مجهزة بنظام أتمتة PLC متقدم، تضمن آلة التمزيق أحادية العمود TSH-60 إنتاجاً متواصلاً مع وظيفة الرجوع التلقائي وحماية الحمل الزائد ومراقبة حمل المحرك في الوقت الفعلي. كونها استثماراً اقتصادياً من حيث أسعار كسارات البلاستيك، يضمن هذا النظام معالجة فعالة للنفايات الكبيرة والصعبة بفضل آلية الضغط الهيدروليكي.',
            paragraph3: 'آلة تمزيق النفايات الصلبة MT Makina TSH-60 لها طول دوار 600 مم و24 شفرة فولاذية مقواة ونظام تشحيم تلقائي وهيكل محمل معزز يتطلب الحد الأدنى من الصيانة. يمكن تعديل أحجام المخرجات المختلفة بنظام الشاشة القابل للاستبدال (20-60 مم). توفر هذه الآلة أيضاً نتائج فعالة في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط.',
            paragraph4: 'تقنية التمزيق أحادية العمود توفر كفاءة عالية مع سطح شاشة واسع وهندسة قاطع محسنة. طراز TSH-60 استثمار مثالي لمرافق إعادة تدوير البلاستيك ومراكز معالجة نفايات الخشب ووحدات استعادة الورق-الكرتون ومصانع إعادة تدوير المنسوجات ومرافق معالجة نفايات التعبئة والتغليف.',
            paragraph5: 'آلة التمزيق أحادية العمود TSH-60 تقلل تكاليف التشغيل بتصميم شفرات خاص وميزة الإغلاق التلقائي التي توفر كفاءة الطاقة. يمكن استخدامها بنجاح في مشاريع معالجة النفايات الإلكترونية والنفايات المختلطة. مدعومة بمعايير السلامة المعتمدة CE وضمان سنتين.',
            paragraph6: 'TSH-60 التي توفر الاستدامة في إدارة النفايات تقدم مزايا بيئية واقتصادية للشركات من خلال تحسين عمليات إعادة التدوير. يمكنك الاتصال بـ MT Makina للحصول على عرض أسعار آلة تمزيق البلاستيك. كشركة رائدة في تصنيع آلات التمزيق في تركيا، نقدم مجموعة واسعة من المنتجات مع نماذج آلات تمزيق النفايات الصلبة أحادية وثنائية ورباعية العمود. TSH-60 استثمار ممتاز للبدء لمرافق إعادة التدوير الصغيرة والمشاريع الناشئة.'
        }
    },
    'TSH-80': {
        tr: {
            intro: 'TSH-80 tek şaftlı katı atık parçalama makinesi, orta ölçekli üretim tesisleri ve profesyonel geri dönüşüm merkezleri için güçlü, verimli ve ekonomik bir parçalama çözümü sunan endüstriyel sınıf bir sistemdir.',
            paragraph1: 'TSH-80 tek şaftlı parçalama makinesi, 22-45 kW motor gücü ile 800x1100 mm geniş parçalama alanına sahiptir. 800-1200 kg/saat kapasite ile günlük yüksek hacimli atık işleme gereksinimlerini karşılayan bu plastik parçalama makinesi, PET şişeler, PP-PE malzemeler, HDPE konteynerler, plastik film atıkları, tekstil döküntüleri, ahşap paletler ve endüstriyel ambalaj atıklarının parçalanmasında üstün performans gösterir. Yüksek tork ve düşük hız kombinasyonu ile çalışan tek şaftlı parçalama makinesi, plastik kırma makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi olarak çok yönlü kullanım sunar.',
            paragraph2: 'Gelişmiş PLC otomasyon sistemi ile donatılmış TSH-80 katı atık parçalama makinası, gerçek zamanlı motor yükü izleme, otomatik başlatma-durdurma ve acil durum güvenlik sistemleri içerir. 800 mm rotor uzunluğu ve 32 adet yüksek kaliteli sertleştirilmiş çelik bıçak, homojen parçalama ve uzun ömürlü kullanım garantisi verir. Plastik parçalama makinası ve hurda plastik kırma makinası uygulamalarında hidrolik baskı sistemi sayesinde malzemeler daha sıkı bir şekilde bıçaklarla temas ederek verimli parçalama sağlar. Geri dönüşüm kırma makinası olarak optimize edilmiş kesici geometrisi ile enerji verimliliği sunar.',
            paragraph3: 'TSH-80 tek şaftlı parçalama makinesi, orta büyüklükteki geri dönüşüm tesisleri, plastik işleme fabrikaları, ahşap atık yönetim merkezleri ve tekstil geri dönüşüm üniteleri için optimize edilmiştir. Değiştirilebilir elek sistemi (20-80 mm) ile çıkış boyutu kontrolü yapılabilir. Düşük enerji tüketimi ve yüksek verimlilik oranı ile katı atık parçalama makinası fiyatları açısından ekonomik çözümler sunan bu sistem, işletme maliyetlerini minimize eder. Tahliye helezonları, konveyör bantları, metal ayırıcılar ve boru mıknatısları ile entegre edilebilir.',
            paragraph4: 'MT Makina TSH-80 parçalama makinesi, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası gibi farklı sektörlerde etkili çözümler sunar. Güçlü tahrik motorları ve dayanıklı kesme aletleri sayesinde zorlu koşullarda bile güvenilir performans sergiler. Uzun rotor ve geniş elek yüzeyi ile yüksek verimlilik sunan tek şaftlı parçalama makinesi teknolojisi, geri dönüşüm ve atık yönetiminde önemli bir rol oynar. Plastik kırma makinesi fiyatları konusunda rekabetçi avantaj sunar.',
            paragraph5: 'Enerji verimliliği sunan özel bıçak tasarımı ve otomatik kapanma özelliği ile TSH-80, işletme maliyetlerini düşürür ve çevre dostu üretim sağlar. Bu tek şaftlı katı atık parçalama makinesi, plastik geri dönüşüm tesisleri, ambalaj atığı işleme tesisleri, kağıt-karton geri kazanım merkezleri ve endüstriyel atık yönetim sistemleri için ideal bir yatırımdır. Otomatik yağlama sistemi ve güçlendirilmiş rulman yapısı ile minimum bakım gerektirir. CE sertifikalı güvenlik standartları ve 2 yıl garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-80 tek şaftlı parçalama makinesi, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik ve çevresel faydalar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, tek şaftlı katı atık parçalama makinesi fiyat teklifi ve teknik danışmanlık hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi ve palet parçalama makinesi ihtiyaçlarınız için bizimle iletişime geçin. TSH-80, orta ölçekli tesisler için ideal maliyet-performans dengesi sunan profesyonel bir parçalama çözümüdür.'
        },
        en: {
            intro: 'TSH-80 single shaft solid waste shredder is an industrial-class system offering powerful, efficient and economical shredding solution for medium-scale production facilities and professional recycling centers.',
            paragraph1: 'TSH-80 single shaft shredder has a wide shredding area of 800x1100 mm with 22-45 kW motor power. With 800-1200 kg/hour capacity, it meets daily high-volume waste processing requirements. This plastic shredder shows superior performance in shredding PET bottles, PP-PE materials, HDPE containers, plastic film waste, textile scraps, wooden pallets and industrial packaging waste. The single shaft shredder operating with high torque and low speed combination offers versatile use as plastic crusher, fabric shredder, pallet shredder and paper shredder.',
            paragraph2: 'Equipped with advanced PLC automation system, TSH-80 solid waste shredder includes real-time motor load monitoring, automatic start-stop and emergency safety systems. 800 mm rotor length and 32 high-quality hardened steel blades guarantee homogeneous shredding and long-lasting use. In plastic shredder and scrap plastic crusher applications, the hydraulic pressure system ensures materials come into tighter contact with blades for efficient shredding. Offers energy efficiency with optimized cutter geometry as a recycling crusher.',
            paragraph3: 'TSH-80 single shaft shredder is optimized for medium-sized recycling facilities, plastic processing factories, wood waste management centers and textile recycling units. Output size control can be done with replaceable screen system (20-80 mm). This system minimizes operating costs with low energy consumption and high efficiency ratio, offering economical solutions in terms of solid waste shredder prices. Can be integrated with discharge screws, conveyor belts, metal separators and pipe magnets.',
            paragraph4: 'MT Makina TSH-80 shredder offers effective solutions in different sectors such as plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder. It demonstrates reliable performance even in harsh conditions thanks to powerful drive motors and durable cutting tools. Single shaft shredder technology with long rotor and wide screen surface plays an important role in recycling and waste management, offering high efficiency. Provides competitive advantage in terms of plastic crusher prices.',
            paragraph5: 'TSH-80 reduces operating costs and ensures environmentally friendly production with special blade design and automatic shutdown feature offering energy efficiency. This single shaft solid waste shredder is an ideal investment for plastic recycling facilities, packaging waste processing plants, paper-cardboard recovery centers and industrial waste management systems. Requires minimum maintenance with automatic lubrication system and reinforced bearing structure. Supported by CE certified safety standards and 2-year warranty.',
            paragraph6: 'TSH-80 single shaft shredder providing sustainability in waste management offers high efficiency and environmental benefits to businesses by optimizing recycling processes. MT Makina, Turkey\'s leading shredder manufacturer, offers single shaft solid waste shredder price quotes and technical consultancy services. Contact us for your plastic shredder, fabric shredder and pallet shredder needs. TSH-80 is a professional shredding solution offering ideal cost-performance balance for medium-scale facilities.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-80 - система промышленного класса, предлагающая мощное, эффективное и экономичное решение для измельчения для производственных объектов среднего масштаба и профессиональных центров переработки.',
            paragraph1: 'Одновальный измельчитель TSH-80 имеет широкую зону измельчения 800x1100 мм с мощностью двигателя 22-45 кВт. С производительностью 800-1200 кг/час он отвечает ежедневным требованиям обработки больших объемов отходов. Этот измельчитель пластика демонстрирует превосходную производительность при измельчении ПЭТ-бутылок, материалов PP-PE, контейнеров HDPE, отходов пластиковой пленки, текстильных обрезков, деревянных поддонов и промышленных упаковочных отходов.',
            paragraph2: 'Оснащенный усовершенствованной системой автоматизации ПЛК, измельчитель твердых отходов TSH-80 включает мониторинг нагрузки двигателя в реальном времени, автоматический запуск-остановку и системы аварийной безопасности. Длина ротора 800 мм и 32 высококачественных закаленных стальных ножа гарантируют однородное измельчение и долговечное использование. В применениях измельчителя пластика и дробилки пластикового лома гидравлическая система прессования обеспечивает более плотный контакт материалов с ножами для эффективного измельчения.',
            paragraph3: 'Одновальный измельчитель TSH-80 оптимизирован для перерабатывающих предприятий среднего размера, заводов по переработке пластмасс, центров управления древесными отходами и подразделений переработки текстиля. Контроль размера на выходе может осуществляться с помощью сменной системы сит (20-80 мм). Эта система минимизирует эксплуатационные расходы благодаря низкому энергопотреблению и высокому коэффициенту эффективности.',
            paragraph4: 'Измельчитель MT Makina TSH-80 предлагает эффективные решения в различных секторах, таких как дробилка пластикового лома, измельчитель тюков, измельчитель резины и измельчитель изношенных шин. Он демонстрирует надежную работу даже в суровых условиях благодаря мощным приводным двигателям и прочным режущим инструментам.',
            paragraph5: 'TSH-80 снижает эксплуатационные расходы и обеспечивает экологически чистое производство благодаря специальной конструкции ножей и функции автоматического отключения, обеспечивающей энергоэффективность. Этот одновальный измельчитель твердых отходов является идеальной инвестицией для предприятий по переработке пластика, предприятий по переработке упаковочных отходов и центров восстановления бумаги-картона. Поддерживается сертифицированными стандартами безопасности CE и 2-летней гарантией.',
            paragraph6: 'Одновальный измельчитель TSH-80, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность и экологические преимущества предприятиям, оптимизируя процессы переработки. MT Makina, ведущий производитель измельчителей Турции, предлагает ценовые предложения на одновальные измельчители твердых отходов и технические консультации. TSH-80 - профессиональное решение для измельчения, предлагающее идеальный баланс стоимости и производительности для средних предприятий.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-80 هي نظام من الدرجة الصناعية يقدم حلاً قوياً وفعالاً واقتصادياً للتمزيق لمرافق الإنتاج متوسطة الحجم ومراكز إعادة التدوير المهنية.',
            paragraph1: 'آلة التمزيق أحادية العمود TSH-80 لها منطقة تمزيق واسعة 800×1100 مم بقوة محرك 22-45 كيلووات. بسعة 800-1200 كجم/ساعة، تلبي متطلبات معالجة النفايات اليومية ذات الحجم الكبير. تظهر أداءً متفوقاً في تمزيق زجاجات PET ومواد PP-PE وحاويات HDPE ونفايات الأفلام البلاستيكية وقصاصات المنسوجات والمنصات الخشبية ونفايات التعبئة والتغليف الصناعية.',
            paragraph2: 'مجهزة بنظام أتمتة PLC متقدم، تتضمن آلة تمزيق النفايات الصلبة TSH-80 مراقبة حمل المحرك في الوقت الفعلي والبدء والإيقاف التلقائي وأنظمة السلامة في حالات الطوارئ. يضمن طول الدوار 800 مم و32 شفرة فولاذية مقواة عالية الجودة تمزيقاً متجانساً واستخداماً طويل الأمد. في تطبيقات تمزيق البلاستيك وكسارة خردة البلاستيك، يضمن نظام الضغط الهيدروليكي اتصالاً أكثر إحكاماً للمواد بالشفرات.',
            paragraph3: 'تم تحسين آلة التمزيق أحادية العمود TSH-80 لمرافق إعادة التدوير متوسطة الحجم ومصانع معالجة البلاستيك ومراكز إدارة نفايات الخشب ووحدات إعادة تدوير المنسوجات. يمكن التحكم في حجم المخرجات باستخدام نظام الشاشة القابل للاستبدال (20-80 مم). تقلل هذه الآلة من تكاليف التشغيل بفضل انخفاض استهلاك الطاقة ونسبة الكفاءة العالية.',
            paragraph4: 'تقدم آلة تمزيق MT Makina TSH-80 حلولاً فعالة في قطاعات مختلفة مثل كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط وتمزيق الإطارات. تظهر أداءً موثوقاً حتى في الظروف القاسية بفضل محركات الدفع القوية وأدوات القطع المتينة.',
            paragraph5: 'تقلل TSH-80 من تكاليف التشغيل وتضمن إنتاجاً صديقاً للبيئة بتصميم شفرات خاص وميزة الإغلاق التلقائي التي توفر كفاءة الطاقة. هذه آلة تمزيق النفايات الصلبة أحادية العمود استثمار مثالي لمرافق إعادة تدوير البلاستيك ومصانع معالجة نفايات التعبئة والتغليف ومراكز استعادة الورق-الكرتون. مدعومة بمعايير السلامة المعتمدة CE وضمان سنتين.',
            paragraph6: 'آلة التمزيق أحادية العمود TSH-80 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية للشركات من خلال تحسين عمليات إعادة التدوير. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وخدمات استشارية تقنية. TSH-80 حل تمزيق احترافي يقدم توازناً مثالياً بين التكلفة والأداء للمنشآت متوسطة الحجم.'
        }
    },
    'TSH-100': {
        tr: {
            intro: 'TSH-100 tek şaftlı katı atık parçalama makinesi, yüksek kapasite gerektiren endüstriyel uygulamalar ve büyük ölçekli geri dönüşüm tesisleri için tasarlanmış profesyonel ve güvenilir bir parçalama sistemidir.',
            paragraph1: 'TSH-100 tek şaftlı parçalama makinesi, 30-75 kW güçlü motor seçenekleri ile 1000x1300 mm geniş parçalama alanı sunar. 1200-1800 kg/saat işleme kapasitesi ile büyük ölçekli üretim tesislerinin plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarını karşılar. Kalın duvarlı plastikler, büyük çaplı ahşap parçalar, endüstriyel konteynerler, IBC tanklar, ağır tekstil atıkları, büyük hacimli ambalaj malzemeleri ve kompozit atıkları kolayca parçalayan bu sistem, plastik kırma makinesi ve hurda plastik kırma makinası olarak endüstriyel standartta performans sağlar.',
            paragraph2: 'İleri seviye PLC kontrol paneli, touch screen operatör arayüzü, uzaktan izleme ve bakım hatırlatma sistemleri ile donatılmış TSH-100 katı atık parçalama makinası, geri dönüşüm ve atık yönetiminde önemli bir rol oynar. 1000 mm rotor, 40 adet premium kalite sertleştirilmiş çelik bıçak ve hidrolik itici sistem sayesinde sürekli ve kesintisiz üretim garantisi verir. Otomatik ters çalışma ve akıllı yük yönetimi, plastik parçalama makinası ve geri dönüşüm kırma makinası uygulamalarında maksimum verimlilik sağlar. Yüksek tork ve düşük hız kombinasyonu ile zorlu malzemeleri güvenle işler.',
            paragraph3: 'MT Makina TSH-100 tek şaftlı parçalama makinesi, büyük plastik geri dönüşüm tesisleri, ahşap palet üreticileri, kompozit malzeme işleyiciler, endüstriyel atık yönetim firmaları ve tekstil geri dönüşüm fabrikaları için ideal çözümdür. Modüler yapısı sayesinde tahliye helezonları, konveyör bantları, metal ayırıcılar, boru mıknatısları ve seperatörlerle entegre edilebilir. CE sertifikalı güvenlik standartları ve 2 yıl garanti ile desteklenir. Katı atık parçalama makinası fiyatları açısından yatırım maliyeti düşük, geri dönüş hızı yüksektir.',
            paragraph4: 'Tek şaftlı parçalama makinesi teknolojisi ile TSH-100, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında da üstün sonuçlar verir. Optimize edilmiş kesici geometrisi ve geniş elek yüzeyi sayesinde homojen parçalama ve düşük enerji tüketimi sağlar. Güçlü tahrik motorları ve dayanıklı kesme aletleri ile zorlu koşullarda güvenilir performans sergiler. Değiştirilebilir elek sistemi (20-100 mm) ile farklı çıkış boyutları ayarlanabilir.',
            paragraph5: 'Enerji verimliliği sunan özel bıçak tasarımı ve otomatik kapanma özelliği ile TSH-100 tek şaftlı katı atık parçalama makinesi, işletme maliyetlerini minimize eder. Plastik kırma makinesi fiyatları konusunda rekabetçi fiyatlandırma sunan bu sistem, büyük kapasiteli geri dönüşüm projelerinde tercih edilmektedir. Otomatik yağlama sistemi, güçlendirilmiş rulman yapısı ve sağlam çelik gövde ile minimum bakım gerektirir. Elektronik atık, e-atık işleme ve belediye atık yönetim projelerinde de başarıyla kullanılabilir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-100, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina olarak, tek şaftlı katı atık parçalama makinesi, çift şaftlı parçalama makinesi ve dört şaftlı parçalama makinesi modellerimizle geniş bir ürün yelpazesi sunuyoruz. Plastik parçalama makinesi fiyat teklifi ve teknik danışmanlık hizmetleri için bizimle iletişime geçin. TSH-100, büyük ölçekli endüstriyel projeler için önerilen profesyonel sınıf parçalama çözümüdür.'
        },
        en: {
            intro: 'TSH-100 single shaft solid waste shredder is a professional and reliable shredding system designed for industrial applications and large-scale recycling facilities requiring high capacity.',
            paragraph1: 'TSH-100 single shaft shredder offers a wide shredding area of 1000x1300 mm with powerful motor options of 30-75 kW. With 1200-1800 kg/hour processing capacity, it meets plastic shredder, fabric shredder, pallet shredder and paper shredder needs of large-scale production facilities. It easily shreds thick-walled plastics, large wood parts, industrial containers, IBC tanks, heavy textile waste, large volume packaging materials and composite waste, providing industrial standard performance as plastic crusher and scrap plastic crusher.',
            paragraph2: 'Equipped with advanced PLC control panel, touch screen operator interface, remote monitoring and maintenance reminder systems, TSH-100 solid waste shredder plays an important role in recycling and waste management. With 1000 mm rotor, 40 premium quality hardened steel blades and hydraulic pusher system, it guarantees continuous and uninterrupted production. Automatic reverse operation and intelligent load management provide maximum efficiency in plastic shredder and recycling crusher applications. Safely processes difficult materials with high torque and low speed combination.',
            paragraph3: 'MT Makina TSH-100 single shaft shredder is an ideal solution for large plastic recycling facilities, wooden pallet manufacturers, composite material processors, industrial waste management companies and textile recycling factories. Thanks to its modular structure, it can be integrated with discharge screws, conveyor belts, metal separators, pipe magnets and separators. Supported by CE certified safety standards and 2-year warranty. Low investment cost and fast return rate in terms of solid waste shredder prices.',
            paragraph4: 'With single shaft shredder technology, TSH-100 also provides superior results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Optimized cutter geometry and wide screen surface provide homogeneous shredding and low energy consumption. Demonstrates reliable performance in harsh conditions with powerful drive motors and durable cutting tools. Different output sizes can be adjusted with replaceable screen system (20-100 mm).',
            paragraph5: 'TSH-100 single shaft solid waste shredder minimizes operating costs with special blade design and automatic shutdown feature offering energy efficiency. This system offering competitive pricing in terms of plastic crusher prices is preferred in large capacity recycling projects. Requires minimum maintenance with automatic lubrication system, reinforced bearing structure and solid steel body. Can also be successfully used in electronic waste, e-waste processing and municipal waste management projects.',
            paragraph6: 'TSH-100 providing sustainability in waste management offers high efficiency, environmental benefits and economic advantages to businesses by optimizing recycling processes. As MT Makina, Turkey\'s leading shredder manufacturer, we offer a wide product range with single shaft solid waste shredder, dual shaft shredder and quad shaft shredder models. Contact us for plastic shredder price quote and technical consultancy services. TSH-100 is the recommended professional class shredding solution for large-scale industrial projects.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-100 - профессиональная и надежная система измельчения, разработанная для промышленных применений и крупномасштабных перерабатывающих предприятий, требующих высокой производительности.',
            paragraph1: 'Одновальный измельчитель TSH-100 предлагает широкую зону измельчения 1000x1300 мм с мощными вариантами двигателя 30-75 кВт. С производительностью обработки 1200-1800 кг/час он отвечает потребностям крупномасштабных производственных объектов в измельчителе пластика, ткани, поддонов и бумаги. Легко измельчает толстостенный пластик, крупные деревянные детали, промышленные контейнеры, баки IBC, тяжелые текстильные отходы, упаковочные материалы большого объема и композитные отходы, обеспечивая производительность промышленного стандарта.',
            paragraph2: 'Оснащенный усовершенствованной панелью управления ПЛК, сенсорным интерфейсом оператора, системами дистанционного мониторинга и напоминания о техническом обслуживании, измельчитель твердых отходов TSH-100 играет важную роль в переработке и управлении отходами. С ротором 1000 мм, 40 ножами премиум-качества и гидравлической системой толкателя гарантирует непрерывное и бесперебойное производство. Автоматическая реверсивная работа и интеллектуальное управление нагрузкой обеспечивают максимальную эффективность.',
            paragraph3: 'Одновальный измельчитель MT Makina TSH-100 - идеальное решение для крупных предприятий по переработке пластика, производителей деревянных поддонов, переработчиков композитных материалов, компаний по управлению промышленными отходами и текстильных перерабатывающих фабрик. Благодаря модульной структуре может быть интегрирован с разгрузочными шнеками, конвейерными лентами, магнитными сепараторами и сепараторами. Поддерживается сертифицированными стандартами безопасности CE и 2-летней гарантией.',
            paragraph4: 'С технологией одновального измельчителя TSH-100 также обеспечивает превосходные результаты в применениях дробилки пластикового лома, измельчителя тюков, измельчителя резины и измельчителя изношенных шин. Оптимизированная геометрия резака и широкая поверхность сита обеспечивают однородное измельчение и низкое энергопотребление. Демонстрирует надежную работу в суровых условиях.',
            paragraph5: 'Одновальный измельчитель твердых отходов TSH-100 минимизирует эксплуатационные расходы благодаря специальной конструкции ножей и функции автоматического отключения, обеспечивающей энергоэффективность. Требует минимального обслуживания с автоматической системой смазки, усиленной конструкцией подшипников и прочным стальным корпусом. Может также успешно использоваться в проектах по переработке электронных отходов и муниципальному управлению отходами.',
            paragraph6: 'TSH-100, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность, экологические преимущества и экономические выгоды предприятиям, оптимизируя процессы переработки. Как MT Makina, ведущий производитель измельчителей Турции, мы предлагаем широкий ассортимент продукции с моделями одновальных, двухвальных и четырехвальных измельчителей твердых отходов. Свяжитесь с нами для получения ценового предложения и технических консультаций. TSH-100 - рекомендуемое профессиональное решение для крупномасштабных промышленных проектов.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-100 هي نظام تمزيق احترافي وموثوق مصمم للتطبيقات الصناعية ومرافق إعادة التدوير واسعة النطاق التي تتطلب سعة عالية.',
            paragraph1: 'آلة التمزيق أحادية العمود TSH-100 توفر منطقة تمزيق واسعة 1000×1300 مم مع خيارات محرك قوية 30-75 كيلووات. بسعة معالجة 1200-1800 كجم/ساعة، تلبي احتياجات مرافق الإنتاج واسعة النطاق من تمزيق البلاستيك والأقمشة والمنصات والورق. تمزق بسهولة البلاستيك ذو الجدران السميكة وقطع الخشب الكبيرة والحاويات الصناعية وخزانات IBC ونفايات المنسوجات الثقيلة ومواد التعبئة والتغليف كبيرة الحجم والنفايات المركبة.',
            paragraph2: 'مجهزة بلوحة تحكم PLC متقدمة وواجهة مشغل بشاشة تعمل باللمس وأنظمة المراقبة عن بُعد وتذكير الصيانة، تلعب آلة تمزيق النفايات الصلبة TSH-100 دوراً هاماً في إعادة التدوير وإدارة النفايات. مع دوار 1000 مم و40 شفرة فولاذية مقواة عالية الجودة ونظام دفع هيدروليكي، تضمن إنتاجاً مستمراً ومتواصلاً. توفر العملية العكسية التلقائية وإدارة الحمل الذكية أقصى كفاءة.',
            paragraph3: 'آلة التمزيق أحادية العمود MT Makina TSH-100 حل مثالي لمرافق إعادة تدوير البلاستيك الكبيرة ومصنعي المنصات الخشبية ومعالجي المواد المركبة وشركات إدارة النفايات الصناعية ومصانع إعادة تدوير المنسوجات. بفضل هيكلها المعياري، يمكن دمجها مع براغي التفريغ وأحزمة النقل والفواصل المغناطيسية. مدعومة بمعايير السلامة المعتمدة CE وضمان سنتين.',
            paragraph4: 'مع تقنية التمزيق أحادية العمود، توفر TSH-100 أيضاً نتائج متفوقة في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط وتمزيق الإطارات. توفر هندسة القاطع المحسنة وسطح الشاشة الواسع تمزيقاً متجانساً واستهلاكاً منخفضاً للطاقة. تظهر أداءً موثوقاً في الظروف القاسية.',
            paragraph5: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-100 تقلل تكاليف التشغيل بتصميم شفرات خاص وميزة الإغلاق التلقائي التي توفر كفاءة الطاقة. تتطلب الحد الأدنى من الصيانة مع نظام التشحيم التلقائي وهيكل المحمل المعزز والجسم الفولاذي الصلب. يمكن استخدامها بنجاح أيضاً في مشاريع معالجة النفايات الإلكترونية وإدارة النفايات البلدية.',
            paragraph6: 'TSH-100 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية ومزايا اقتصادية للشركات من خلال تحسين عمليات إعادة التدوير. كـ MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، نقدم مجموعة واسعة من المنتجات مع نماذج آلات تمزيق النفايات الصلبة أحادية وثنائية ورباعية العمود. اتصل بنا للحصول على عرض أسعار وخدمات استشارية تقنية. TSH-100 حل التمزيق الاحترافي الموصى به للمشاريع الصناعية واسعة النطاق.'
        }
    },
    'TSH-130': {
        tr: {
            intro: 'TSH-130 tek şaftlı katı atık parçalama makinesi, ağır hizmet tipi endüstriyel uygulamalar ve yüksek kapasiteli geri dönüşüm kompleksleri için tasarlanmış güçlü ve dayanıklı bir parçalama sistemidir.',
            paragraph1: 'TSH-130 tek şaftlı parçalama makinesi, 45-110 kW yüksek torklu motor gücü ile 1300x1600 mm ekstra geniş parçalama alanı sunar. 1800-2500 kg/saat işleme kapasitesi ile sürekli üretim yapan büyük tesislerin plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarını karşılar. Kalın çeperli endüstriyel plastikler, büyük ahşap kütükler, yatak ve mobilya atıkları, büyük çaplı PVC borular, ağır tekstil balyaları, endüstriyel ambalaj konteynerleri ve ağır endüstriyel atıkların parçalanmasında üstün performans gösterir. Tek şaftlı parçalama makinesi teknolojisi ile plastik kırma makinesi ve hurda plastik kırma makinası işlevlerini endüstriyel kapasitede gerçekleştirir.',
            paragraph2: 'Endüstriyel sınıf PLC otomasyon sistemi ile donatılmış TSH-130 katı atık parçalama makinası, gerçek zamanlı üretim takibi, enerji tüketim analizi ve bakım planlama modülleri içerir. 1300 mm uzun rotor, 48 adet takviyeli sertleştirilmiş çelik bıçak sistemi ve güçlendirilmiş rulman yapısı ile 7/24 kesintisiz çalışma kapasitesine sahiptir. Hidrolik besleyici ve otomatik seviye kontrol sistemi, plastik parçalama makinası ve geri dönüşüm kırma makinası uygulamalarında operatör müdahalesini minimize eder. Yüksek tork ve düşük hız kombinasyonu ile ağır malzemeleri güvenle işler.',
            paragraph3: 'TSH-130 tek şaftlı parçalama makinesi, büyük kapasiteli plastik geri dönüşüm kompleksleri, ahşap işleme merkezleri, evsel eşya geri kazanım tesisleri, beyaz eşya parçalama üniteleri, mobilya atık yönetimi ve ağır sanayi atık yönetimi için optimize edilmiştir. Çift elek sistemi ile hem kaba hem de ince parçalama yapılabilir. Katı atık parçalama makinası fiyatları açısından yüksek dayanıklılık ve düşük işletme maliyeti ile yatırım geri dönüşü hızlıdır. Tahliye helezonları, konveyör bantları ve metal ayırıcılar ile entegre edilebilir.',
            paragraph4: 'MT Makina TSH-130 parçalama makinesi, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası gibi zorlu uygulamalarda etkili sonuçlar verir. Uzun rotor ve geniş elek yüzeyi ile optimize edilmiş kesici geometrisi, homojen parçalama ve enerji verimliliği sağlar. Güçlü tahrik motorları ve dayanıklı kesme aletleri sayesinde zorlu koşullarda bile güvenilir performans sergiler. Plastik kırma makinesi fiyatları konusunda büyük projeler için ekonomik avantaj sunar.',
            paragraph5: 'Enerji verimliliği sunan özel bıçak tasarımı ve otomatik kapanma özelliği ile TSH-130 tek şaftlı katı atık parçalama makinesi, işletme maliyetlerini minimize eder. Belediye entegre katı atık yönetim tesisleri, sanayi bölgesi ortak atık işleme merkezleri, büyük lojistik depoları ve evsel atık geri kazanım projeleri için ideal bir yatırımdır. Otomatik yağlama sistemi, güçlendirilmiş dişli kutusu ve sağlam çelik gövde ile minimum bakım gerektirir. CE ve ISO sertifikalı güvenlik standartları ile 2 yıl garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-130, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, tek şaftlı katı atık parçalama makinesi fiyat teklifi ve turnkey proje çözümleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık hizmetimizden yararlanın. TSH-130, ağır hizmet tipi endüstriyel projeler için tercih edilen güvenilir parçalama çözümüdür.'
        },
        en: {
            intro: 'TSH-130 single shaft solid waste shredder is a high-performance system offering powerful and efficient shredding solution for large-capacity production processes and industrial recycling facilities.',
            paragraph1: 'TSH-130 model offers an extra wide shredding area of 1300x1600 mm with 45-110 kW high torque motor power. With 1800-2500 kg/hour processing capacity, it meets the requirements of large facilities with continuous production. This plastic shredder shows superior performance in shredding thick-walled industrial plastics, large wood logs, bed and furniture waste, large diameter pipes, heavy textile bales, industrial packaging containers and heavy industrial waste. Single shaft shredder combines plastic crusher and scrap plastic crusher functions at industrial capacity.',
            paragraph2: 'Industrial grade PLC automation includes real-time production tracking, energy consumption analysis and maintenance planning modules. With 1300 mm long rotor, 48 reinforced hardened steel blade system and strengthened bearing structure, it has 7/24 uninterrupted operation capacity. Hydraulic feeder and automatic level control system minimize operator intervention. Offers high torque and low speed combination for safe processing of heavy materials in plastic shredder and fabric shredder applications.',
            paragraph3: 'TSH-130 is optimized for large capacity plastic recycling complexes, wood processing centers, household appliance recovery facilities, white goods shredding units, furniture waste management and heavy industry waste management. Both coarse and fine shredding can be done with dual screen system. Fast return on investment in terms of solid waste shredder prices with high durability and low operating costs. Can be integrated with discharge screws, conveyor belts and metal separators.',
            paragraph4: 'MT Makina TSH-130 shredder provides effective results in challenging applications such as plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder. Long rotor and wide screen surface with optimized cutter geometry provides homogeneous shredding and energy efficiency. Demonstrates reliable performance even in harsh conditions thanks to powerful drive motors and durable cutting tools. Offers economic advantage for large projects in terms of plastic crusher prices.',
            paragraph5: 'TSH-130 single shaft solid waste shredder minimizes operating costs with special blade design and automatic shutdown feature offering energy efficiency. Ideal investment for municipal integrated solid waste management facilities, industrial zone joint waste processing centers, large logistics warehouses and household waste recovery projects. Requires minimum maintenance with automatic lubrication system, reinforced gearbox and solid steel body. Supported by CE and ISO certified safety standards and 2-year warranty.',
            paragraph6: 'TSH-130 providing sustainability in waste management offers high efficiency, environmental benefits and economic advantages to businesses by optimizing recycling processes. MT Makina, Turkey\'s leading shredder manufacturer, offers single shaft solid waste shredder price quotes and turnkey project solutions. Contact our professional consultancy team for your plastic shredder, fabric shredder, pallet shredder and paper shredder needs. TSH-130 is the reliable shredding solution preferred for heavy-duty industrial projects.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-130 - высокопроизводительная система, предлагающая мощное и эффективное решение для измельчения для производственных процессов большой мощности и промышленных перерабатывающих предприятий.',
            paragraph1: 'Модель TSH-130 предлагает сверхширокую зону измельчения 1300x1600 мм с высокомоментным двигателем 45-110 кВт. С производительностью обработки 1800-2500 кг/час она отвечает требованиям крупных предприятий с непрерывным производством. Показывает превосходную производительность при измельчении толстостенного промышленного пластика, крупных деревянных бревен, отходов мебели и кроватей, труб большого диаметра, тяжелых текстильных тюков и тяжелых промышленных отходов.',
            paragraph2: 'Промышленная автоматизация ПЛК включает отслеживание производства в реальном времени, анализ энергопотребления и модули планирования технического обслуживания. С длинным ротором 1300 мм, системой из 48 усиленных закаленных стальных ножей и усиленной конструкцией подшипников имеет возможность непрерывной работы 7/24. Гидравлический податчик и система автоматического контроля уровня минимизируют вмешательство оператора.',
            paragraph3: 'TSH-130 оптимизирован для крупных комплексов по переработке пластика, центров обработки древесины, предприятий по утилизации бытовой техники, подразделений измельчения белой техники и управления отходами тяжелой промышленности. Возможно как грубое, так и тонкое измельчение с двойной системой сит. Быстрая окупаемость инвестиций благодаря высокой долговечности и низким эксплуатационным расходам.',
            paragraph4: 'Измельчитель MT Makina TSH-130 обеспечивает эффективные результаты в сложных применениях, таких как дробилка пластикового лома, измельчитель тюков, измельчитель резины и измельчитель изношенных шин. Длинный ротор и широкая поверхность сита с оптимизированной геометрией резака обеспечивают однородное измельчение и энергоэффективность. Демонстрирует надежную работу даже в суровых условиях.',
            paragraph5: 'Одновальный измельчитель твердых отходов TSH-130 минимизирует эксплуатационные расходы благодаря специальной конструкции ножей и функции автоматического отключения, обеспечивающей энергоэффективность. Идеальная инвестиция для муниципальных интегрированных объектов управления твердыми отходами и совместных центров переработки промышленных зон. Поддерживается стандартами безопасности CE и ISO и 2-летней гарантией.',
            paragraph6: 'TSH-130, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность, экологические преимущества и экономические выгоды предприятиям, оптимизируя процессы переработки. MT Makina, ведущий производитель измельчителей Турции, предлагает ценовые предложения на одновальные измельчители и комплексные проектные решения. TSH-130 - надежное решение для измельчения, предпочитаемое для тяжелых промышленных проектов.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-130 هي نظام عالي الأداء يقدم حلاً قوياً وفعالاً للتمزيق لعمليات الإنتاج ذات السعة العالية ومرافق إعادة التدوير الصناعية.',
            paragraph1: 'يوفر طراز TSH-130 منطقة تقطيع واسعة للغاية 1300×1600 مم مع قوة محرك عزم دوران عالية 45-110 كيلووات. بسعة معالجة 1800-2500 كجم/ساعة، يلبي متطلبات المنشآت الكبيرة ذات الإنتاج المستمر. يظهر أداءً متفوقاً في تقطيع البلاستيك الصناعي ذو الجدران السميكة وجذوع الخشب الكبيرة ونفايات الأسرة والأثاث والأنابيب ذات القطر الكبير وبالات المنسوجات الثقيلة والنفايات الصناعية الثقيلة.',
            paragraph2: 'تتضمن أتمتة PLC الصناعية تتبع الإنتاج في الوقت الفعلي وتحليل استهلاك الطاقة ووحدات تخطيط الصيانة. مع دوار طويل 1300 مم ونظام 48 شفرة فولاذية مقواة معززة وهيكل محمل معزز، لديه قدرة تشغيل متواصل 7/24. يقلل المغذي الهيدروليكي ونظام التحكم في المستوى التلقائي من تدخل المشغل.',
            paragraph3: 'تم تحسين TSH-130 لمجمعات إعادة تدوير البلاستيك ذات السعة الكبيرة ومراكز معالجة الخشب ومرافق استعادة الأجهزة المنزلية ووحدات تمزيق الأجهزة البيضاء وإدارة نفايات الصناعة الثقيلة. يمكن إجراء التقطيع الخشن والناعم باستخدام نظام الشاشة المزدوجة. عائد سريع على الاستثمار مع متانة عالية وتكاليف تشغيل منخفضة.',
            paragraph4: 'تقدم آلة تمزيق MT Makina TSH-130 نتائج فعالة في التطبيقات الصعبة مثل كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط وتمزيق الإطارات. توفر الدوار الطويل وسطح الشاشة الواسع مع هندسة القاطع المحسنة تمزيقاً متجانساً وكفاءة في الطاقة. تظهر أداءً موثوقاً حتى في الظروف القاسية.',
            paragraph5: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-130 تقلل تكاليف التشغيل بتصميم شفرات خاص وميزة الإغلاق التلقائي التي توفر كفاءة الطاقة. استثمار مثالي لمرافق إدارة النفايات الصلبة البلدية المتكاملة ومراكز معالجة النفايات المشتركة في المناطق الصناعية. مدعومة بمعايير السلامة CE وISO وضمان سنتين.',
            paragraph6: 'TSH-130 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية ومزايا اقتصادية للشركات من خلال تحسين عمليات إعادة التدوير. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وحلول مشاريع متكاملة. TSH-130 حل التمزيق الموثوق المفضل للمشاريع الصناعية الثقيلة.'
        }
    },
    'TSH-160': {
        tr: {
            intro: 'TSH-160 tek şaftlı katı atık parçalama makinesi, çift motor teknolojisi ile ekstra yüksek kapasite ve performans sunan endüstriyel sınıf bir parçalama sistemidir. Türkiye\'nin en yüksek kapasiteli tek şaftlı parçalama makinelerinden biri olan TSH-160, mega ölçekli geri dönüşüm projeleri için tasarlanmıştır.',
            paragraph1: 'TSH-160 tek şaftlı parçalama makinesi, 2x 55-132 kW çift motor konfigürasyonu ile 1600x1800 mm ultra geniş parçalama alanı sunar. 3500-4500 kg/saat işleme kapasitesi ile saatte 4 tona yakın atık işleyebilen bu sistem, büyük hacimli endüstriyel konteynerler, otomotiv tampon ve parçaları, büyük çaplı boru sistemleri, kompozit malzemeler, ağır plastik atıklar ve toplu atık işleme projelerinde kullanılır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi uygulamalarında endüstriyel standartta performans sağlayan TSH-160, plastik kırma makinesi ve hurda plastik kırma makinası olarak mega kapasiteli tesislerin ihtiyaçlarını karşılar.',
            paragraph2: 'Siemens PLC tabanlı ileri otomasyon sistemi ile donatılmış TSH-160 katı atık parçalama makinası, SCADA entegrasyonu, uzaktan müdahale, predictive maintenance (öngörülü bakım) ve IoT bağlantı altyapısı sunar. 1600 mm ekstra uzun rotor, 64 adet özel alaşımlı sertleştirilmiş çelik bıçak ve takviyeli dişli kutusu ile maksimum tork ve dayanıklılık sağlar. Çift motor sistemi sayesinde plastik parçalama makinası ve geri dönüşüm kırma makinası uygulamalarında ağır yüklerde bile kesintisiz çalışma garantisi verir. Yüksek tork ve düşük hız kombinasyonu ile zorlu malzemeleri güvenle işler.',
            paragraph3: 'MT Makina TSH-160 tek şaftlı parçalama makinesi, büyük ölçekli geri dönüşüm kompleksleri, otomotiv geri kazanım merkezleri, belediye atık yönetim tesisleri ve sanayi bölgesi ortak atık işleme merkezleri için tasarlanmıştır. Tam otomatik konveyör besleme, manyetik seperatör, hava seperatörü ve balya presi ile entegre edilebilir. Avrupa standartlarında güvenlik ve CE sertifikası ile desteklenir. Katı atık parçalama makinası fiyatları açısından yüksek kapasite ile düşük birim maliyeti sunar.',
            paragraph4: 'Tek şaftlı parçalama makinesi teknolojisinin en gelişmiş örneklerinden olan TSH-160, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında olağanüstü sonuçlar verir. Uzun rotor ve geniş elek yüzeyi ile optimize edilmiş kesici geometrisi, homojen parçalama ve enerji verimliliği sağlar. Tahliye helezonları, konveyör bantları, metal ayırıcılar ve boru mıknatısları ile tam uyumludur. Plastik kırma makinesi fiyatları konusunda mega projeler için ekonomik çözümler sunar.',
            paragraph5: 'Enerji verimliliği sunan özel bıçak tasarımı ve otomatik kapanma özelliği ile TSH-160 tek şaftlı katı atık parçalama makinesi, işletme maliyetlerini minimize eder. Endüstri 4.0 standartlarına uygun otomasyon altyapısı ile uzaktan izleme ve kontrol imkanı sunar. Otomotiv sanayi atıkları, beyaz eşya geri dönüşümü, büyük plastik tank parçalama ve mega belediye atık yönetim projeleri için ideal bir yatırımdır. Otomatik yağlama sistemi, güçlendirilmiş rulman yapısı ve sağlam çelik gövde ile minimum bakım gerektirir. CE ve ISO sertifikalı güvenlik standartları ile 3 yıl garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-160, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, tek şaftlı katı atık parçalama makinesi fiyat teklifi, turnkey proje çözümleri ve 7/24 teknik destek hizmetleri sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. TSH-160, mega ölçekli endüstriyel projeler ve yüksek kapasiteli geri dönüşüm kompleksleri için önerilen premium sınıf parçalama çözümüdür.'
        },
        en: {
            intro: 'TSH-160 single shaft solid waste shredder is an industrial-class system offering extra high capacity and performance with dual motor technology. One of Turkey\'s highest capacity single shaft shredders, TSH-160 is designed for mega-scale recycling projects.',
            paragraph1: 'TSH-160 single shaft shredder offers an ultra-wide shredding area of 1600x1800 mm with 2x 55-132 kW dual motor configuration. With a processing capacity of 3500-4500 kg/hour, this system capable of processing nearly 4 tons of waste per hour is used in large volume industrial containers, automotive bumpers and parts, large diameter pipe systems, composite materials, heavy plastic waste and bulk waste processing projects. TSH-160 provides industrial-standard performance in plastic shredder, fabric shredder, pallet shredder and paper shredder applications, meeting the needs of mega-capacity facilities as plastic crusher and scrap plastic crusher.',
            paragraph2: 'Siemens PLC-based advanced automation system offers SCADA integration, remote intervention, predictive maintenance and IoT connectivity infrastructure. With 1600 mm extra long rotor, 64 special alloy hardened steel blades and reinforced gearbox, it provides maximum torque and durability. Thanks to the dual motor system, it guarantees uninterrupted operation even under heavy loads in plastic shredder and recycling crusher applications. Processes challenging materials safely with high torque and low speed combination.',
            paragraph3: 'MT Makina TSH-160 single shaft shredder is designed for large-scale recycling complexes, automotive recovery centers, municipal waste management facilities and industrial zone joint waste processing centers. Can be integrated with fully automatic conveyor feeding, magnetic separator, air separator and bale press. Supported by European standards safety and CE certification. Offers high capacity with low unit cost in terms of solid waste shredder prices.',
            paragraph4: 'TSH-160, one of the most advanced examples of single shaft shredder technology, provides extraordinary results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Long rotor and wide screen surface with optimized cutter geometry provides homogeneous shredding and energy efficiency. Fully compatible with discharge screws, conveyor belts, metal separators and pipe magnets. Offers economic solutions for mega projects in terms of plastic crusher prices.',
            paragraph5: 'TSH-160 single shaft solid waste shredder minimizes operating costs with special blade design and automatic shutdown feature offering energy efficiency. Offers remote monitoring and control with automation infrastructure compliant with Industry 4.0 standards. Ideal investment for automotive industry waste, white goods recycling, large plastic tank shredding and mega municipal waste management projects. Requires minimum maintenance with automatic lubrication system, reinforced bearing structure and solid steel body. Supported by CE and ISO certified safety standards and 3-year warranty.',
            paragraph6: 'TSH-160 providing sustainability in waste management offers high efficiency, environmental benefits and economic advantages to businesses by optimizing recycling processes. MT Makina, Turkey\'s leading shredder manufacturer, offers single shaft solid waste shredder price quotes, turnkey project solutions and 24/7 technical support services. Contact our professional consultancy team for your plastic shredder, fabric shredder, pallet shredder and paper shredder needs. TSH-160 is the recommended premium class shredding solution for mega-scale industrial projects and high-capacity recycling complexes.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-160 - система промышленного класса, предлагающая сверхвысокую производительность с технологией двойного двигателя. Один из самых высокопроизводительных одновальных измельчителей Турции, TSH-160 разработан для мега-масштабных проектов переработки.',
            paragraph1: 'Одновальный измельчитель TSH-160 предлагает сверхширокую зону измельчения 1600x1800 мм с конфигурацией двойного двигателя 2x 55-132 кВт. С производительностью обработки 3500-4500 кг/час эта система способна обрабатывать почти 4 тонны отходов в час. Используется в крупногабаритных промышленных контейнерах, автомобильных бамперах и деталях, трубных системах большого диаметра, композитных материалах и проектах массовой переработки отходов.',
            paragraph2: 'Передовая система автоматизации на базе ПЛК Siemens предлагает интеграцию SCADA, дистанционное вмешательство, прогнозируемое техническое обслуживание и инфраструктуру подключения IoT. С дополнительным длинным ротором 1600 мм, 64 ножами из специального закаленного сплава и усиленным редуктором обеспечивает максимальный крутящий момент и долговечность. Благодаря системе с двумя двигателями гарантирует бесперебойную работу даже при больших нагрузках.',
            paragraph3: 'Одновальный измельчитель MT Makina TSH-160 разработан для крупномасштабных комплексов переработки, центров восстановления автомобилей, муниципальных объектов по управлению отходами и совместных центров переработки промышленных зон. Может быть интегрирован с полностью автоматической конвейерной подачей, магнитным сепаратором, воздушным сепаратором и пресс-подборщиком. Поддерживается европейскими стандартами безопасности и сертификацией CE.',
            paragraph4: 'TSH-160, один из самых передовых примеров технологии одновального измельчителя, обеспечивает выдающиеся результаты в применениях дробилки пластикового лома, измельчителя тюков, измельчителя резины и измельчителя изношенных шин. Длинный ротор и широкая поверхность сита с оптимизированной геометрией резака обеспечивают однородное измельчение и энергоэффективность.',
            paragraph5: 'Одновальный измельчитель твердых отходов TSH-160 минимизирует эксплуатационные расходы благодаря специальной конструкции ножей и функции автоматического отключения, обеспечивающей энергоэффективность. Предлагает дистанционный мониторинг и управление с автоматизационной инфраструктурой, соответствующей стандартам Индустрии 4.0. Поддерживается стандартами безопасности CE и ISO и 3-летней гарантией.',
            paragraph6: 'TSH-160, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность, экологические преимущества и экономические выгоды предприятиям, оптимизируя процессы переработки. MT Makina, ведущий производитель измельчителей Турции, предлагает ценовые предложения на одновальные измельчители, комплексные проектные решения и круглосуточную техническую поддержку. TSH-160 - рекомендуемое решение премиум-класса для мега-масштабных промышленных проектов.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-160 هي نظام من الدرجة الصناعية يوفر سعة وأداء عاليين للغاية بتقنية المحرك المزدوج. واحدة من أعلى آلات التمزيق أحادية العمود سعة في تركيا، TSH-160 مصممة للمشاريع ضخمة النطاق.',
            paragraph1: 'آلة التمزيق أحادية العمود TSH-160 توفر منطقة تمزيق فائقة الاتساع 1600×1800 مم مع تكوين محرك مزدوج 2×55-132 كيلووات. بسعة معالجة 3500-4500 كجم/ساعة، هذا النظام قادر على معالجة ما يقرب من 4 أطنان من النفايات في الساعة. يستخدم في الحاويات الصناعية كبيرة الحجم ومصدات وأجزاء السيارات وأنظمة الأنابيب ذات القطر الكبير والمواد المركبة ومشاريع معالجة النفايات بالجملة.',
            paragraph2: 'يوفر نظام الأتمتة المتقدم القائم على PLC من Siemens تكامل SCADA والتدخل عن بُعد والصيانة التنبؤية والبنية التحتية لاتصال إنترنت الأشياء. مع دوار طويل إضافي 1600 مم و64 شفرة سبائك خاصة مقسى وعلبة تروس معززة، يوفر أقصى عزم دوران ومتانة. بفضل نظام المحرك المزدوج، يضمن تشغيلاً متواصلاً حتى تحت الأحمال الثقيلة.',
            paragraph3: 'تم تصميم آلة تمزيق MT Makina TSH-160 أحادية العمود لمجمعات إعادة التدوير واسعة النطاق ومراكز استعادة السيارات ومرافق إدارة النفايات البلدية ومراكز معالجة النفايات المشتركة في المناطق الصناعية. يمكن دمجها مع التغذية بالناقل الأوتوماتيكي بالكامل والفاصل المغناطيسي والفاصل الهوائي ومكبس البالات. مدعومة بمعايير السلامة الأوروبية وشهادة CE.',
            paragraph4: 'TSH-160، واحدة من أكثر الأمثلة تقدماً لتقنية التمزيق أحادية العمود، توفر نتائج استثنائية في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط وتمزيق الإطارات. توفر الدوار الطويل وسطح الشاشة الواسع مع هندسة القاطع المحسنة تمزيقاً متجانساً وكفاءة في الطاقة.',
            paragraph5: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-160 تقلل تكاليف التشغيل بتصميم شفرات خاص وميزة الإغلاق التلقائي التي توفر كفاءة الطاقة. توفر مراقبة وتحكم عن بُعد مع بنية تحتية للأتمتة متوافقة مع معايير الصناعة 4.0. مدعومة بمعايير السلامة CE وISO وضمان 3 سنوات.',
            paragraph6: 'TSH-160 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية ومزايا اقتصادية للشركات من خلال تحسين عمليات إعادة التدوير. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وحلول مشاريع متكاملة ودعم فني على مدار الساعة. TSH-160 حل التمزيق المتميز الموصى به للمشاريع الصناعية ضخمة النطاق.'
        }
    },
    'TSH-200': {
        tr: {
            intro: 'TSH-200 tek şaftlı katı atık parçalama makinesi, MT Makina\'nın en büyük ve en güçlü modeli olup maksimum kapasite gerektiren mega projeler ve uluslararası standartlarda geri dönüşüm kompleksleri için tasarlanmış premium sınıf bir parçalama sistemidir.',
            paragraph1: 'TSH-200 tek şaftlı parçalama makinesi, 2x 75-160 kW çift motor sistemi ile 2000x2300 mm dev parçalama alanı sunar. 4500-6000 kg/saat işleme kapasitesi ile saatte 5 tona kadar atık işleyebilme gücüne sahip olan bu sistem, endüstriyel büyük hacimli konteynerler, otobüs-kamyon iç döşemeleri, büyük çaplı plastik tanklar, endüstriyel makine kasaları, büyük ahşap yapılar, mega plastik atıklar ve toplu elektronik atık projelerinde kullanılır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi uygulamalarında dünya standartlarında performans sağlayan TSH-200, plastik kırma makinesi ve hurda plastik kırma makinası olarak mega kapasiteli tesislerin tüm ihtiyaçlarını karşılar.',
            paragraph2: 'En ileri Siemens S7-1500 PLC ve SCADA sistemi ile donatılmış TSH-200 katı atık parçalama makinası, yapay zeka destekli yük optimizasyonu, gerçek zamanlı performans analizi, uzaktan tam kontrol ve bulut tabanlı veri saklama özelliklerine sahiptir. 2000 mm ultra uzun rotor, 80 adet premium kalite sertleştirilmiş çelik bıçak, endüstriyel sınıf hidrolik sistem ve takviyeli çelik gövde ile en zorlu malzemeleri bile kolayca işler. Çift motor ve diferansiyel dişli sistemi sayesinde plastik parçalama makinası ve geri dönüşüm kırma makinası uygulamalarında eşsiz tork ve verim sunar. Yüksek tork ve düşük hız kombinasyonu ile güvenle çalışır.',
            paragraph3: 'TSH-200 tek şaftlı parçalama makinesi, mega ölçekli geri dönüşüm kompleksleri, belediye entegre katı atık yönetim tesisleri, otomotiv sanayi atık merkezleri, liman ve gümrük atık işleme merkezleri için ideal çözümdür. Tam otomatik hat entegrasyonu, multi-seperatör sistemleri, tahliye helezonları, konveyör bantları, metal ayırıcılar, boru mıknatısları, otomatik paketleme ve sevkiyat sistemleri ile kombine edilebilir. Katı atık parçalama makinası fiyatları açısından mega kapasitede en düşük birim maliyeti sunar.',
            paragraph4: 'Tek şaftlı parçalama makinesi teknolojisinin en gelişmiş ve en güçlü örneği olan TSH-200, plastik hurda kırma makinası, balya parçalama makinası, kauçuk parçalama makinası ve hurda lastik parçalama makinası uygulamalarında olağanüstü sonuçlar verir. Uzun rotor ve geniş elek yüzeyi ile optimize edilmiş kesici geometrisi, homojen parçalama ve enerji verimliliği sağlar. Predictive maintenance (öngörülü bakım), IoT sensör ağı ve digital twin simülasyonu ile Endüstri 4.0 standartlarını karşılar. Plastik kırma makinesi fiyatları konusunda mega projeler için en ekonomik çözümü sunar.',
            paragraph5: 'Enerji verimliliği sunan özel bıçak tasarımı ve akıllı yük yönetimi ile TSH-200 tek şaftlı katı atık parçalama makinesi, işletme maliyetlerini minimize eder. Metropol belediye entegre atık yönetim projeleri, uluslararası geri dönüşüm konsorsiyumları, serbest bölge atık işleme merkezleri ve çevre organizasyonu büyük ölçekli projeleri için ideal bir yatırımdır. Otomatik yağlama sistemi, güçlendirilmiş rulman yapısı, endüstriyel soğutma sistemi ve sağlam çelik gövde ile minimum bakım gerektirir. Tüm küresel güvenlik standartları (CE, UL, ISO 9001, ISO 14001, ISO 45001) ve 5 yıl platinum garanti ile desteklenir.',
            paragraph6: 'Atık yönetiminde sürdürülebilirlik sağlayan TSH-200, geri dönüşüm süreçlerini optimize ederek işletmelere yüksek verimlilik, çevresel faydalar ve ekonomik avantajlar sunar. Türkiye\'nin lider parçalama makinesi üreticisi MT Makina, tek şaftlı katı atık parçalama makinesi fiyat teklifi, turnkey proje çözümleri, 7/24 global teknik destek ve yerinde bakım servisi sunmaktadır. Plastik parçalama makinesi, kumaş parçalama makinesi, palet parçalama makinesi ve kağıt parçalama makinesi ihtiyaçlarınız için profesyonel danışmanlık ekibimizle iletişime geçin. TSH-200, mega ölçekli endüstriyel projeler, uluslararası geri dönüşüm kompleksleri ve maksimum kapasite gerektiren turnkey projeler için önerilen en üst sınıf parçalama çözümüdür.'
        },
        en: {
            intro: 'TSH-200 single shaft solid waste shredder is MT Makina\'s largest and most powerful model, a premium-class shredding system designed for mega projects requiring maximum capacity and international-standard recycling complexes.',
            paragraph1: 'TSH-200 single shaft shredder offers a giant shredding area of 2000x2300 mm with 2x 75-160 kW dual motor system. With a processing capacity of 4500-6000 kg/hour, this system with the power to process up to 5 tons of waste per hour is used for industrial large volume containers, bus-truck interior trim, large diameter plastic tanks, industrial machine casings, large wooden structures, mega plastic waste and bulk electronic waste projects. TSH-200 providing world-class performance in plastic shredder, fabric shredder, pallet shredder and paper shredder applications meets all needs of mega capacity facilities as plastic crusher and scrap plastic crusher.',
            paragraph2: 'Equipped with the most advanced Siemens S7-1500 PLC and SCADA system, TSH-200 solid waste shredder features AI-assisted load optimization, real-time performance analysis, full remote control and cloud-based data storage. With 2000 mm ultra-long rotor, 80 premium quality hardened steel blades, industrial grade hydraulic system and reinforced steel body, it easily processes even the toughest materials. It offers unique torque and efficiency thanks to dual motor and differential gear system. Operates safely with high torque and low speed combination in plastic shredder and recycling crusher applications.',
            paragraph3: 'TSH-200 single shaft shredder is the ideal solution for mega-scale recycling complexes, municipal integrated solid waste management facilities, automotive industrial waste centers, port and customs waste processing centers. It can be combined with fully automatic line integration, multi-separator systems, discharge screws, conveyor belts, metal separators, pipe magnets, automatic packaging and shipping systems. Offers the lowest unit cost at mega capacity in terms of solid waste shredder prices.',
            paragraph4: 'TSH-200, the most advanced and powerful example of single shaft shredder technology, provides extraordinary results in plastic scrap crusher, bale shredder, rubber shredder and scrap tire shredder applications. Long rotor and wide screen surface with optimized cutter geometry provides homogeneous shredding and energy efficiency. Meets Industry 4.0 standards with predictive maintenance, IoT sensor network and digital twin simulation. Offers the most economical solution for mega projects in terms of plastic crusher prices.',
            paragraph5: 'TSH-200 single shaft solid waste shredder minimizes operating costs with special blade design and smart load management offering energy efficiency. Ideal investment for metropolitan municipal integrated waste management projects, international recycling consortiums, free zone waste processing centers and environmental organization large-scale projects. Requires minimum maintenance with automatic lubrication system, reinforced bearing structure, industrial cooling system and solid steel body. Supported by all global safety standards (CE, UL, ISO 9001, ISO 14001, ISO 45001) and 5-year platinum warranty.',
            paragraph6: 'TSH-200 providing sustainability in waste management offers high efficiency, environmental benefits and economic advantages to businesses by optimizing recycling processes. MT Makina, Turkey\'s leading shredder manufacturer, offers single shaft solid waste shredder price quotes, turnkey project solutions, 24/7 global technical support and on-site maintenance service. Contact our professional consultancy team for your plastic shredder, fabric shredder, pallet shredder and paper shredder needs. TSH-200 is the top-class shredding solution recommended for mega-scale industrial projects, international recycling complexes and turnkey projects requiring maximum capacity.'
        },
        ru: {
            intro: 'Одновальный измельчитель твердых отходов TSH-200 - самая большая и мощная модель MT Makina, система измельчения премиум-класса, разработанная для мега-проектов, требующих максимальной производительности, и комплексов переработки международного стандарта.',
            paragraph1: 'Одновальный измельчитель TSH-200 предлагает гигантскую зону измельчения 2000x2300 мм с системой двойного двигателя 2x 75-160 кВт. С производительностью обработки 4500-6000 кг/час эта система способна обрабатывать до 5 тонн отходов в час. Используется для промышленных контейнеров большого объема, внутренней отделки автобусов и грузовиков, пластиковых резервуаров большого диаметра, корпусов промышленного оборудования, больших деревянных конструкций, мега пластиковых отходов и крупных проектов по электронным отходам.',
            paragraph2: 'Оснащенный самой передовой системой ПЛК Siemens S7-1500 и SCADA, измельчитель твердых отходов TSH-200 включает оптимизацию нагрузки с помощью ИИ, анализ производительности в реальном времени, полное дистанционное управление и облачное хранение данных. С ультрадлинным ротором 2000 мм, 80 ножами премиум-качества из закаленной стали, гидравлической системой промышленного класса и усиленным стальным корпусом легко обрабатывает даже самые прочные материалы. Обеспечивает уникальный крутящий момент и эффективность благодаря системе с двумя двигателями и дифференциальной передачей.',
            paragraph3: 'Одновальный измельчитель TSH-200 - идеальное решение для мегамасштабных комплексов переработки, муниципальных интегрированных объектов управления твердыми отходами, центров промышленных отходов автомобильной промышленности, портовых и таможенных центров переработки отходов. Может комбинироваться с полностью автоматической интеграцией линии, мультисепараторными системами, разгрузочными шнеками, конвейерами, автоматическими системами упаковки и отгрузки.',
            paragraph4: 'TSH-200, самый передовой и мощный пример технологии одновального измельчителя, обеспечивает выдающиеся результаты в применениях дробилки пластикового лома, измельчителя тюков, измельчителя резины и измельчителя изношенных шин. Длинный ротор и широкая поверхность сита с оптимизированной геометрией резака обеспечивают однородное измельчение и энергоэффективность. Соответствует стандартам Индустрии 4.0 с прогнозируемым обслуживанием, сетью датчиков IoT и симуляцией цифрового двойника.',
            paragraph5: 'Одновальный измельчитель твердых отходов TSH-200 минимизирует эксплуатационные расходы благодаря специальной конструкции ножей и интеллектуальному управлению нагрузкой, обеспечивающему энергоэффективность. Идеальная инвестиция для проектов интегрированного управления отходами столичных муниципалитетов, международных консорциумов переработки и крупномасштабных экологических проектов. Поддерживается всеми глобальными стандартами безопасности (CE, UL, ISO 9001, ISO 14001, ISO 45001) и 5-летней платиновой гарантией.',
            paragraph6: 'TSH-200, обеспечивающий устойчивость в управлении отходами, предлагает высокую эффективность, экологические преимущества и экономические выгоды предприятиям, оптимизируя процессы переработки. MT Makina, ведущий производитель измельчителей Турции, предлагает ценовые предложения на одновальные измельчители, комплексные проектные решения, круглосуточную глобальную техническую поддержку и сервис обслуживания на месте. TSH-200 - решение для измельчения высшего класса, рекомендуемое для мега-масштабных проектов.'
        },
        ar: {
            intro: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-200 هي أكبر وأقوى طراز من MT Makina، نظام تمزيق من الفئة المتميزة مصمم للمشاريع الضخمة التي تتطلب أقصى سعة ومجمعات إعادة التدوير بالمعايير الدولية.',
            paragraph1: 'آلة التمزيق أحادية العمود TSH-200 توفر منطقة تمزيق عملاقة 2000×2300 مم مع نظام محرك مزدوج 2×75-160 كيلووات. بسعة معالجة 4500-6000 كجم/ساعة، هذا النظام بقدرة معالجة تصل إلى 5 أطنان من النفايات في الساعة يستخدم للحاويات الصناعية كبيرة الحجم والتزيين الداخلي للحافلات والشاحنات وخزانات البلاستيك ذات القطر الكبير وأغلفة الآلات الصناعية والهياكل الخشبية الكبيرة والنفايات البلاستيكية الضخمة ومشاريع النفايات الإلكترونية بالجملة.',
            paragraph2: 'مجهزة بأحدث نظام PLC Siemens S7-1500 وSCADA، تتميز آلة تمزيق النفايات الصلبة TSH-200 بتحسين الحمل بمساعدة الذكاء الاصطناعي وتحليل الأداء في الوقت الفعلي والتحكم الكامل عن بُعد وتخزين البيانات السحابي. مع دوار فائق الطول 2000 مم و80 شفرة متميزة من الفولاذ المقسى ونظام هيدروليكي بدرجة صناعية وهيكل فولاذي معزز، يعالج بسهولة حتى أصعب المواد. يوفر عزم دوران وكفاءة فريدة بفضل نظام المحرك المزدوج ونظام التروس التفاضلي.',
            paragraph3: 'آلة التمزيق أحادية العمود TSH-200 هي الحل الأمثل لمجمعات إعادة التدوير على نطاق ضخم ومرافق الإدارة المتكاملة للنفايات الصلبة البلدية ومراكز النفايات الصناعية للسيارات ومراكز معالجة نفايات الموانئ والجمارك. يمكن دمجها مع التكامل الآلي الكامل للخط وأنظمة الفصل المتعددة وبراغي التفريغ والناقلات وأنظمة التعبئة والشحن التلقائية.',
            paragraph4: 'TSH-200، أكثر الأمثلة تقدماً وقوة لتقنية التمزيق أحادية العمود، توفر نتائج استثنائية في تطبيقات كسارة خردة البلاستيك وتمزيق البالات وتمزيق المطاط وتمزيق الإطارات. توفر الدوار الطويل وسطح الشاشة الواسع مع هندسة القاطع المحسنة تمزيقاً متجانساً وكفاءة في الطاقة. تلبي معايير الصناعة 4.0 مع الصيانة التنبؤية وشبكة مستشعرات إنترنت الأشياء ومحاكاة التوأم الرقمي.',
            paragraph5: 'آلة تمزيق النفايات الصلبة أحادية العمود TSH-200 تقلل تكاليف التشغيل بتصميم شفرات خاص وإدارة الحمل الذكية التي توفر كفاءة الطاقة. استثمار مثالي لمشاريع إدارة النفايات المتكاملة للبلديات الكبرى واتحادات إعادة التدوير الدولية ومراكز معالجة نفايات المناطق الحرة والمشاريع البيئية واسعة النطاق. مدعومة بجميع معايير السلامة العالمية (CE، UL، ISO 9001، ISO 14001، ISO 45001) وضمان بلاتيني 5 سنوات.',
            paragraph6: 'TSH-200 التي توفر الاستدامة في إدارة النفايات تقدم كفاءة عالية وفوائد بيئية ومزايا اقتصادية للشركات من خلال تحسين عمليات إعادة التدوير. MT Makina، الشركة الرائدة في تصنيع آلات التمزيق في تركيا، تقدم عروض أسعار وحلول مشاريع متكاملة ودعم فني عالمي على مدار الساعة وخدمة صيانة في الموقع. TSH-200 حل التمزيق من أعلى فئة الموصى به للمشاريع الصناعية ضخمة النطاق ومجمعات إعادة التدوير الدولية.'
        }
    }
};
