import { MultilingualModelDescription } from '../../types/descriptionTypes';

export const treeRootDescriptions: { [modelName: string]: MultilingualModelDescription } = {
    'TW-100': {
        tr: {
            intro: 'TW-100 ağaç kökü parçalama makinesi, orta ölçekli ağaç kökü ve odunsu atık işleme için tasarlanmış güçlü ve verimli bir çözümdür.',
            paragraph1: 'TW-100 model, 132-160 kW yüksek tork motor ile Ø 1000 mm parçalama alanı ve 500 mm rotor boyuna sahiptir. Çok bıçaklı rotor yapısı ve besleme dişleri sistemi ile ağaç kökleri, kalın dallar, hurda tahta, ahşap palet, MDF-sunta atıkları ve odunsu materyallerin etkili parçalanmasını sağlar. Yüksek tork - düşük hız kombinasyonu sayesinde zorlu malzemeleri hızla işler. Rotor aşırı yüklendiğinde besleme haznesinin otomatik ters dönmesi ile sıkışma önlenir ve kesintisiz çalışma garantisi verir.',
            paragraph2: 'Besleme haznesine monte edilmiş özel tasarım besleme dişleri, malzemelerin kontrollü şekilde rotora iletilmesini sağlar. Aşırı yüklenme durumunda otomatik ters çalışma sistemi devreye girer ve güvenli operasyon sağlar. Dayanıklı bıçak yapısı uzun ömürlü kullanım garantisi verir. Enerji verimli motor teknolojisi ile düşük işletme maliyeti sağlanır. Kullanıcı dostu kontrol paneli ile kolay operasyon ve bakım imkanı sunar.',
            paragraph3: 'MT Makina TW-100, orta ölçekli orman yönetimi, belediye park ve bahçe işletmeleri, ahşap işleme tesisleri ve geri dönüşüm merkezleri için ideal çözümdür. Parçalanan malzemeler biyokütle yakıt üretimi, kompozit malzeme hammaddesi, hayvan altlığı ve organik gübre olarak değerlendirilebilir. Opsiyonel dizel motor, mobil tasarım ve farklı elek seçenekleri ile ihtiyaca özel yapılandırılabilir. CE sertifikası ve 2 yıl garanti ile desteklenir.'
        },
        en: {
            intro: 'TW-100 tree root shredder is a powerful and efficient solution designed for medium-scale tree root and woody waste processing.',
            paragraph1: 'TW-100 model has Ø 1000 mm shredding area and 500 mm rotor length with 132-160 kW high-torque motor. Multi-blade rotor structure and feeding teeth system provide effective shredding of tree roots, thick branches, scrap wood, wooden pallets, MDF-chipboard waste and woody materials. Thanks to high torque - low speed combination, it quickly processes tough materials. Automatic reverse rotation of feeding hopper when rotor is overloaded prevents jamming and guarantees uninterrupted operation.',
            paragraph2: 'Specially designed feeding teeth mounted on feeding hopper ensure controlled feeding of materials to rotor. Automatic reverse operation system activates in case of overload and provides safe operation. Durable blade structure guarantees long-lasting use. Energy-efficient motor technology provides low operating costs. User-friendly control panel offers easy operation and maintenance.',
            paragraph3: 'MT Makina TW-100 is the ideal solution for medium-scale forest management, municipal park and garden operations, wood processing facilities and recycling centers. Shredded materials can be used as biomass fuel production, composite material raw materials, animal bedding and organic fertilizer. Can be configured to specific needs with optional diesel engine, mobile design and different screen options. Supported by CE certificate and 2-year warranty.'
        },
        ru: {
            intro: 'TW-100 измельчитель корней деревьев - это мощное и эффективное решение, разработанное для переработки корней деревьев и древесных отходов среднего масштаба.',
            paragraph1: 'Модель TW-100 имеет зону измельчения Ø 1000 мм и длину ротора 500 мм с высокомоментным двигателем 132-160 кВт. Многолопастная конструкция ротора и система подающих зубьев обеспечивают эффективное измельчение корней деревьев, толстых ветвей, обрезков древесины, деревянных поддонов, отходов МДФ-ДСП и древесных материалов. Благодаря комбинации высокого крутящего момента и низкой скорости быстро обрабатывает прочные материалы. Автоматическое обратное вращение загрузочного бункера при перегрузке ротора предотвращает заклинивание и гарантирует бесперебойную работу.',
            paragraph2: 'Специально разработанные подающие зубья, установленные на загрузочном бункере, обеспечивают контролируемую подачу материалов к ротору. Система автоматической реверсивной работы активируется в случае перегрузки и обеспечивает безопасную работу. Прочная конструкция ножей гарантирует долговечное использование. Энергоэффективная технология двигателя обеспечивает низкие эксплуатационные расходы. Удобная панель управления обеспечивает легкую эксплуатацию и обслуживание.',
            paragraph3: 'MT Makina TW-100 - идеальное решение для управления лесами среднего масштаба, муниципальных парковых и садовых хозяйств, деревообрабатывающих предприятий и центров переработки. Измельченные материалы могут использоваться для производства биомассового топлива, сырья для композитных материалов, подстилки для животных и органических удобрений. Может быть настроен в соответствии с конкретными потребностями с опциональным дизельным двигателем, мобильной конструкцией и различными вариантами сит. Поддерживается сертификатом CE и 2-летней гарантией.'
        },
        ar: {
            intro: 'آلة تقطيع جذور الأشجار TW-100 هي حل قوي وفعال مصمم لمعالجة جذور الأشجار والنفايات الخشبية متوسطة الحجم.',
            paragraph1: 'يتميز طراز TW-100 بمنطقة تقطيع Ø 1000 мм وطول دوار 500 مم مع محرك عالي العزم 132-160 كيلووات. يوفر هيكل الدوار متعدد الشفرات ونظام أسنان التغذية تقطيعًا فعالاً لجذور الأشجار والفروع السميكة وخردة الخشب والمنصات الخشبية ونفايات MDF-اللوح الحبيبي والمواد الخشبية. بفضل مزيج العزم العالي والسرعة المنخفضة، تعالج بسرعة المواد الصلبة. يمنع الدوران العكسي التلقائي لقادوس التغذية عند تحميل الدوار الزائد الانحشار ويضمن تشغيلًا مستمرًا.',
            paragraph2: 'تضمن أسنان التغذية المصممة خصيصًا والمركبة على قادوس التغذية التغذية المتحكم فيها للمواد إلى الدوار. ينشط نظام التشغيل العكسي التلقائي في حالة الحمل الزائد ويوفر تشغيلًا آمنًا. يضمن هيكل الشفرة المتين استخدامًا طويل الأمد. توفر تقنية المحرك الموفرة للطاقة تكاليف تشغيل منخفضة. توفر لوحة التحكم سهلة الاستخدام تشغيلًا وصيانة سهلة.',
            paragraph3: 'MT Makina TW-100 هو الحل الأمثل لإدارة الغابات متوسطة الحجم وعمليات الحدائق والمتنزهات البلدية ومرافق معالجة الخشب ومراكز إعادة التدوير. يمكن استخدام المواد المقطعة كإنتاج وقود الكتلة الحيوية والمواد الخام للمواد المركبة وفراش للحيوانات والأسمدة العضوية. يمكن تكوينه وفقًا للاحتياجات المحددة مع محرك ديزل اختياري وتصميم محمول وخيارات شاشة مختلفة. مدعوم بشهادة CE وضمان لمدة عامين.'
        }
    },
    'TW-150': {
        tr: {
            intro: 'TW-150 ağaç kökü parçalama makinesi, büyük ölçekli ağaç kökü ve ağır odunsu malzeme işleme için yüksek performans sunan profesyonel bir sistemdir.',
            paragraph1: 'TW-150 model, 160-220 kW güçlü motor ile Ø 1500 mm geniş parçalama alanı ve 800 mm rotor boyuna sahiptir. Güçlendirilmiş çok bıçaklı rotor ve çift sıra besleme dişleri sistemi ile kalın ağaç kökleri, büyük çaplı gövdeler, sanayi palet atıkları, ağır MDF-kontrplak kalıntıları ve sert odun türlerinin parçalanmasında üstün performans gösterir. Yüksek kapasiteli işleme ile saatte büyük miktarda malzeme parçalayabilir. Hidrolik destekli besleme sistemi ağır malzemelerin kolay yüklenmesini sağlar.',
            paragraph2: 'Gelişmiş PLC otomasyon sistemi, gerçek zamanlı yük izleme ve otomatik ters çalışma fonksiyonu ile operatör müdahalesini minimize eder. Takviyeli besleme haznesi ve özel alaşımlı bıçaklar uzun ömürlü kullanım garantisi verir. 800 mm rotor boyu ve 28-32 adet premium kalite bıçak ile homojen parçalama sağlar. Otomatik yağlama sistemi bakım maliyetlerini azaltır. Toz bastırma sistemi ile çevre dostu çalışma imkanı sunar.',
            paragraph3: 'MT Makina TW-150, büyük orman işletmeleri, endüstriyel ahşap geri dönüşüm tesisleri, belediye katı atık yönetim merkezleri ve biyoenerji üretim tesisleri için ideal çözümdür. Opsiyonel mobil paletli tasarım ile farklı lokasyonlarda kullanılabilir. Rotor soğutma sistemi, farklı ölçülerde elek ve besleme konveyörü seçenekleri ile tam otomatik hat kurulabilir. Parçalanan materyaller pellet yakıt, OSB-MDF üretimi ve enerji eldesi için kullanılabilir. CE ve ISO 9001 sertifikaları ile desteklenir.'
        },
        en: {
            intro: 'TW-150 tree root shredder is a professional system offering high performance for large-scale tree root and heavy woody material processing.',
            paragraph1: 'TW-150 model has Ø 1500 mm wide shredding area and 800 mm rotor length with 160-220 kW powerful motor. Reinforced multi-blade rotor and double-row feeding teeth system show superior performance in shredding thick tree roots, large diameter trunks, industrial pallet waste, heavy MDF-plywood remnants and hardwood species. Can shred large amounts of material per hour with high-capacity processing. Hydraulically assisted feeding system facilitates loading of heavy materials.',
            paragraph2: 'Advanced PLC automation system minimizes operator intervention with real-time load monitoring and automatic reverse function. Reinforced feeding hopper and special alloy blades guarantee long-lasting use. 800 mm rotor length and 28-32 premium quality blades provide homogeneous shredding. Automatic lubrication system reduces maintenance costs. Offers environmentally friendly operation with dust suppression system.',
            paragraph3: 'MT Makina TW-150 is the ideal solution for large forest operations, industrial wood recycling facilities, municipal solid waste management centers and bioenergy production facilities. Can be used in different locations with optional mobile tracked design. Full automatic line can be established with rotor cooling system, screens in different sizes and feeding conveyor options. Shredded materials can be used for pellet fuel, OSB-MDF production and energy generation. Supported by CE and ISO 9001 certificates.'
        },
        ru: {
            intro: 'TW-150 измельчитель корней деревьев - это профессиональная система, обеспечивающая высокую производительность для крупномасштабной обработки корней деревьев и тяжелых древесных материалов.',
            paragraph1: 'Модель TW-150 имеет широкую зону измельчения Ø 1500 мм и длину ротора 800 мм с мощным двигателем 160-220 кВт. Усиленный многолопастный ротор и система подающих зубьев с двойным рядом показывают превосходную производительность при измельчении толстых корней деревьев, стволов большого диаметра, промышленных отходов поддонов, тяжелых остатков МДФ-фанеры и твердых пород древесины. Может измельчать большое количество материала в час при высокопроизводительной обработке. Гидравлическая система подачи облегчает загрузку тяжелых материалов.',
            paragraph2: 'Усовершенствованная система автоматизации ПЛК минимизирует вмешательство оператора с мониторингом нагрузки в реальном времени и автоматической функцией реверса. Усиленный загрузочный бункер и ножи из специального сплава гарантируют долговечное использование. Длина ротора 800 мм и 28-32 ножа премиум-качества обеспечивают однородное измельчение. Система автоматической смазки снижает расходы на обслуживание. Предлагает экологически чистую работу с системой пылеподавления.',
            paragraph3: 'MT Makina TW-150 - идеальное решение для крупных лесных хозяйств, промышленных предприятий по переработке древесины, муниципальных центров управления твердыми отходами и предприятий по производству биоэнергии. Может использоваться в разных местах с опциональной мобильной гусеничной конструкцией. Полная автоматическая линия может быть установлена с системой охлаждения ротора, ситами разных размеров и опциями конвейера подачи. Измельченные материалы могут использоваться для производства пеллетного топлива, производства OSB-МДФ и выработки энергии. Поддерживается сертификатами CE и ISO 9001.'
        },
        ar: {
            intro: 'آلة تقطيع جذور الأشجار TW-150 هي نظام احترافي يوفر أداءً عاليًا لمعالجة جذور الأشجار والمواد الخشبية الثقيلة على نطاق واسع.',
            paragraph1: 'يتميز طراز TW-150 بمنطقة تقطيع واسعة Ø 1500 مم وطول دوار 800 مم مع محرك قوي 160-220 كيلووات. يُظهر الدوار متعدد الشفرات المعزز ونظام أسنان التغذية ذو الصف المزدوج أداءً متفوقًا في تقطيع جذور الأشجار السميكة وجذوع القطر الكبير ونفايات المنصات الصناعية وبقايا MDF-الخشب الرقائقي الثقيلة وأنواع الخشب الصلب. يمكن تقطيع كميات كبيرة من المواد في الساعة مع معالجة عالية السعة. يسهل نظام التغذية بالمساعدة الهيدروليكية تحميل المواد الثقيلة.',
            paragraph2: 'يقلل نظام الأتمتة المتقدم PLC من تدخل المشغل مع مراقبة الحمل في الوقت الفعلي ووظيفة الرجوع التلقائي. يضمن قادوس التغذية المعزز والشفرات من السبائك الخاصة استخدامًا طويل الأمد. يوفر طول الدوار 800 مم و28-32 شفرة عالية الجودة تقطيعًا متجانسًا. يقلل نظام التشحيم التلقائي من تكاليف الصيانة. يوفر تشغيلًا صديقًا للبيئة مع نظام قمع الغبار.',
            paragraph3: 'MT Makina TW-150 هو الحل الأمثل لعمليات الغابات الكبيرة ومرافق إعادة تدوير الخشب الصناعية ومراكز إدارة النفايات الصلبة البلدية ومرافق إنتاج الطاقة الحيوية. يمكن استخدامه في مواقع مختلفة مع تصميم مجنزر متنقل اختياري. يمكن إنشاء خط أوتوماتيكي كامل مع نظام تبريد الدوار والشاشات بأحجام مختلفة وخيارات الناقل المغذي. يمكن استخدام المواد المقطعة لوقود الحبيبات وإنتاج OSB-MDF وتوليد الطاقة. مدعوم بشهادات CE وISO 9001.'
        }
    },
    'TW-200': {
        tr: {
            intro: 'TW-200 ağaç kökü parçalama makinesi, endüstriyel ölçekte ultra yüksek kapasiteli ağaç kökü ve ağır odun işleme için maksimum güç sunan premium bir çözümdür.',
            paragraph1: 'TW-200 model, 220-315 kW ultra güçlü motor ile Ø 2000 mm ekstra geniş parçalama alanı ve 1000 mm uzun rotor boyuna sahiptir. Ağır hizmet tipi çok bıçaklı rotor sistemi ve hidrolik destekli çift besleme haznesi ile dev ağaç kökleri, kalın gövdeler (Ø 80+ cm), endüstriyel ahşap atık blokları, hurda ahşap yapılar, demiryolu traversleri ve en sert odun türlerinin parçalanmasında olağanüstü performans gösterir. Saatte 8-15 ton işleme kapasitesi ile büyük ölçekli projeler için idealdir. Çift hidrolik itici sistem ile sürekli besleme garantisi verir.',
            paragraph2: 'Siemens PLC tabanlı endüstri 4.0 otomasyon sistemi, SCADA entegrasyonu, uzaktan izleme ve bakım takip modülleri ile donatılmıştır. 1000 mm ultra uzun rotor, 36-40 adet ekstra kalın (30 mm) premium bıçak ve otomatik bıçak boşluk ayarı ile maksimum verimlilik sağlar. Çift otomatik yağlama sistemi, rotor soğutma ünitesi ve toz bastırma sistemi ile 7/24 kesintisiz çalışma kapasitesi. Gelişmiş sensör sistemi ile aşırı yüklenme, titreşim ve sıcaklık kontrolü yapılır.',
            paragraph3: 'MT Makina TW-200, mega orman yönetim projeleri, büyük biyoenerji santralleri, endüstriyel ahşap geri dönüşüm kompleksleri ve devlet kurumlarının ağır hizmet uygulamaları için turnkey çözümdür. Mobil paletli/tekerlekli tasarım seçeneği ile farklı sahalarda kullanılabilir. Tam otomatik hat entegrasyonu ile besleme konveyörü, manyetik seperatör, farklı elek sistemleri ve çıkış bandı entegre edilebilir. Parçalanan çıktılar biyokütle yakıt pelleti, endüstriyel enerji üretimi, OSB-MDF hammaddesi ve organik gübre üretimi için kullanılabilir. Tüm AB güvenlik standartları, CE, ISO 9001, ISO 14001 sertifikaları ve 3 yıl premium garanti ile güvence altındadır.'
        },
        en: {
            intro: 'TW-200 tree root shredder is a premium solution offering maximum power for industrial-scale ultra-high capacity tree root and heavy wood processing.',
            paragraph1: 'TW-200 model has Ø 2000 mm extra wide shredding area and 1000 mm long rotor length with 220-315 kW ultra-powerful motor. Heavy-duty multi-blade rotor system and hydraulically assisted dual feeding hopper show extraordinary performance in shredding giant tree roots, thick trunks (Ø 80+ cm), industrial wood waste blocks, scrap wood structures, railway sleepers and hardest wood species. Ideal for large-scale projects with 8-15 ton/hour processing capacity. Dual hydraulic pusher system guarantees continuous feeding.',
            paragraph2: 'Equipped with Siemens PLC-based Industry 4.0 automation system, SCADA integration, remote monitoring and maintenance tracking modules. 1000 mm ultra-long rotor, 36-40 extra-thick (30 mm) premium blades and automatic blade gap adjustment provide maximum efficiency. Dual automatic lubrication system, rotor cooling unit and dust suppression system enable 24/7 uninterrupted operation capacity. Advanced sensor system performs overload, vibration and temperature control.',
            paragraph3: 'MT Makina TW-200 is a turnkey solution for mega forest management projects, large bioenergy plants, industrial wood recycling complexes and heavy-duty applications of government institutions. Can be used in different sites with mobile tracked/wheeled design option. With full automatic line integration, feeding conveyor, magnetic separator, different screen systems and output belt can be integrated. Shredded outputs can be used for biomass fuel pellets, industrial energy production, OSB-MDF raw materials and organic fertilizer production. Secured by all EU safety standards, CE, ISO 9001, ISO 14001 certificates and 3-year premium warranty.'
        },
        ru: {
            intro: 'TW-200 измельчитель корней деревьев - это премиальное решение, обеспечивающее максимальную мощность для промышленной обработки корней деревьев и тяжелой древесины ультра-высокой производительности.',
            paragraph1: 'Модель TW-200 имеет сверхширокую зону измельчения Ø 2000 мм и длинный ротор 1000 мм с ультрамощным двигателем 220-315 кВт. Роторная система для тяжелых условий эксплуатации с несколькими лопастями и двойной загрузочный бункер с гидравлической поддержкой показывают выдающуюся производительность при измельчении гигантских корней деревьев, толстых стволов (Ø 80+ см), промышленных блоков древесных отходов, конструкций из лома древесины, железнодорожных шпал и самых твердых пород древесины. Идеально подходит для крупномасштабных проектов с производительностью 8-15 тонн/час. Двойная гидравлическая толкающая система гарантирует непрерывную подачу.',
            paragraph2: 'Оснащен системой автоматизации Индустрии 4.0 на базе Siemens PLC, интеграцией SCADA, удаленным мониторингом и модулями отслеживания обслуживания. Ультрадлинный ротор 1000 мм, 36-40 сверхтолстых (30 мм) ножей премиум-класса и автоматическая регулировка зазора ножей обеспечивают максимальную эффективность. Двойная система автоматической смазки, блок охлаждения ротора и система пылеподавления обеспечивают круглосуточную бесперебойную работу. Усовершенствованная сенсорная система выполняет контроль перегрузки, вибрации и температуры.',
            paragraph3: 'MT Makina TW-200 - это комплексное решение для мега проектов управления лесами, крупных биоэнергетических заводов, промышленных комплексов переработки древесины и тяжелых применений государственных учреждений. Может использоваться на разных площадках с опцией мобильной гусеничной/колесной конструкции. С полной автоматической интеграцией линии может быть интегрирован конвейер подачи, магнитный сепаратор, различные системы сит и выходная лента. Измельченные отходы могут использоваться для производства топливных пеллет из биомассы, промышленного производства энергии, сырья OSB-МДФ и производства органических удобрений. Обеспечено всеми стандартами безопасности ЕС, сертификатами CE, ISO 9001, ISO 14001 и 3-летней премиум-гарантией.'
        },
        ar: {
            intro: 'آلة تقطيع جذور الأشجار TW-200 هي حل متميز يوفر أقصى قدر من القوة لمعالجة جذور الأشجار والخشب الثقيل عالي السعة على النطاق الصناعي.',
            paragraph1: 'يتميز طراز TW-200 بمنطقة تقطيع واسعة للغاية Ø 2000 مم وطول دوار طويل 1000 مم مع محرك فائق القوة 220-315 كيلووات. يُظهر نظام الدوار متعدد الشفرات للخدمة الشاقة وقادوس التغذية المزدوج بمساعدة هيدروليكية أداءً استثنائيًا في تقطيع جذور الأشجار العملاقة وجذوع سميكة (Ø 80+ سم) وكتل نفايات الخشب الصناعية وهياكل خشب الخردة وعوارض السكك الحديدية وأصلب أنواع الخشب. مثالي للمشاريع واسعة النطاق بسعة معالجة 8-15 طن/ساعة. يضمن نظام الدفع الهيدروليكي المزدوج التغذية المستمرة.',
            paragraph2: 'مجهز بنظام أتمتة الصناعة 4.0 القائم على Siemens PLC وتكامل SCADA ومراقبة عن بعد ووحدات تتبع الصيانة. يوفر الدوار فائق الطول 1000 مم و36-40 شفرة فائقة السُمك (30 مم) ممتازة الجودة وضبط فجوة الشفرة التلقائي أقصى قدر من الكفاءة. يتيح نظام التشحيم التلقائي المزدوج ووحدة تبريد الدوار ونظام قمع الغبار قدرة تشغيل مستمر على مدار الساعة طوال أيام الأسبوع. يؤدي نظام الاستشعار المتقدم تحكم الحمل الزائد والاهتزاز ودرجة الحرارة.',
            paragraph3: 'MT Makina TW-200 هو حل تسليم مفتاح لمشاريع إدارة الغابات الضخمة ومحطات الطاقة الحيوية الكبيرة ومجمعات إعادة تدوير الخشب الصناعية والتطبيقات الثقيلة للمؤسسات الحكومية. يمكن استخدامه في مواقع مختلفة مع خيار التصميم المتنقل المجنزر/بالعجلات. مع تكامل خط أوتوماتيكي كامل، يمكن دمج ناقل التغذية والفاصل المغناطيسي وأنظمة الشاشة المختلفة وحزام الإخراج. يمكن استخدام المخرجات المقطعة لحبيبات وقود الكتلة الحيوية وإنتاج الطاقة الصناعية والمواد الخام OSB-MDF وإنتاج الأسمدة العضوية. مضمون بجميع معايير السلامة الأوروبية وشهادات CE وISO 9001 وISO 14001 وضمان متميز لمدة 3 سنوات.'
        }
    }
};
