import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  tr: {
    // Header & Navigation
    nav_home: 'Ana Sayfa',
    nav_corporate: 'Kurumsal',
    nav_products: 'Ürünler',
    nav_wastes: 'Atıklar',
    nav_technology: 'Teknoloji',
    nav_references: 'Referanslar',
    nav_contact: 'İletişim',
    nav_ecatalog: 'E-Katalog',
    models: 'Modeller',
    btn_quote: 'Hemen Teklif Al!',
    btn_view_details: 'Detaylı İncele',
    btn_contact_us: 'Bize Ulaşın',
    
    // Page Titles
    page_title_home: 'PARÇALAMA MAKİNELERİ',
    page_title_shredders: 'MT Makina Parçalama Makineleri',
    page_title_location: 'Konumumuz',
    page_title_headquarters: 'Genel Merkez',
    page_title_contact_info: 'İletişim Bilgileri',
    page_title_working_hours: 'Çalışma Saatleri',
    
    // Descriptions
    desc_location: 'Esenyurt / İstanbul\'daki merkez ofisimizde sizleri bekliyoruz.',
    desc_map_label: 'MT MAKİNA GENEL MERKEZ',
    
    // Corporate Dropdown
    nav_about: 'Hakkımızda',
    nav_certificates: 'Belgelerimiz',
    nav_fair: 'Fuar',
    nav_refs: 'Referanslar',
    
    // Wastes Dropdown
    waste_household: 'Evsel Atıklar',
    waste_electronic: 'Elektronik Atıklar',
    waste_tire: 'Lastik Atıkları',
    waste_metal: 'Metal Atıklar',
    waste_glass: 'Cam Atıklar',
    waste_paper: 'Kağıt Karton Atıklar',
    waste_plastic: 'Plastik Atıklar',
    waste_organic: 'Organik Atıklar',
    waste_medical: 'Tıbbi Atıklar',
    waste_tree_root: 'Ağaç Kökü Atıkları',
    waste_animal: 'Hayvan Atıkları',
    waste_packaging: 'Ambalaj Atıkları',
    waste_pallet: 'Palet Atıkları',
    waste_textile: 'Tekstil Atıkları',
    waste_aty: 'ATY Atıkları',
    
    // Hero
    hero_title: 'Parçalama Makinelerinde Endüstriyel Güç',
    hero_subtitle: 'Yüksek verimlilik, uzun ömür ve güvenli çalışma ile çevre dostu üretim.',
    btn_explore: 'Ürünleri İncele',
    
    // Intro Section
    intro_title: 'Çevre Dostu Üretim ve Sürdürülebilir Geri Dönüşüm',
    intro_description: 'Endüstriyel atık yönetimi ve geri dönüşüm süreçlerinde yüksek verimlilik sunan MT MAKİNA parçalama makineleri, dayanıklı yapısı ve güçlü bıçak sistemleriyle farklı malzemelerin etkili şekilde parçalanmasını sağlar. Lastik, metal, plastik, ahşap, tekstil, evsel ve endüstriyel atıklar gibi birçok malzemeye uygun olarak üretilen sistemler, sürdürülebilir geri dönüşüm çözümleri sunarak atık miktarını azaltmaya ve kaynakların verimli kullanılmasına katkı sağlar. Özel ihtiyaçlara yönelik tasarlanan modellerle, yüksek performans ve uzun ömürlü kullanım sunan MT MAKİNA parçalama makineleri hakkında detaylı bilgi için iletişime geçebilirsiniz.',
    eco_friendly: 'Çevre Dostu',
    recycling: 'Geri Dönüşüm',
    durability: 'Dayanıklılık',
    performance: 'Performans',
    
    // Products
    products_title: 'Ürün Kategorileri',
    products_description: 'MT Makina\'nın yüksek performanslı parçalama makineleri, güçlü gövde yapısı ve verimli bıçak sistemleriyle endüstriyel geri dönüşüm süreçlerinde fark yaratır.',
    products_subtitle: 'MT Makina\'nın güçlü ve verimli parçalama makineleri: Tek, Çift, Dört Şaftlı, Metal, Palet, Plastik, Cam, Organik, Tıbbi ve daha fazlası.',
    btn_details: 'Detaylı İncele',
    
    // Technology
    tech_title: 'Teknoloji ve Mühendislik',
    tech_subtitle: 'Hidrolik sistemler, kesici bıçak geometrisi, otomasyon ve enerji verimliliği odaklı mühendislik çözümleri.',
    tech_hydraulic: 'Hidrolik Sistemler',
    tech_hydraulic_desc: 'Yüksek basınçlı hidrolik güç ile maksimum verimlilik',
    tech_blade: 'Kesici Bıçak Teknolojisi',
    tech_blade_desc: 'Özel geometri ve dayanıklı malzemelerle uzun ömürlü kesim',
    tech_automation: 'Otomasyon Çözümleri',
    tech_automation_desc: 'PLC kontrollü akıllı işletme ve izleme sistemleri',
    tech_energy: 'Enerji Verimliliği',
    tech_energy_desc: 'Düşük enerji tüketimi ile yüksek performans',
    
    // References
    ref_title: 'Referanslarımız',
    ref_subtitle: 'Dünyanın dört bir yanındaki partnerlerimize endüstriyel çözümler sunuyoruz.',
    ref_main_title: 'Müşteri Memnuniyeti ve Başarı Öyküleri',
    ref_main_subtitle: 'MT Makina olarak müşteri memnuniyetini her zaman ön planda tutuyoruz. İş ortaklarımızın geri bildirimleri, ürünlerimizin ve hizmetlerimizin kalitesini artırmamıza yardımcı olmaktadır. Başarıyla tamamladığımız projeler, en büyük referanslarımızdır.',
    ref_main_paragraph: 'Geri dönüşüm ve atık yönetimi çözümlerinde güvenilir bir iş ortağı olarak sürdürülebilir bir gelecek için çalışmaya devam ediyoruz. MT Makina ile iş birliği yaparak hem çevresel sürdürülebilirliğe katkıda bulunabilir hem de atık yönetimi süreçlerinizi daha verimli hale getirebilirsiniz.',
    ref_global_title: 'Global Export Network',
    ref_global_subtitle: 'Serving customers across Europe, Middle East and Asia.',
    
    // Contact
    contact_title: 'İletişim',
    contact_headquarters: 'Genel Merkez',
    contact_hq_address: 'Cumhuriyet Mahallesi, Nazım Hikmet Bulvarı, 1983 Sk. Kent Palas 2 Kat:7, D:85-86, PK:34512 Esenyurt / İSTANBUL',
    contact_sales: 'Satış',
    contact_export: 'Dış Ticaret',
    contact_whatsapp: 'Whatsapp',
    contact_saudi_rep: 'Arabistan Temsilcisi',
    contact_accounting: 'Muhasebe',
    contact_consulting: 'Danışma',
    
    // CTA
    cta_title: 'Makinenizi Bizimle Planlayın',
    cta_subtitle: 'Projenize uygun parçalama sistemini birlikte tasarlayalım.',
    
    // Footer
    footer_contact: 'İletişim',
    footer_address: 'Adres: İstanbul, Türkiye',
    footer_phone: 'Tel: +90 XXX XXX XX XX',
    footer_email: 'E-posta: info@mtmakina.com.tr',
    footer_quick_links: 'Hızlı Bağlantılar',
    footer_social: 'Sosyal Medya',
    footer_copyright: '© 2025 MT Makina Ltd. Şti. - Tüm Hakları Saklıdır',
    footer_full_address: 'Cumhuriyet Mah. 1983 Sk. Kent Palas 2 K:7 D:85-86 PK:34512 Esenyurt / İstanbul / TÜRKİYE',
    footer_full_phone: '+90 212 613 31 82',
    footer_full_email: 'info@mtmakina.com.tr',
    footer_website: 'www.mtmakina.com.tr',
    
    // Products
    product_single_shaft: 'Tek Şaftlı Parçalama Makinesi',
    product_dual_shaft: 'Çift Şaftlı Parçalama Makinesi',
    product_quad_shaft: 'Dört Şaftlı Parçalama Makinesi',
    product_metal: 'Metal Parçalama Makinesi',
    product_pallet: 'Palet Parçalama Makinesi',
    product_glass: 'Cam Şişe Kırma Makinesi',
    product_plastic: 'Plastik Parçalama Makinesi',
    product_organic: 'Organik Atık Parçalama Makinesi',
    product_tire: 'Lastik Parçalama Makinesi',
    
    // Single Shaft Product Detail Page
    single_shaft_main_title: 'Tek Şaftlı Katı Atık Parçalama Makinesi',
    single_shaft_subtitle: 'Geniş Atık Yelpazesinde Yüksek Verim, Güçlü Performans',
    single_shaft_description_1: 'Tek şaftlı katı atık parçalama makinesi; evsel, endüstriyel, plastik, kâğıt, tekstil, alüminyum ve ambalaj atıklarının etkili şekilde parçalanmasını sağlar. MT Makina mühendisliğiyle geliştirilen bu sistemler, yüksek torklu şaft tasarımı ve enerji verimli hidrolik sistemiyle uzun ömürlü kullanım sunar.',
    single_shaft_description_2: 'PLC kontrollü otomasyon sistemi sayesinde, aşırı yüklenme durumlarında otomatik ters çalışma fonksiyonu devreye girer. Bu özellik hem kesici bıçakların ömrünü uzatır hem de bakım ihtiyacını minimuma indirir.',
    single_shaft_description_3: 'MT Makina\'nın tek şaftlı kırıcıları, yüksek dayanım gerektiren sanayi uygulamaları için optimize edilmiştir. 800 – 1500 mm rotor uzunluğu, değiştirilebilir bıçak modülleri ve otomatik besleme kontrol sistemi ile maksimum verimlilik elde edilir.',
    single_shaft_advantages_title: 'Tek Şaftlı Katı Atık Parçalama Makinesi Avantajları',
    single_shaft_adv_1_title: 'Yüksek Torklu Şaft Sistemi',
    single_shaft_adv_1_desc: 'Ağır hizmet tipi malzemelerde bile güçlü ve kararlı performans.',
    single_shaft_adv_2_title: 'Otomatik Ters Çalışma',
    single_shaft_adv_2_desc: 'Tıkanmaları önleyen akıllı sistem, uzun ömürlü bıçaklar.',
    single_shaft_adv_3_title: 'Düşük Gürültü ve Enerji Tüketimi',
    single_shaft_adv_3_desc: 'Verimlilik odaklı mühendislik tasarımı.',
    single_shaft_performance_title: 'Tek Şaftlı Parçalama Makinelerinde Maksimum Performans ve Verimlilik',
    single_shaft_perf_1: 'Metal ve Plastik Geri Dönüşümü Uygulamaları',
    single_shaft_perf_2: 'Dayanıklı Rotor Tasarımı',
    single_shaft_perf_3: 'Yüksek Kapasiteli Şarj Sistemi',
    single_shaft_tech_specs_title: 'Teknik Özellikler',
    single_shaft_tech_model: 'Model',
    single_shaft_tech_model_value: 'TSH-800 / TSH-1000 / TSH-1500',
    single_shaft_tech_motor: 'Motor Gücü',
    single_shaft_tech_motor_value: '37 – 90 kW',
    single_shaft_tech_rotor_length: 'Rotor Uzunluğu',
    single_shaft_tech_rotor_length_value: '800 – 1500 mm',
    single_shaft_tech_rotor_diameter: 'Rotor Çapı',
    single_shaft_tech_rotor_diameter_value: '400 – 600 mm',
    single_shaft_tech_blade_count: 'Bıçak Sayısı',
    single_shaft_tech_blade_count_value: '30 – 60 adet',
    single_shaft_tech_weight: 'Ağırlık',
    single_shaft_tech_weight_value: '2.5 – 6 ton',
    single_shaft_tech_feed_opening: 'Besleme Ağzı',
    single_shaft_tech_feed_opening_value: '800 x 1000 mm',
    single_shaft_tech_control: 'Kontrol Sistemi',
    single_shaft_tech_control_value: 'PLC – Otomatik Ters Çalışma',
    single_shaft_tech_capacity: 'Kapasite',
    single_shaft_tech_capacity_value: '800 – 3000 kg/sa',
    single_shaft_faq_title: 'Tek Şaftlı Parçalama Makinesi S.S.S.',
    single_shaft_faq_q1: 'Tek Şaftlı Parçalama Makinesi hangi atıkları işler?',
    single_shaft_faq_a1: 'Tek şaftlı parçalama makineleri evsel atıklar, plastik, kâğıt, karton, tekstil, alüminyum ambalaj, ahşap palet ve organik atıklar gibi geniş bir yelpazede kullanılabilir.',
    single_shaft_faq_q2: 'Otomatik ters çalışma sistemi nasıl çalışır?',
    single_shaft_faq_a2: 'PLC kontrol sistemi sayesinde, makine aşırı yüklenme veya tıkanma algıladığında rotoru otomatik olarak ters yönde çalıştırarak malzemenin düzgün parçalanmasını sağlar ve bıçak ömrünü uzatır.',
    single_shaft_faq_q3: 'Bakım gereksinimleri nelerdir?',
    single_shaft_faq_a3: 'Düzenli bıçak kontrolü, hidrolik sistem kontrolü ve yağlama işlemleri önerilir. Ortalama 500 çalışma saatinde bir genel kontrol yapılması yeterlidir.',
    single_shaft_faq_q4: 'Rotor ve bıçak ömrü ne kadardır?',
    single_shaft_faq_a4: 'Bıçaklar dayanıklı alaşım çelikten üretilir ve işlenen malzeme tipine göre 2000-5000 saat arası kullanım ömrü sunar. Rotor ömrü ise 10 yılın üzerindedir.',
    single_shaft_faq_q5: 'Makine kapasitesi neye göre değişir?',
    single_shaft_faq_a5: 'Kapasite; işlenen malzemenin cinsi, nem oranı, yoğunluğu ve parçalama boyutuna göre değişkenlik gösterir. Plastik ve kâğıt gibi hafif malzemeler daha yüksek kapasitede işlenebilir.',
    single_shaft_video_title: 'Tek Şaftlı Parçalama Makinesi Video',
    single_shaft_watch_video: 'Videoyu İzle',
    single_shaft_similar_products: 'Benzer Ürünler',
    single_shaft_ecatalog_btn: 'E-Katalog',
    youtube_channel_title: 'YouTube Kanalımızı İnceleyin',
    youtube_channel_description: 'Tüm makinelerimizin çalışma videolarını, müşteri referanslarını ve üretim süreçlerimizi YouTube kanalımızda bulabilirsiniz.',
    visit_youtube: 'YouTube Kanalına Git',
    
    // Product Category Page
    about_our_machines: 'Makinelerimiz Hakkında',
    key_features: 'Temel Özellikler',
    our_models: 'Modellerimiz',
    select_model_description: 'İhtiyacınıza uygun modeli seçin ve detaylı teknik özellikleri inceleyin',
    need_help_choosing: 'Model Seçiminde Yardıma mı İhtiyacınız Var?',
    contact_us_for_consultation: 'Uzman ekibimiz size en uygun makineyi seçmenizde yardımcı olacaktır',
    contact_us: 'Bize Ulaşın',
    single_shaft_advantage_1_title: 'Esnek Kullanım',
    single_shaft_advantage_1_desc: 'Farklı atık türleri için optimize edilmiş parçalama',
    single_shaft_advantage_2_title: 'Yüksek Verimlilik',
    single_shaft_advantage_2_desc: 'Enerji tasarruflu motor ve güçlü performans',
    single_shaft_advantage_3_title: 'Güvenli Çalışma',
    single_shaft_advantage_3_desc: 'Otomatik koruma sistemleri ve acil durdurma',
    single_shaft_advantage_4_title: 'Kolay Bakım',
    single_shaft_advantage_4_desc: 'Hızlı bıçak değişimi ve basit servis erişimi',
    
    // Dual Shaft Product Detail Page
    dual_shaft_main_title: 'Çift Şaftlı Parçalama Makinesi',
    dual_shaft_subtitle: 'Zorlu Endüstriyel Atıklar İçin Güçlü Parçalama Performansı',
    dual_shaft_description_1: 'Çift Şaftlı Parçalama Makinesi, yüksek dayanımlı metal, plastik, ahşap, kauçuk, evsel ve endüstriyel atıkların düşük devir – yüksek tork prensibiyle güvenli biçimde parçalanmasını sağlar.',
    dual_shaft_description_2: 'MT Makina mühendisliğiyle geliştirilen bu sistem, senkronize çalışan iki güçlü şaft üzerinden yüksek kesme kuvveti üretir.',
    dual_shaft_description_3: 'Makine, ağır hizmet tipi gövde yapısı, özel alaşımlı kesici bıçakları ve otomatik ters dönüş özelliği ile uzun ömürlü kullanım sunar.',
    dual_shaft_description_4: 'Çift şaftlı yapı sayesinde malzeme sıkışmaları önlenir ve kesme işlemi daha dengeli gerçekleşir.',
    dual_shaft_description_5: 'Ayrıca PLC kontrollü sistem, operatör müdahalesi olmadan yük değişimlerine adapte olur. Bu sayede sistem arızaları en aza iner ve sürekli verimli çalışma sağlanır.',
    dual_shaft_advantages_title: 'Çift Şaftlı Parçalama Makinelerinin Avantajları',
    dual_shaft_adv_1_title: 'Yüksek Kesme Kuvveti',
    dual_shaft_adv_1_desc: 'Çift şaftlı yapı sayesinde kalın ve sert atıklarda maksimum tork.',
    dual_shaft_adv_2_title: 'Ters Dönüş Özelliği',
    dual_shaft_adv_2_desc: 'Tıkanmalara karşı otomatik olarak tersine döner.',
    dual_shaft_adv_3_title: 'Düşük Gürültü Seviyesi',
    dual_shaft_adv_3_desc: 'Enerji verimliliği sağlayan düşük devirli sistem.',
    dual_shaft_adv_4_title: 'Modüler Bıçak Sistemi',
    dual_shaft_adv_4_desc: 'Değiştirilebilir bıçaklar kolay bakım ve uzun ömür sağlar.',
    dual_shaft_performance_title: 'Çift Şaftlı Parçalama Makinelerinde Maksimum Verim ve Güvenilirlik',
    dual_shaft_perf_1: 'Senkronize Çalışan İki Güçlü Şaft',
    dual_shaft_perf_2: 'Metal ve Plastik Atıklar İçin Yüksek Performanslı Sistem',
    dual_shaft_perf_3: 'Enerji Verimli Hidrolik Güç Ünitesi',
    dual_shaft_tech_specs_title: 'CS Serisi Teknik Özellikler',
    dual_shaft_tech_motor: 'Motor Gücü',
    dual_shaft_tech_rotor_speed: 'Kesici Mil Hızı',
    dual_shaft_tech_blade_count: 'Bıçak Sayısı',
    dual_shaft_tech_rotor_length: 'Rotor Uzunluğu',
    dual_shaft_tech_blade_thickness: 'Bıçak Kalınlığı',
    dual_shaft_tech_capacity: 'Üretim Kapasitesi',
    dual_shaft_tech_weight: 'Ağırlık',
    dual_shaft_faq_title: 'Çift Şaftlı Parçalama Makineleri Hakkında S.S.S.',
    dual_shaft_faq_q1: 'Çift Şaftlı Parçalama Makinesi hangi malzemeleri işler?',
    dual_shaft_faq_a1: 'Çift şaftlı parçalama makineleri metal, plastik, ahşap, kauçuk, lastik, elektronik atık, tekstil, evsel atık ve endüstriyel katı atıklar gibi zorlu malzemeleri işler.',
    dual_shaft_faq_q2: 'Ters dönüş sistemi ne işe yarar?',
    dual_shaft_faq_a2: 'Otomatik ters dönüş sistemi, makine içinde malzeme sıkışması veya aşırı yüklenme olduğunda şaftları tersine çevirerek tıkanmayı giderir ve bıçakların zarar görmesini önler.',
    dual_shaft_faq_q3: 'CS serisi modeller arasında fark nedir?',
    dual_shaft_faq_a3: 'CS serisi modeller rotor uzunluğu, motor gücü ve kapasite açısından farklılık gösterir. CS-60 küçük işletmeler için idealken, CS-200 büyük sanayi tesisleri için tasarlanmıştır.',
    dual_shaft_faq_q4: 'Bakım ve bıçak değişimi ne kadar sürer?',
    dual_shaft_faq_a4: 'Modüler bıçak sistemi sayesinde bıçak değişimi yaklaşık 2-3 saat içinde tamamlanabilir. Düzenli bakım periyodu 1000 çalışma saatinde bir önerilir.',
    dual_shaft_faq_q5: 'Makine kapasitesi hangi faktörlere bağlıdır?',
    dual_shaft_faq_a5: 'Kapasite, işlenen malzemenin türü, boyutu, nem oranı ve istenen çıkış boyutuna göre değişir. Sert malzemeler daha düşük, yumuşak malzemeler daha yüksek kapasitede işlenir.',
    dual_shaft_video_title: 'Çift Şaftlı Parçalama Makinesi Video',
    dual_shaft_watch_video: 'Videoyu İzle',
    dual_shaft_similar_products: 'Benzer Ürünler',
    dual_shaft_ecatalog_btn: 'E-Katalog',
  },
  en: {
    // Header & Navigation
    nav_home: 'Home',
    nav_corporate: 'Corporate',
    nav_products: 'Products',
    nav_wastes: 'Waste Types',
    nav_technology: 'Technology',
    models: 'Models',
    nav_references: 'References',
    nav_contact: 'Contact',
    nav_ecatalog: 'E-Catalog',
    btn_quote: 'Get a Quote Now!',
    btn_view_details: 'View Details',
    btn_contact_us: 'Contact Us',
    
    // Page Titles
    page_title_home: 'SHREDDING MACHINES',
    page_title_shredders: 'MT Makina Shredding Machines',
    page_title_location: 'Our Location',
    page_title_headquarters: 'Head Office',
    page_title_contact_info: 'Contact Information',
    page_title_working_hours: 'Working Hours',
    
    // Descriptions
    desc_location: 'We welcome you at our headquarters in Esenyurt / Istanbul.',
    desc_map_label: 'MT MAKINA HEAD OFFICE',
    
    // Corporate Dropdown
    nav_about: 'About Us',
    nav_certificates: 'Our Certificates',
    nav_fair: 'Fair',
    nav_refs: 'References',
    
    // Wastes Dropdown
    waste_household: 'Household Waste',
    waste_electronic: 'Electronic Waste',
    waste_tire: 'Tire Waste',
    waste_metal: 'Metal Waste',
    waste_glass: 'Glass Waste',
    waste_paper: 'Paper Cardboard Waste',
    waste_plastic: 'Plastic Waste',
    waste_organic: 'Organic Waste',
    waste_medical: 'Medical Waste',
    waste_tree_root: 'Tree Root Waste',
    waste_animal: 'Animal Waste',
    waste_packaging: 'Packaging Waste',
    waste_pallet: 'Pallet Waste',
    waste_textile: 'Textile Waste',
    waste_aty: 'ATY Waste',
    
    // Hero
    hero_title: 'Industrial Power in Shredding Machines',
    hero_subtitle: 'High efficiency, long life and safe operation with environmentally friendly production.',
    btn_explore: 'Explore Products',
    
    // Intro Section
    intro_title: 'Environmentally Friendly Production and Sustainable Recycling',
    intro_description: 'MT MAKINA shredding machines, offering high efficiency in industrial waste management and recycling processes, ensure effective shredding of various materials with their durable structure and powerful blade systems. The systems produced for many materials such as tire, metal, plastic, wood, textile, household and industrial waste, contribute to reducing waste volume and efficient use of resources by providing sustainable recycling solutions. For detailed information about MT MAKINA shredding machines that offer high performance and long-lasting use with models designed for special needs, please contact us.',
    eco_friendly: 'Eco-Friendly',
    recycling: 'Recycling',
    durability: 'Durability',
    performance: 'Performance',
    
    // Products
    products_title: 'Product Categories',
    products_description: 'MT Makina\'s high-performance shredding machines make a difference in industrial recycling processes with their robust body structure and efficient blade systems.',
    products_subtitle: 'MT Makina\'s powerful and efficient shredding machines: Single, Double, Quad Shaft, Metal, Pallet, Plastic, Glass, Organic, Medical and more.',
    btn_details: 'View Details',
    
    // Technology
    tech_title: 'Technology and Engineering',
    tech_subtitle: 'Engineering solutions focused on hydraulic systems, cutting blade geometry, automation and energy efficiency.',
    tech_hydraulic: 'Hydraulic Systems',
    tech_hydraulic_desc: 'Maximum efficiency with high-pressure hydraulic power',
    tech_blade: 'Cutting Blade Technology',
    tech_blade_desc: 'Long-lasting cutting with special geometry and durable materials',
    tech_automation: 'Automation Solutions',
    tech_automation_desc: 'PLC-controlled intelligent operation and monitoring systems',
    tech_energy: 'Energy Efficiency',
    tech_energy_desc: 'High performance with low energy consumption',
    
    // References
    ref_title: 'Our References',
    ref_subtitle: 'We provide industrial solutions to our partners around the world.',
    ref_main_title: 'Customer Satisfaction and Success Stories',
    ref_main_subtitle: 'At MT Makina, we always prioritize customer satisfaction. Feedback from our business partners helps us improve the quality of our products and services. Our successfully completed projects are our greatest references.',
    ref_main_paragraph: 'As a reliable business partner in recycling and waste management solutions, we continue to work towards a sustainable future. By collaborating with MT Makina, you can both contribute to environmental sustainability and make your waste management processes more efficient.',
    ref_global_title: 'Global Export Network',
    ref_global_subtitle: 'Serving customers across Europe, Middle East and Asia.',
    
    // Contact
    contact_title: 'Contact',
    contact_headquarters: 'Headquarters',
    contact_hq_address: 'Cumhuriyet Mahallesi, Nazım Hikmet Bulvarı, 1983 Sk. Kent Palas 2 Floor:7, D:85-86, PK:34512 Esenyurt / ISTANBUL',
    contact_sales: 'Sales',
    contact_export: 'Export',
    contact_whatsapp: 'Whatsapp',
    contact_saudi_rep: 'Saudi Representative',
    contact_accounting: 'Accounting',
    contact_consulting: 'Consulting',
    
    // CTA
    cta_title: 'Plan Your Machine With Us',
    cta_subtitle: 'Let\'s design the shredding system suitable for your project together.',
    
    // Footer
    footer_contact: 'Contact',
    footer_address: 'Address: Istanbul, Turkey',
    footer_phone: 'Phone: +90 XXX XXX XX XX',
    footer_email: 'Email: info@mtmakina.com.tr',
    footer_quick_links: 'Quick Links',
    footer_social: 'Social Media',
    footer_copyright: '© 2025 MT Makina Ltd. - All Rights Reserved',
    footer_full_address: 'Cumhuriyet Mah. 1983 Sk. Kent Palas 2 Floor:7 D:85-86 PK:34512 Esenyurt / Istanbul / TURKEY',
    footer_full_phone: '+90 212 613 31 82',
    footer_full_email: 'info@mtmakina.com.tr',
    footer_website: 'www.mtmakina.com.tr',
    
    // Products
    product_single_shaft: 'Single Shaft Shredder',
    product_dual_shaft: 'Dual Shaft Shredder',
    product_quad_shaft: 'Quad Shaft Shredder',
    product_metal: 'Metal Shredder',
    product_pallet: 'Pallet Shredder',
    product_glass: 'Glass Bottle Crusher',
    product_plastic: 'Plastic Shredder',
    product_organic: 'Organic Waste Shredder',
    product_tire: 'Tire Shredder',
    
    // Single Shaft Product Detail Page
    single_shaft_main_title: 'Single Shaft Solid Waste Shredder',
    single_shaft_subtitle: 'High Efficiency and Powerful Performance Across Wide Range of Waste',
    single_shaft_description_1: 'The single shaft solid waste shredder effectively shreds household, industrial, plastic, paper, textile, aluminum and packaging waste. Developed with MT Makina engineering, these systems offer long-lasting use with high-torque shaft design and energy-efficient hydraulic system.',
    single_shaft_description_2: 'Thanks to the PLC-controlled automation system, the automatic reverse function is activated in case of overload. This feature both extends the life of the cutting blades and minimizes maintenance needs.',
    single_shaft_description_3: 'MT Makina\'s single shaft crushers are optimized for industrial applications requiring high durability. Maximum efficiency is achieved with 800 – 1500 mm rotor length, replaceable blade modules and automatic feed control system.',
    single_shaft_advantages_title: 'Single Shaft Solid Waste Shredder Advantages',
    single_shaft_adv_1_title: 'High Torque Shaft System',
    single_shaft_adv_1_desc: 'Powerful and stable performance even in heavy-duty materials.',
    single_shaft_adv_2_title: 'Automatic Reverse Operation',
    single_shaft_adv_2_desc: 'Intelligent system preventing jams, long-lasting blades.',
    single_shaft_adv_3_title: 'Low Noise and Energy Consumption',
    single_shaft_adv_3_desc: 'Efficiency-focused engineering design.',
    single_shaft_performance_title: 'Maximum Performance and Efficiency in Single Shaft Shredders',
    single_shaft_perf_1: 'Metal and Plastic Recycling Applications',
    single_shaft_perf_2: 'Durable Rotor Design',
    single_shaft_perf_3: 'High Capacity Feeding System',
    single_shaft_tech_specs_title: 'Technical Specifications',
    single_shaft_tech_model: 'Model',
    single_shaft_tech_model_value: 'TSH-800 / TSH-1000 / TSH-1500',
    single_shaft_tech_motor: 'Motor Power',
    single_shaft_tech_motor_value: '37 – 90 kW',
    single_shaft_tech_rotor_length: 'Rotor Length',
    single_shaft_tech_rotor_length_value: '800 – 1500 mm',
    single_shaft_tech_rotor_diameter: 'Rotor Diameter',
    single_shaft_tech_rotor_diameter_value: '400 – 600 mm',
    single_shaft_tech_blade_count: 'Blade Count',
    single_shaft_tech_blade_count_value: '30 – 60 pcs',
    single_shaft_tech_weight: 'Weight',
    single_shaft_tech_weight_value: '2.5 – 6 tons',
    single_shaft_tech_feed_opening: 'Feed Opening',
    single_shaft_tech_feed_opening_value: '800 x 1000 mm',
    single_shaft_tech_control: 'Control System',
    single_shaft_tech_control_value: 'PLC – Automatic Reverse',
    single_shaft_tech_capacity: 'Capacity',
    single_shaft_tech_capacity_value: '800 – 3000 kg/h',
    single_shaft_faq_title: 'Single Shaft Shredder F.A.Q.',
    single_shaft_faq_q1: 'What waste does the Single Shaft Shredder process?',
    single_shaft_faq_a1: 'Single shaft shredders can be used for a wide range including household waste, plastic, paper, cardboard, textiles, aluminum packaging, wooden pallets and organic waste.',
    single_shaft_faq_q2: 'How does the automatic reverse system work?',
    single_shaft_faq_a2: 'Thanks to the PLC control system, when the machine detects overload or jamming, it automatically runs the rotor in reverse to ensure proper shredding and extend blade life.',
    single_shaft_faq_q3: 'What are the maintenance requirements?',
    single_shaft_faq_a3: 'Regular blade inspection, hydraulic system check and lubrication are recommended. A general inspection every 500 operating hours is sufficient.',
    single_shaft_faq_q4: 'What is the lifespan of the rotor and blades?',
    single_shaft_faq_a4: 'Blades are made of durable alloy steel and offer 2000-5000 hours of use depending on the type of material processed. The rotor life exceeds 10 years.',
    single_shaft_faq_q5: 'What does machine capacity depend on?',
    single_shaft_faq_a5: 'Capacity varies depending on the type, moisture content, density and shredding size of the processed material. Light materials such as plastic and paper can be processed at higher capacities.',
    single_shaft_video_title: 'Single Shaft Shredder Video',
    single_shaft_watch_video: 'Watch Video',
    single_shaft_similar_products: 'Similar Products',
    single_shaft_ecatalog_btn: 'E-Catalog',
    youtube_channel_title: 'Check Out Our YouTube Channel',
    youtube_channel_description: 'Find all our machine operation videos, customer testimonials and production processes on our YouTube channel.',
    visit_youtube: 'Visit YouTube Channel',
    
    // Product Category Page
    about_our_machines: 'About Our Machines',
    key_features: 'Key Features',
    our_models: 'Our Models',
    select_model_description: 'Select the model that suits your needs and review detailed technical specifications',
    need_help_choosing: 'Need Help Choosing a Model?',
    contact_us_for_consultation: 'Our expert team will help you select the most suitable machine',
    contact_us: 'Contact Us',
    single_shaft_advantage_1_title: 'Flexible Use',
    single_shaft_advantage_1_desc: 'Optimized shredding for different waste types',
    single_shaft_advantage_2_title: 'High Efficiency',
    single_shaft_advantage_2_desc: 'Energy-efficient motor and powerful performance',
    single_shaft_advantage_3_title: 'Safe Operation',
    single_shaft_advantage_3_desc: 'Automatic protection systems and emergency stop',
    single_shaft_advantage_4_title: 'Easy Maintenance',
    single_shaft_advantage_4_desc: 'Quick blade replacement and simple service access',
    
    // Dual Shaft Product Detail Page
    dual_shaft_main_title: 'Dual Shaft Shredder',
    dual_shaft_subtitle: 'Powerful Shredding Performance for Challenging Industrial Waste',
    dual_shaft_description_1: 'The Dual Shaft Shredder safely shreds high-strength metal, plastic, wood, rubber, household and industrial waste with the low speed - high torque principle.',
    dual_shaft_description_2: 'Developed with MT Makina engineering, this system generates high cutting force through two powerful shafts working synchronously.',
    dual_shaft_description_3: 'The machine offers long-lasting use with heavy-duty body structure, special alloy cutting blades and automatic reverse feature.',
    dual_shaft_description_4: 'Thanks to the dual shaft structure, material jams are prevented and the cutting process is performed more balanced.',
    dual_shaft_description_5: 'Additionally, the PLC controlled system adapts to load changes without operator intervention. This minimizes system failures and ensures continuous efficient operation.',
    dual_shaft_advantages_title: 'Advantages of Dual Shaft Shredders',
    dual_shaft_adv_1_title: 'High Cutting Force',
    dual_shaft_adv_1_desc: 'Maximum torque on thick and hard waste thanks to dual shaft structure.',
    dual_shaft_adv_2_title: 'Reverse Function',
    dual_shaft_adv_2_desc: 'Automatically reverses against jams.',
    dual_shaft_adv_3_title: 'Low Noise Level',
    dual_shaft_adv_3_desc: 'Low speed system providing energy efficiency.',
    dual_shaft_adv_4_title: 'Modular Blade System',
    dual_shaft_adv_4_desc: 'Replaceable blades ensure easy maintenance and long life.',
    dual_shaft_performance_title: 'Maximum Efficiency and Reliability in Dual Shaft Shredders',
    dual_shaft_perf_1: 'Two Powerful Shafts Working Synchronously',
    dual_shaft_perf_2: 'High Performance System for Metal and Plastic Waste',
    dual_shaft_perf_3: 'Energy Efficient Hydraulic Power Unit',
    dual_shaft_tech_specs_title: 'CS Series Technical Specifications',
    dual_shaft_tech_motor: 'Motor Power',
    dual_shaft_tech_rotor_speed: 'Cutting Shaft Speed',
    dual_shaft_tech_blade_count: 'Blade Count',
    dual_shaft_tech_rotor_length: 'Rotor Length',
    dual_shaft_tech_blade_thickness: 'Blade Thickness',
    dual_shaft_tech_capacity: 'Production Capacity',
    dual_shaft_tech_weight: 'Weight',
    dual_shaft_faq_title: 'Dual Shaft Shredder F.A.Q.',
    dual_shaft_faq_q1: 'What materials does the Dual Shaft Shredder process?',
    dual_shaft_faq_a1: 'Dual shaft shredders process challenging materials such as metal, plastic, wood, rubber, tires, electronic waste, textiles, household waste and industrial solid waste.',
    dual_shaft_faq_q2: 'What does the reverse system do?',
    dual_shaft_faq_a2: 'The automatic reverse system reverses the shafts when material jamming or overload occurs inside the machine, clearing the jam and preventing blade damage.',
    dual_shaft_faq_q3: 'What is the difference between CS series models?',
    dual_shaft_faq_a3: 'CS series models differ in rotor length, motor power and capacity. While CS-60 is ideal for small businesses, CS-200 is designed for large industrial facilities.',
    dual_shaft_faq_q4: 'How long does maintenance and blade replacement take?',
    dual_shaft_faq_a4: 'Thanks to the modular blade system, blade replacement can be completed in approximately 2-3 hours. Regular maintenance period is recommended every 1000 operating hours.',
    dual_shaft_faq_q5: 'What factors does machine capacity depend on?',
    dual_shaft_faq_a5: 'Capacity varies depending on the type, size, moisture content and desired output size of the material being processed. Hard materials are processed at lower capacity, soft materials at higher capacity.',
    dual_shaft_video_title: 'Dual Shaft Shredder Video',
    dual_shaft_watch_video: 'Watch Video',
    dual_shaft_similar_products: 'Similar Products',
    dual_shaft_ecatalog_btn: 'E-Catalog',
  },
  ru: {
    // Header & Navigation
    nav_home: 'Главная',
    nav_corporate: 'О компании',
    nav_products: 'Продукция',
    nav_wastes: 'Виды отходов',
    nav_technology: 'Технологии',
    nav_references: 'Референсы',
    nav_contact: 'Контакты',
    nav_ecatalog: 'Электронный каталог',
    models: 'Модели',
    btn_quote: 'Получить предложение!',
    btn_view_details: 'Подробнее',
    btn_contact_us: 'Связаться с нами',
    
    // Page Titles
    page_title_home: 'ИЗМЕЛЬЧИТЕЛИ',
    page_title_shredders: 'Измельчители MT Makina',
    page_title_location: 'Наш адрес',
    page_title_headquarters: 'Главный офис',
    page_title_contact_info: 'Контактная информация',
    page_title_working_hours: 'Часы работы',
    
    // Descriptions
    desc_location: 'Мы ждем вас в нашем главном офисе в Эсенюрт / Стамбул.',
    desc_map_label: 'MT MAKINA ГЛАВНЫЙ ОФИС',
    
    // Corporate Dropdown
    nav_about: 'О нас',
    nav_certificates: 'Наши сертификаты',
    nav_fair: 'Ярмарка',
    nav_refs: 'Референции',
    
    // Wastes Dropdown
    waste_household: 'Бытовые отходы',
    waste_electronic: 'Электронные отходы',
    waste_tire: 'Шинные отходы',
    waste_metal: 'Металлические отходы',
    waste_glass: 'Стеклянные отходы',
    waste_paper: 'Бумажно-картонные отходы',
    waste_plastic: 'Пластиковые отходы',
    waste_organic: 'Органические отходы',
    waste_medical: 'Медицинские отходы',
    waste_tree_root: 'Отходы корней деревьев',
    waste_animal: 'Животные отходы',
    waste_packaging: 'Упаковочные отходы',
    waste_pallet: 'Поддоны',
    waste_textile: 'Текстильные отходы',
    waste_aty: 'Отходы ATY',
    
    // Hero
    hero_title: 'Промышленная мощь в измельчительных машинах',
    hero_subtitle: 'Высокая эффективность, долгий срок службы и безопасная работа с экологически чистым производством.',
    btn_explore: 'Изучить продукты',
    
    // Intro Section
    intro_title: 'Экологически чистое производство и устойчивая переработка',
    intro_description: 'Измельчительные машины MT MAKINA, обеспечивающие высокую эффективность в процессах управления промышленными отходами и переработки, гарантируют эффективное измельчение различных материалов благодаря прочной конструкции и мощным системам лезвий. Системы, производимые для многих материалов, таких как шины, металл, пластик, дерево, текстиль, бытовые и промышленные отходы, способствуют сокращению объема отходов и эффективному использованию ресурсов, предоставляя устойчивые решения по переработке. Для получения подробной информации о измельчительных машинах MT MAKINA, которые предлагают высокую производительность и долговечное использование с моделями, разработанными для особых нужд, свяжитесь с нами.',
    eco_friendly: 'Экологичность',
    recycling: 'Переработка',
    durability: 'Прочность',
    performance: 'Производительность',
    
    // Products
    products_title: 'Категории продуктов',
    products_description: 'Высокопроизводительные измель��ительные машины MT Makina выделяются в процессах промышленной переработки благодаря прочной конструкции корпуса и эффективным системам лезвий.',
    products_subtitle: 'Мощные и эффективные измельчительные машины MT Makina: одновальные, двухвальные, четырехвальные, металлические, поддонные, пластиковые, стеклянные, органические, медицинские и другие.',
    btn_details: 'Подробнее',
    
    // Technology
    tech_title: 'Технология и инженерия',
    tech_subtitle: 'Инженерные решения с фокусом на гидравлические системы, геометрию режущих лезвий, автоматизацию и энергоэффективность.',
    tech_hydraulic: 'Гидравлические системы',
    tech_hydraulic_desc: 'Максимальная эффективность с высоким гидравлическим давлением',
    tech_blade: 'Технология режущих лезвий',
    tech_blade_desc: 'Долговечная резка со специальной геометрией и прочными материалами',
    tech_automation: 'Решения автоматизации',
    tech_automation_desc: 'Интеллектуальные системы управления и мониторинга с ПЛК',
    tech_energy: 'Энергоэффективность',
    tech_energy_desc: 'Высокая производительность при низком энергопотреблении',
    
    // References
    ref_title: 'Наши референции',
    ref_subtitle: 'Мы предоставляем промышленные решения нашим партнерам по всему миру.',
    ref_main_title: 'Удовлетворенность клиентов и истории успеха',
    ref_main_subtitle: 'В MT Makina мы всегда ставим удовлетворенность клиентов на первое место. Отзывы наших деловых партнеров помогают нам улучшать качество наших продуктов и услуг. Наши успешно завершенные проекты являю��ся на��ими лучшими рекомендациями.',
    ref_main_paragraph: 'Как надежный деловой партнер в области решений по переработке и управлению отходами, мы продолжаем работать над устойчивым будущим. Сотрудничая с MT Makina, вы можете внести свой вклад в экологическую устойчивость и сделать свои процессы управления отходами более эффективными.',
    ref_global_title: 'Глобальная экспортная сеть',
    ref_global_subtitle: 'Обслуживание клиентов в Европе, на Ближнем Востоке и в Азии.',
    
    // Contact
    contact_title: 'Контакт',
    contact_headquarters: 'Главный офис',
    contact_hq_address: 'Cumhuriyet Mahallesi, Nazım Hikmet Bulvarı, 1983 Sk. Kent Palas 2 Этаж:7, D:85-86, PK:34512 Esenyurt / СТАМБУЛ',
    contact_sales: 'Продажи',
    contact_export: 'Экспорт',
    contact_whatsapp: 'Whatsapp',
    contact_saudi_rep: 'Представитель в Саудовской Аравии',
    contact_accounting: 'Бухгалтерия',
    contact_consulting: 'Консультации',
    
    // CTA
    cta_title: 'Спланируйте свою машину с нами',
    cta_subtitle: 'Давайте вместе разработаем систему измельчения, подходящую для вашего проекта.',
    
    // Footer
    footer_contact: 'Контакт',
    footer_address: 'Адрес: Стамбул, Турция',
    footer_phone: 'Телефон: +90 XXX XXX XX XX',
    footer_email: 'Email: info@mtmakina.com.tr',
    footer_quick_links: 'Быстрые ссылки',
    footer_social: 'Социальные сети',
    footer_copyright: '© 2025 MT Makina Ltd. - Все права защищены',
    footer_full_address: 'Cumhuriyet Mah. 1983 Sk. Kent Palas 2 Этаж:7 D:85-86 PK:34512 Esenyurt / Стамбул / ТУРЦИЯ',
    footer_full_phone: '+90 212 613 31 82',
    footer_full_email: 'info@mtmakina.com.tr',
    footer_website: 'www.mtmakina.com.tr',
    
    // Products
    product_single_shaft: 'Одновальный измельчитель',
    product_dual_shaft: 'Двухвальный измельчитель',
    product_quad_shaft: 'Четырехвальный измельчитель',
    product_metal: 'Измельчитель металла',
    product_pallet: 'Измельчитель поддонов',
    product_glass: 'Дробилка стеклянных бутылок',
    product_plastic: 'Измельчитель пластика',
    product_organic: 'Измельчитель органических отходов',
    product_tire: 'Измельчитель шин',
    
    // Single Shaft Product Detail Page
    single_shaft_main_title: 'Одновальный измельчитель твердых отходов',
    single_shaft_subtitle: 'Высокая эффективность и мощная производительность для широкого спектра отходов',
    single_shaft_description_1: 'Одновальный измельчитель твердых отходов эффективно измельчает бытовые, промышленные, пластиковые, бумажные, текстильные, алюминиевые и упаковочные отходы. Разработанные с инженерией MT Makina, эти системы обеспечивают долговечное использование благодаря высокомоментной конструкции вала и энергоэффективной гидравлической системе.',
    single_shaft_description_2: 'Благодаря системе автоматизации с управлением ПЛК, функция автоматического реверса активируется в случае перегрузки. Эта функция продлевает срок службы режущих лезвий и минимизирует потребности в обслуживании.',
    single_shaft_description_3: 'Одновальные дробилки MT Makina оптимизированы для промышленных применений, требующих высокой прочности. Максимальная эффективность достигается с длиной ротора 800 – 1500 мм, сменными модулями лезвий и системой автоматического контроля подачи.',
    single_shaft_advantages_title: 'Преимущества одновального измельчителя твердых отходов',
    single_shaft_adv_1_title: 'Высокомоментная система вала',
    single_shaft_adv_1_desc: 'Мощная и стабильная производительность даже с материалами для тяжелых условий эксплуатации.',
    single_shaft_adv_2_title: 'Автоматический реверс',
    single_shaft_adv_2_desc: 'Интеллектуальная система предотвращения заклинивания, долговечные лезвия.',
    single_shaft_adv_3_title: 'Низкий уровень шума и энергопотребления',
    single_shaft_adv_3_desc: 'Инженерный дизайн, ориентированный на эффективность.',
    single_shaft_performance_title: 'Максимальная производительность и эффективность одновальных измельчителей',
    single_shaft_perf_1: 'Применение для переработки металла и пластика',
    single_shaft_perf_2: 'Прочная конструкция ротора',
    single_shaft_perf_3: 'Система подачи высокой мощности',
    single_shaft_tech_specs_title: 'Технические характеристики',
    single_shaft_tech_model: 'Модель',
    single_shaft_tech_model_value: 'TSH-800 / TSH-1000 / TSH-1500',
    single_shaft_tech_motor: 'Мощность двигателя',
    single_shaft_tech_motor_value: '37 – 90 кВт',
    single_shaft_tech_rotor_length: 'Длина ротора',
    single_shaft_tech_rotor_length_value: '800 – 1500 мм',
    single_shaft_tech_rotor_diameter: 'Диаметр ротора',
    single_shaft_tech_rotor_diameter_value: '400 – 600 мм',
    single_shaft_tech_blade_count: 'Количество лезвий',
    single_shaft_tech_blade_count_value: '30 – 60 шт',
    single_shaft_tech_weight: 'Вес',
    single_shaft_tech_weight_value: '2.5 – 6 тонн',
    single_shaft_tech_feed_opening: 'Отверстие подачи',
    single_shaft_tech_feed_opening_value: '800 x 1000 мм',
    single_shaft_tech_control: 'Система управления',
    single_shaft_tech_control_value: 'ПЛК – Автоматический реверс',
    single_shaft_tech_capacity: 'Производительность',
    single_shaft_tech_capacity_value: '800 – 3000 кг/ч',
    single_shaft_faq_title: 'Часто задаваемые вопросы об одновальном измельчителе',
    single_shaft_faq_q1: 'Какие отходы обрабатывает одновальный измельчитель?',
    single_shaft_faq_a1: 'Одновальные измельчители могут использоваться для широкого спектра, включая бытовые отходы, пластик, бумагу, картон, текстиль, алюминиевую упаковку, деревянные поддоны и органические отходы.',
    single_shaft_faq_q2: 'Как работает система автоматического реверса?',
    single_shaft_faq_a2: 'Благодаря системе управления ПЛК, когда машина обнаруживает перегрузку или заклинивание, она автоматически зап��скает ротор в обратном направлении для обеспечения правильного измельчения и продления срока службы лезвия.',
    single_shaft_faq_q3: 'Каковы требования к техническому обслуживанию?',
    single_shaft_faq_a3: 'Рекомендуется регулярная проверка лезвий, проверка гидравлической системы и смазка. Достаточно общего осмотра каждые 500 часов работы.',
    single_shaft_faq_q4: 'Каков срок службы ротора и лезвий?',
    single_shaft_faq_a4: 'Лезвия изготовлены из прочной легированной стали и обеспечивают 2000-5000 часов использования в зависимости от типа обрабатываемого материала. Срок службы ротора превышает 10 лет.',
    single_shaft_faq_q5: 'От чего зависит производительность машины?',
    single_shaft_faq_a5: 'Производительность варьируется в зависимости от типа, содержания влаги, плотности и размера измельчения обрабатываемого материала. Легкие материалы, такие как пластик и бумага, могут обрабатываться с более высокой производительностью.',
    single_shaft_video_title: 'Видео одновального измельчителя',
    single_shaft_watch_video: 'Смотреть видео',
    single_shaft_similar_products: 'Похожие продукты',
    single_shaft_ecatalog_btn: 'Электронный каталог',
    youtube_channel_title: 'Посетите наш канал на YouTube',
    youtube_channel_description: 'Все видео работы наших машин, отзывы клиентов и производственные процессы на нашем канале YouTube.',
    visit_youtube: 'Перейти на канал YouTube',
    
    // Product Category Page
    about_our_machines: 'О наших машинах',
    key_features: 'Ключевые особенности',
    our_models: 'Наши модели',
    select_model_description: 'Выберите модель, которая соответствует вашим потребностям',
    need_help_choosing: 'Нужна помощь в выборе модели?',
    contact_us_for_consultation: 'Наша команда экспертов поможет вам выбрать наиболее подходящую машину',
    contact_us: 'Свяжитесь с нами',
    single_shaft_advantage_1_title: 'Гибкое использование',
    single_shaft_advantage_1_desc: 'Оптимизированное измельчение для различных типов отходов',
    single_shaft_advantage_2_title: 'Высокая эффективность',
    single_shaft_advantage_2_desc: 'Энергоэффективный двигатель и мощная производительность',
    single_shaft_advantage_3_title: 'Безопасная работа',
    single_shaft_advantage_3_desc: 'Автоматические системы защиты и аварийная остановка',
    single_shaft_advantage_4_title: 'Легкое обслуживание',
    single_shaft_advantage_4_desc: 'Быстрая замена лезвий и простой доступ для обслуживания',
    
    // Dual Shaft Product Detail Page
    dual_shaft_main_title: 'Двухвальный измельчитель',
    dual_shaft_subtitle: 'Мощная производительность измельчения для сложных промышленных отходов',
    dual_shaft_description_1: 'Двухвальный измельчитель безопасно измельчает высокопрочные металлы, пластик, дерево, резину, бытовые и промышленные отходы по принципу низкой скорости - высокого крутящего момента.',
    dual_shaft_description_2: 'Разработанная с инженерией MT Makina, эта система генерирует высокую силу резания через два мощных синхронно работающих вала.',
    dual_shaft_description_3: 'Машина обеспечивает долговечное использование благодаря конструкции корпуса для тяжелых условий эксплуатации, специальным режущим лезвиям из сплава и функции автоматического реверса.',
    dual_shaft_description_4: 'Благодаря двухвальной конструкции предотвращаются заклинивания материала, и процесс резки выполняется более сбалансировано.',
    dual_shaft_description_5: 'Кроме того, система с управлением ПЛК адаптируется к изменениям нагрузки без вмешательства оператора. Это минимизирует сбои системы и обеспечивает непрерывную эффективную работу.',
    dual_shaft_advantages_title: 'Преимущества двухвальных измельчителей',
    dual_shaft_adv_1_title: 'Высокая сила резания',
    dual_shaft_adv_1_desc: 'Максимальный крутящий момент на толстых и твердых отходах благодаря двухвальной конструкции.',
    dual_shaft_adv_2_title: 'Функци�� реверса',
    dual_shaft_adv_2_desc: 'Автоматически реверсирует против заклиниваний.',
    dual_shaft_adv_3_title: 'Низкий уровень шума',
    dual_shaft_adv_3_desc: 'Низкоскоростная система, обеспечивающая энергоэффективность.',
    dual_shaft_adv_4_title: 'Модульная система лезвий',
    dual_shaft_adv_4_desc: 'Сменные лезвия обеспечивают легкое обслуживание и долгий срок службы.',
    dual_shaft_performance_title: 'Максимальная эффективность и надежность двухвальных измельчителей',
    dual_shaft_perf_1: 'Два мощных синхронно работающих вала',
    dual_shaft_perf_2: 'Высокопроизводительная система для металлических и пластиковых отходов',
    dual_shaft_perf_3: 'Энергоэффективная гидравлическая силовая установка',
    dual_shaft_tech_specs_title: 'Технические характеристики серии CS',
    dual_shaft_tech_motor: 'Мощность двигателя',
    dual_shaft_tech_rotor_speed: 'Скорость режущего вала',
    dual_shaft_tech_blade_count: 'Количество лезвий',
    dual_shaft_tech_rotor_length: 'Длина ротора',
    dual_shaft_tech_blade_thickness: 'Толщина лезвия',
    dual_shaft_tech_capacity: 'Производственная мощность',
    dual_shaft_tech_weight: 'Вес',
    dual_shaft_faq_title: 'Часто задаваемые вопросы о двухвальном измельчителе',
    dual_shaft_faq_q1: 'Какие материалы обрабатывает двухвальный измельчитель?',
    dual_shaft_faq_a1: 'Двухвальные измельчители обрабатывают сложные материалы, такие как металл, пластик, дерево, резина, шины, электронные отходы, текстиль, бытовые отходы и промышленные твердые отходы.',
    dual_shaft_faq_q2: 'Для чего нужна система реверса?',
    dual_shaft_faq_a2: 'Система автоматического реверса реверсирует валы при заклинивании материала или перегрузке внутри машины, устраняя заклинивание и предотвращая повреждение лезвия.',
    dual_shaft_faq_q3: 'В чем разница между моделями серии CS?',
    dual_shaft_faq_a3: 'Модели серии CS различаются по длине ротора, мощности двигателя и производительности. В то время как CS-60 идеален для малого бизнеса, CS-200 предназначен для крупных промышленных объектов.',
    dual_shaft_faq_q4: 'Сколько времени занимает техническое обслуживание и замена лезвий?',
    dual_shaft_faq_a4: 'Благодаря модульной системе лезвий замену лезвия можно завершить примерно за 2-3 часа. Регулярный период технического обслуживания рекомендуется каждые 1000 часов работы.',
    dual_shaft_faq_q5: 'От каких факторов зависит производительность машины?',
    dual_shaft_faq_a5: 'Производительность варьируется в зависимости от типа, размера, содержания влаги и желаемого размера выхода обрабатываемого материала. Твердые материалы обрабатываются с меньшей производительностью, мягкие материалы - с более высо��ой.',
    dual_shaft_video_title: 'Видео двухвального измельчителя',
    dual_shaft_watch_video: 'Смотреть видео',
    dual_shaft_similar_products: 'Похожие продукты',
    dual_shaft_ecatalog_btn: 'Электронный каталог',
  },
  ar: {
    // Header & Navigation
    nav_home: 'الرئيسية',
    nav_corporate: 'من نحن',
    nav_products: 'المنتجات',
    nav_wastes: 'أنواع النفايات',
    nav_technology: 'التكنولوجيا',
    nav_references: 'المراجع',
    nav_contact: 'اتصل بنا',
    nav_ecatalog: 'الكتالوج الإلكتروني',
    models: 'النماذج',
    btn_quote: 'احصل على عرض الآن!',
    btn_view_details: 'عرض التفاصيل',
    btn_contact_us: 'تواصل معنا',
    
    // Page Titles
    page_title_home: 'آلات تمزيق',
    page_title_shredders: 'آلات تمزيق MT Makina',
    page_title_location: 'موقعنا',
    page_title_headquarters: 'المكتب الرئيسي',
    page_title_contact_info: 'معلومات الاتصال',
    page_title_working_hours: 'ساعات العمل',
    
    // Descriptions
    desc_location: 'نرحب بكم في مقرنا الرئيسي في إسنيورت / إسطنبول.',
    desc_map_label: 'MT MAKINA المكتب الرئيسي',
    
    // Corporate Dropdown
    nav_about: 'معلومات عنا',
    nav_certificates: 'شهاداتنا',
    nav_fair: 'معرض',
    nav_refs: 'المراجع',
    
    // Wastes Dropdown
    waste_household: 'النفايات المنزلية',
    waste_electronic: 'النفايات الإلكترونية',
    waste_tire: 'نفايات الإطارات',
    waste_metal: 'النفايات المعدنية',
    waste_glass: 'نفايات الزجاج',
    waste_paper: 'نفايات الورق والكرتون',
    waste_plastic: 'النفايات البلاستيكية',
    waste_organic: 'النفايات العضوية',
    waste_medical: 'النفايات الطبية',
    waste_tree_root: 'نفايات جذور الأشجار',
    waste_animal: 'النفايات الحيوانية',
    waste_packaging: 'نفايات التغليف',
    waste_pallet: 'نفايات المنصات',
    waste_textile: 'نفايات النسيج',
    waste_aty: 'نفايات ATY',
    
    // Hero
    hero_title: 'القوة الصناعية في آلات التقطيع',
    hero_subtitle: 'كفاءة عالية وعمر طويل وتشغيل آمن مع إنتاج صديق للبيئة.',
    btn_explore: 'استكشف المنتجات',
    
    // Intro Section
    intro_title: 'إنتاج صديق للبيئة وإعادة تدوير مستدامة',
    intro_description: 'آلات التقطيع MT MAKINA، التي توفر كفاءة عالية في إدارة النفايات الصناعية وعمليات إعادة التدوير، تضمن التقطيع الفعال لمختلف المواد بفضل هيكلها المتين وأنظمة الشفرات القوية. الأنظمة المنتجة للعديد من المواد مثل الإطارات والمعادن والبلاستيك والخشب والنسيج والنفايات المنزلية والصناعية، تساهم في تقليل حجم النفايات والاستخدام الفعال للموارد من خلال توفير حلول إعادة تدوير مستدامة. للحصول على معلومات مفصلة حول آلات التقطيع MT MAKINA التي تقدم أداءً عاليًا واستخدامًا طويل الأمد مع نماذج مصممة للاحتياجات الخاصة، يرجى الاتصال بنا.',
    eco_friendly: 'صديق للبيئة',
    recycling: 'إعادة التدوير',
    durability: 'المتانة',
    performance: 'الأداء',
    
    // Products
    products_title: 'فئات المنتجات',
    products_description: 'آلات التقطيع عالية الأداء من MT Makina تحدث فرقًا في عمليات إعادة التدوير الصناعية بفضل هيكلها القوي وأنظمة الشفرات الفعالة.',
    products_subtitle: 'آلات التقطيع القوية والفعالة من MT Makina: أحادي، مزدوج، رباعي العمود، معدني، منصات، بلاستيك، زجاج، عضوي، طبي والمزيد.',
    btn_details: 'عرض التفاصيل',
    
    // Technology
    tech_title: 'التكنولوجيا والهندسة',
    tech_subtitle: 'حلول هندسية تركز على الأنظمة الهيدروليكية، وهندسة الشفرات القاطعة، والأتمتة وكفاءة الطاقة.',
    tech_hydraulic: 'الأنظمة الهيدروليكية',
    tech_hydraulic_desc: 'كفاءة قصوى مع القوة الهيدروليكية عالية الضغط',
    tech_blade: 'تقنية الشفرات القاطعة',
    tech_blade_desc: 'قطع طويل الأمد بهندسة خاصة ومواد متينة',
    tech_automation: 'حلول الأتمتة',
    tech_automation_desc: 'أنظمة التشغيل والمراقبة الذكية المتحكم فيها بواسطة PLC',
    tech_energy: 'كفاءة الطاقة',
    tech_energy_desc: 'أداء عالي مع استهلاك منخفض للطاقة',
    
    // References
    ref_title: 'مراجعنا',
    ref_subtitle: 'نقدم حلولاً صناعية لشركائنا في جميع أنحاء العالم.',
    ref_main_title: 'رضا العملاء وقصص النجاح',
    ref_main_subtitle: 'في MT Makina، نضع رضا العملاء دائمًا في المقام الأول. تساعدنا تعليقات شركائنا التجاريين على تحسين جودة منتجاتنا وخدماتنا. مشاريعنا المنجزة بنجاح هي أفضل مراجعنا.',
    ref_main_paragraph: 'كشريك تجاري موثوق في حلول إعادة التدوير وإدارة النفايات، نواصل العمل من أجل مستقبل مستدام. من خلال التعاون مع MT Makina، يمكنك المساهمة في الاستدامة البيئية وجعل عمليات إدارة النفايات أكثر كفاءة.',
    ref_global_title: 'شبكة التصدير العالمية',
    ref_global_subtitle: 'خدمة العملاء في أوروبا والشرق الأوسط وآسيا.',
    
    // Contact
    contact_title: 'اتصل',
    contact_headquarters: 'المقر الرئيسي',
    contact_hq_address: 'Cumhuriyet Mahallesi, Nazım Hikmet Bulvarı, 1983 Sk. Kent Palas 2 الطابق:7, D:85-86, PK:34512 Esenyurt / إسطنبول',
    contact_sales: 'المبيعات',
    contact_export: 'التصدير',
    contact_whatsapp: 'واتساب',
    contact_saudi_rep: 'ممثل السعودية',
    contact_accounting: 'المحاسبة',
    contact_consulting: 'الاستشارات',
    
    // CTA
    cta_title: 'خطط لآلتك معنا',
    cta_subtitle: 'دعنا نصمم نظام التقطيع المناسب لمشروعك معًا.',
    
    // Footer
    footer_contact: 'اتصل',
    footer_address: 'العنوان: إسطنبول، تركيا',
    footer_phone: 'الهاتف: +90 XXX XXX XX XX',
    footer_email: 'البريد الإلكتروني: info@mtmakina.com.tr',
    footer_quick_links: 'روابط سريعة',
    footer_social: 'وسائل التواصل الاجتماعي',
    footer_copyright: '© 2025 MT Makina Ltd. - جميع الحقوق محفوظة',
    footer_full_address: 'Cumhuriyet Mah. 1983 Sk. Kent Palas 2 الطابق:7 D:85-86 PK:34512 Esenyurt / إسطنبول / تركيا',
    footer_full_phone: '+90 212 613 31 82',
    footer_full_email: 'info@mtmakina.com.tr',
    footer_website: 'www.mtmakina.com.tr',
    
    // Products
    product_single_shaft: 'آلة تمزيق أحادية العمود',
    product_dual_shaft: 'آلة تمزيق ثنائية العمود',
    product_quad_shaft: 'آلة تمزيق رباعية العمود',
    product_metal: 'آلة تمزيق المعادن',
    product_pallet: 'آلة تمزيق المنصات',
    product_glass: 'آلة تكسير الزجاجات',
    product_plastic: 'آلة تمزيق البلاستيك',
    product_organic: '��لة تمزيق النفايات العضوية',
    product_tire: 'آلة تمزيق الإطارات',
    
    // Single Shaft Product Detail Page
    single_shaft_main_title: 'آلة تمزيق النفايات الصلبة أحادية العمود',
    single_shaft_subtitle: 'كفاءة عالية وأداء قوي لمجموعة واسعة من النفايات',
    single_shaft_description_1: 'آلة تمزيق النفايات الصلبة أحادية العمود تمزق بفعالية النفايات المنزلية والصناعية والبلاستيكية والورقية والنسيجية والألمنيوم والتغليف. تم تطويرها بهندسة MT Makina، توفر هذه الأنظمة استخدامًا طويل الأمد بفضل تصميم العمود عالي عزم الدوران ونظام هيدروليكي موفر للطاقة.',
    single_shaft_description_2: 'بفضل نظام الأتمتة المتحكم به بواسطة PLC، يتم تفعيل وظيفة الرجوع التلقائي في حالة الحمل الزائد. هذه الميزة تطيل عمر الشفرات القاطعة وتقلل احتياجات الصيانة إلى الحد الأدنى.',
    single_shaft_description_3: 'الكسارات أحادية العمود من MT Makina محسّنة للتطبيقات الصناعية التي تتطلب متانة عالية. يتم تحقيق أقصى قدر من الكفاءة بطول دوار 800 – 1500 مم، ووحدات شفرات قابلة للاستبدال ونظام التحكم التلقائي في التغذية.',
    single_shaft_advantages_title: 'مزايا آلة تمزيق النفايات الصلبة أحادية العمود',
    single_shaft_adv_1_title: 'نظام عمود عالي عزم الدوران',
    single_shaft_adv_1_desc: 'أداء قوي ومستقر حتى في المواد ذات الخدمة الشاقة.',
    single_shaft_adv_2_title: 'الرجوع التلقائي',
    single_shaft_adv_2_desc: 'نظام ذكي يمنع الانسدادات، شفرات طويلة الأمد.',
    single_shaft_adv_3_title: 'ضوضاء منخفضة واستهلاك للطاقة',
    single_shaft_adv_3_desc: 'تصميم هندسي يركز على الكفاءة.',
    single_shaft_performance_title: 'أقصى أداء وكفاءة في آلات التمزيق أحادية العمود',
    single_shaft_perf_1: 'تطبيقات إعادة تدوير المعادن والبلاستيك',
    single_shaft_perf_2: 'تصميم دوار متين',
    single_shaft_perf_3: 'نظام تغذية عالي السعة',
    single_shaft_tech_specs_title: 'المواصفات الفنية',
    single_shaft_tech_model: 'الموديل',
    single_shaft_tech_model_value: 'TSH-800 / TSH-1000 / TSH-1500',
    single_shaft_tech_motor: 'قوة المحرك',
    single_shaft_tech_motor_value: '37 – 90 كيلووات',
    single_shaft_tech_rotor_length: 'طول الدوار',
    single_shaft_tech_rotor_length_value: '800 – 1500 مم',
    single_shaft_tech_rotor_diameter: 'قطر الدوار',
    single_shaft_tech_rotor_diameter_value: '400 – 600 مم',
    single_shaft_tech_blade_count: 'عدد الشفرات',
    single_shaft_tech_blade_count_value: '30 – 60 قطعة',
    single_shaft_tech_weight: 'الوزن',
    single_shaft_tech_weight_value: '2.5 – 6 طن',
    single_shaft_tech_feed_opening: 'فتحة التغذية',
    single_shaft_tech_feed_opening_value: '800 x 1000 مم',
    single_shaft_tech_control: 'نظام التحكم',
    single_shaft_tech_control_value: 'PLC – الرجوع التلقائي',
    single_shaft_tech_capacity: 'السعة',
    single_shaft_tech_capacity_value: '800 – 3000 كجم/س',
    single_shaft_faq_title: 'الأسئلة الشائعة حول آلة التمزيق أحادية العمود',
    single_shaft_faq_q1: 'ما هي النفايات التي تعالجها آلة التمزيق أحادية العمود؟',
    single_shaft_faq_a1: 'يمكن استخدام آلات التمزيق أحادية العمود لمجموعة واسعة بما في ذلك النفايات المنزلية والبلاستيك والورق والكرتون والمنسوجات وتغليف الألمنيوم والمنصات الخشبية والنفايات العضوية.',
    single_shaft_faq_q2: 'كيف يعمل نظام الرجوع التلقائي؟',
    single_shaft_faq_a2: 'بفضل نظام التحكم PLC، عندما تكتشف الآلة حملاً زائدًا أو انسدادًا، فإنها تشغل الدوار تلقائيًا في الاتجاه المعاكس لضمان التمزيق الصحيح وإطالة عمر الشفرة.',
    single_shaft_faq_q3: 'ما هي متطلبات الصيانة؟',
    single_shaft_faq_a3: 'يوصى بإجراء فحص منتظم للشفرات وفحص النظام الهيدروليكي والتشحيم. يكفي إجراء فحص عام كل 500 ساعة تشغيل.',
    single_shaft_faq_q4: 'ما هو عمر الدوار والشفرات؟',
    single_shaft_faq_a4: 'الشفرات مصنوعة من الفولاذ السبائكي المتين وتوفر 2000-5000 ساعة من الاستخدام حسب نوع المادة المعالجة. عمر الدوار يتجاوز 10 سنوات.',
    single_shaft_faq_q5: 'على ماذا تعتمد سعة الآلة؟',
    single_shaft_faq_a5: 'تختلف السعة اعتمادًا على نوع ومحتوى الرطوبة والكثافة وحجم التمزيق للمادة المعالجة. يمكن معالجة المواد الخفيفة مثل البلاستيك والورق بسعات أعلى.',
    single_shaft_video_title: 'فيديو آلة التمزيق أحادية العمود',
    single_shaft_watch_video: 'مشاهدة الفيديو',
    single_shaft_similar_products: 'منتجات مماثلة',
    single_shaft_ecatalog_btn: 'الكتالوج الإلكتروني',
    youtube_channel_title: 'تحقق من قناتنا على يوتيوب',
    youtube_channel_description: 'جميع مقاطع فيديو تشغيل آلاتنا وشهادات العملاء وعمليات الإنتاج على قناتنا على يوتيوب.',
    visit_youtube: 'زيارة قناة يوتيوب',
    
    // Product Category Page
    about_our_machines: 'حول آلاتنا',
    key_features: 'الميزات الرئيسية',
    our_models: 'نماذجنا',
    select_model_description: 'اختر النموذج الذي يناسب احتياجاتك',
    need_help_choosing: 'هل تحتاج مساعدة في اختيار النموذج؟',
    contact_us_for_consultation: 'سيساعدك فريق الخبراء لدينا في اختيار الآلة الأنسب',
    contact_us: 'اتصل بنا',
    single_shaft_advantage_1_title: 'استخدام مرن',
    single_shaft_advantage_1_desc: 'تمزيق محسّن لأنواع مختلفة من النفايات',
    single_shaft_advantage_2_title: 'كفاءة عالية',
    single_shaft_advantage_2_desc: 'محرك موفر للطاقة وأداء قوي',
    single_shaft_advantage_3_title: 'تشغيل آمن',
    single_shaft_advantage_3_desc: 'أنظمة حماية تلقائية وإيقاف طوارئ',
    single_shaft_advantage_4_title: 'صيانة سهلة',
    single_shaft_advantage_4_desc: 'استبدال سريع للشفرة ووصول بسيط للخدمة',
    
    // Dual Shaft Product Detail Page
    dual_shaft_main_title: 'آلة تمزيق ثنائية العمود',
    dual_shaft_subtitle: 'أداء تمزيق قوي للنفايات الصناعية الصعبة',
    dual_shaft_description_1: 'آلة التمزيق ثنائية العمود تمزق بأمان المعادن عالية القوة والبلاستيك والخشب والمطاط والنفايات المنزلية والصناعية بمبدأ السرعة المنخفضة - عزم الدوران العالي.',
    dual_shaft_description_2: 'تم تطويرها بهندسة MT Makina، يولد هذا النظام قوة قطع عالية من خلال عمودين قويين يعملان بشكل متزامن.',
    dual_shaft_description_3: 'توفر الآلة استخدامًا طويل الأمد بفضل هيكل الجسم للخدمة الشاقة، والشفرات القاطعة من السبائك الخاصة وميزة الرجوع التلقائي.',
    dual_shaft_description_4: 'بفضل الهيكل ثنائي العمود، يتم منع انحشار المواد ويتم تنفيذ عملية القطع بشكل أكثر توازناً.',
    dual_shaft_description_5: 'بالإضافة إلى ذلك، يتكيف نظام التحكم PLC مع تغيرات الحمل دون تدخل المشغل. هذا يقلل من أعطال النظام ويضمن التشغيل الفعال المستمر.',
    dual_shaft_advantages_title: 'مزايا آلات التمزيق ثنائية العمود',
    dual_shaft_adv_1_title: 'قوة قطع عالية',
    dual_shaft_adv_1_desc: 'أقصى عزم دوران على النفايات السميكة والصلبة بفضل الهيكل ثنائي العمود.',
    dual_shaft_adv_2_title: 'وظيفة الرجوع',
    dual_shaft_adv_2_desc: 'يعكس تلقائيًا ضد الانسدادات.',
    dual_shaft_adv_3_title: 'مستوى ضوضاء منخفض',
    dual_shaft_adv_3_desc: 'نظام منخفض السرعة يوفر كفاءة في استهلاك الطاقة.',
    dual_shaft_adv_4_title: 'نظام شفرات معياري',
    dual_shaft_adv_4_desc: 'الشفرات القابلة للاستبدال تضمن سهولة الصيانة وعمر طويل.',
    dual_shaft_performance_title: 'أقصى كفاءة وموثوقية في آلات التمزيق ثنائية العمود',
    dual_shaft_perf_1: 'عمودان قويان يعملان بشكل متزامن',
    dual_shaft_perf_2: 'نظام عالي الأداء للنفايات المعدنية والبلاستيكية',
    dual_shaft_perf_3: 'وحدة طاقة هيدروليكية موفرة للطاقة',
    dual_shaft_tech_specs_title: 'المواصفات الفنية لسلسلة CS',
    dual_shaft_tech_motor: 'قوة المحرك',
    dual_shaft_tech_rotor_speed: 'سرعة عمود القطع',
    dual_shaft_tech_blade_count: 'عدد الشفرات',
    dual_shaft_tech_rotor_length: 'طول الدوار',
    dual_shaft_tech_blade_thickness: 'سمك الشفرة',
    dual_shaft_tech_capacity: 'سعة الإنتاج',
    dual_shaft_tech_weight: 'الوزن',
    dual_shaft_faq_title: 'الأسئلة الشائعة حول آلة التمزيق ثنائية العمود',
    dual_shaft_faq_q1: 'ما هي المواد التي تعالجها آلة التمزيق ثنائية العمود؟',
    dual_shaft_faq_a1: 'آلات التمزيق ثنائية العمود تعالج مواد صعبة مثل المعادن والبلاستيك والخشب والمطاط والإطارات والنفايات الإلكترونية والمنسوجات والنفايات المنزلية والنفايات الصناعية الصلبة.',
    dual_shaft_faq_q2: 'ما هي وظيفة نظام الرجوع؟',
    dual_shaft_faq_a2: 'نظام الرجوع التلقائي يعكس الأعمدة عند حدوث انحشار المواد أو الحمل الزائد داخل الآلة، مما يزيل الانسداد ويمنع تلف الشفرة.',
    dual_shaft_faq_q3: 'ما هو الفرق بين موديلات سلسلة CS؟',
    dual_shaft_faq_a3: 'تختلف موديلات سلسلة CS في طول الدوار وقوة المحرك والسعة. بينما CS-60 مثالي للشركات الصغيرة، تم تصميم CS-200 للمنشآت الصناعية الكبيرة.',
    dual_shaft_faq_q4: 'كم من الوقت تستغرق الصيانة واستبدال الشفرة؟',
    dual_shaft_faq_a4: 'بفضل نظام الشفرات المعياري، يمكن إكمال استبدال الشفرة في حوالي 2-3 ساعات. يوصى بفترة الصيانة المنتظمة كل 1000 ساعة تشغيل.',
    dual_shaft_faq_q5: 'على أي عوامل تعتمد سعة الآلة؟',
    dual_shaft_faq_a5: 'تختلف السعة اعتمادًا على نوع وحجم ومحتوى الرطوبة والحجم المطلوب للخروج للمادة المعالجة. تتم معالجة المواد الصلبة بسعة أقل، والمواد الناعمة بسعة أعلى.',
    dual_shaft_video_title: 'فيديو آلة التمزيق ثنائية العمود',
    dual_shaft_watch_video: 'مشاهدة الفيديو',
    dual_shaft_similar_products: 'منتجات مماثلة',
    dual_shaft_ecatalog_btn: 'الكتالوج الإلكتروني',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.tr] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
