  'wood': {
    'TSY-100': {
      tr: {
        intro: 'TSY-100 yatay ağaç parçalama makinesi, 1000 mm rotor boyu ve 55-90 kW (2X) çift motor gücü ile orta ölçekli işletmeler için güçlü bir çözümdür.',
        paragraph1: 'TSY-100 model, 55-90 kW (2X) çift motor konfigürasyonu ile ağaç dalları, hurma lifli atıklar, bahçe budama artıkları ve odunsu malzemelerin güçlü parçalanmasını sağlar. 1000 mm rotor boyu ile orta ölçekli tarım kooperatifleri, belediye park bakım işletmeleri, biyokütle yakıt üretim tesisleri için ideal performans sunar. Yatay beslemeli hidrolik piston sistemi, uzun dalların kolayca işlenmesini sağlar.',
        paragraph2: 'TSY-100, özel tasarım rotor bıçakları ile lifli ve nemli malzemelerde yüksek performans gösterir. PLC kontrollü akıllı besleme sistemi, otomatik yük algılama ve ters çalışma fonksiyonu ile sıkışmaları önler. Değiştirilebilir elek sistemi ile farklı çıkış boyutları elde edilir. Hidrolik açılan elek sistemi bakım süresini minimize eder.',
        paragraph3: 'MT Makina TSY-100, çift motorlu tasarım standardında gelir. Opsiyonel özellikler: Kayış kasnaklı hidrolik kaplin, volanlı tasarım, rotor soğutma sistemi, otomatik yağlama ünitesi, farklı ölçülerde elek, hidrolik açılan elek sistemi, çıkış için helezon/konveyör/taşıma fanı uygulamaları. CE sertifikalı.'
      },
      en: {
        intro: 'TSY-100 horizontal wood shredder is a powerful solution for medium-scale operations with 1000 mm rotor length and 55-90 kW (2X) dual motor power.',
        paragraph1: 'TSY-100 model provides powerful shredding of tree branches, palm fibrous waste, garden pruning residues and woody materials with 55-90 kW (2X) dual motor configuration. With 1000 mm rotor length, it delivers ideal performance for medium-scale agricultural cooperatives, municipal park maintenance and biomass fuel production facilities. Horizontal feed hydraulic piston system enables easy processing of long branches.',
        paragraph2: 'TSY-100 shows high performance in fibrous and moist materials with special design rotor blades. PLC-controlled intelligent feeding system prevents jamming with automatic load detection and reverse function. Different output sizes are obtained with replaceable screen system. Hydraulically opening screen system minimizes maintenance time.',
        paragraph3: 'MT Makina TSY-100 comes standard with dual motor design. Optional features: Belt pulley hydraulic coupling, flywheel design, rotor cooling system, automatic lubrication unit, different size screens, hydraulically opening screen system, auger/conveyor/blower fan applications for output. CE certified.'
      },
      ru: {
        intro: 'Горизонтальный измельчитель древесины TSY-100 - мощное решение для средних предприятий с длиной ротора 1000 мм и двухмоторной мощностью 55-90 кВт (2X).',
        paragraph1: 'Модель TSY-100 обеспечивает мощное измельчение веток деревьев, волокнистых отходов пальм, садовых обрезков и древесных материалов с конфигурацией двух двигателей 55-90 кВт (2X). С длиной ротора 1000 мм обеспечивает идеальную производительность для средних сельскохозяйственных кооперативов, муниципальных парковых служб и заводов по производству биомассового топлива. Горизонтальная система подачи с гидравлическим поршнем обеспечивает легкую обработку длинных веток.',
        paragraph2: 'TSY-100 показывает высокую производительность на волокнистых и влажных материалах благодаря специальным роторным ножам. Интеллектуальная система подачи с ПЛК-управлением предотвращает заклинивание с автоматическим определением нагрузки и функцией реверса. Различные размеры на выходе получаются с заменяемой системой сит. Гидравлически открывающаяся система сит минимизирует время обслуживания.',
        paragraph3: 'MT Makina TSY-100 поставляется стандартно с двухмоторной конструкцией. Дополнительные функции: Гидравлическая муфта со шкивом, конструкция с маховиком, система охлаждения ротора, автоматический блок смазки, сита разных размеров, гидравлически открывающаяся система сит, шнек/конвейер/вентилятор для выхода. Сертифицировано CE.'
      },
      ar: {
        intro: 'آلة تقطيع الخشب الأفقية TSY-100 هي حل قوي للعمليات متوسطة الحجم مع طول دوار 1000 مم وقوة محرك مزدوج 55-90 كيلووات (2X).',
        paragraph1: 'يوفر طراز TSY-100 تقطيعًا قويًا لأغصان الأشجار ونفايات النخيل الليفية وبقايا تقليم الحدائق والمواد الخشبية مع تكوين محرك مزدوج 55-90 كيلووات (2X). مع طول دوار 1000 مم، يوفر أداءً مثاليًا للتعاونيات الزراعية متوسطة الحجم وعمليات صيانة المتنزهات البلدية ومرافق إنتاج وقود الكتلة الحيوية. يتيح نظام المكبس الهيدروليكي للتغذية الأفقية معالجة سهلة للفروع الطويلة.',
        paragraph2: 'يُظهر TSY-100 أداءً عاليًا في المواد الليفية والرطبة مع شفرات دوار ذات تصميم خاص. يمنع نظام التغذية الذكي المتحكم فيه بواسطة PLC الانحشار مع الكشف التلقائي عن الحمل ووظيفة الرجوع. يتم الحصول على أحجام مخرجات مختلفة مع نظام الشاشة القابل للاستبدال. يقلل نظام الشاشة الذي يفتح هيدروليكيًا من وقت الصيانة إلى الحد الأدنى.',
        paragraph3: 'يأتي MT Makina TSY-100 قياسيًا مع تصميم محرك مزدوج. ميزات اختيارية: وصلة هيدروليكية بكرة حزام، تصميم دولاب الموازنة، نظام تبريد الدوار، وحدة تشحيم تلقائي، شاشات بأحجام مختلفة، نظام شاشة يفتح هيدروليكيًا، لولب/ناقل/مروحة منفاخ للإخراج. معتمد CE.'
      }
    },
    'TSY-150': {
      tr: {
        intro: 'TSY-150 yatay ağaç parçalama makinesi, 1500 mm rotor boyu ve 75-110 kW (2X) yüksek motor gücü ile endüstriyel ölçekte üstün performans sağlar.',
        paragraph1: 'TSY-150 model, 75-110 kW (2X) güçlü çift motor ile ağaç gövdeleri, kalın dallar, hurma kütükleri ve yoğun odunsu atıkların hızlı parçalanmasını sağlar. 1500 mm rotor boyu ile büyük ölçekli tarım işletmeleri, biyokütle enerji santralleri, mobilya fabrikası atık geri dönüşümü ve odun pelet üretim tesisleri için mükemmel bir çözümdür. Çift hidrolik pistonlu besleme sistemi, ağır ve uzun malzemelerin güvenli işlenmesini garanti eder.',
        paragraph2: 'TSY-150, gelişmiş rotor tasarımı ve yüksek kaliteli çelik bıçaklar ile sert ahşap türleri, çam, meşe ve tropik ağaç türlerinde üstün performans gösterir. PLC tabanlı otomasyon sistemi, gerçek zamanlı yük izleme ve akıllı ters çalışma algoritması ile enerji verimliliği sağlar. Hidrolik açılır elek kasası ve hızlı bakım sistemi ile operasyonel süre minimumda tutulur.',
        paragraph3: 'MT Makina TSY-150, çift motorlu tasarım ile standart olarak gelir. Opsiyonel özellikler: Kayış kasnaklı hidrolik kaplin, volanlı tasarım, rotor soğutma sistemi, otomatik yağlama ünitesi, farklı ölçülerde elek seçenekleri, hidrolik açılan elek sistemi, çıkış için helezon/konveyör/taşıma fanı entegrasyonu. Hurma çiftlikleri, zeytinlik bakımı, orman işletmeleri ve endüstriyel biomass tesisleri için güvenilir çözüm. CE sertifikalı.'
      },
      en: {
        intro: 'TSY-150 horizontal wood shredder provides superior performance on industrial scale with 1500 mm rotor length and 75-110 kW (2X) high motor power.',
        paragraph1: 'TSY-150 model provides fast shredding of tree trunks, thick branches, palm logs and dense woody waste with 75-110 kW (2X) powerful dual motor. With 1500 mm rotor length, it is an excellent solution for large-scale agricultural operations, biomass power plants, furniture factory waste recycling and wood pellet production facilities. Dual hydraulic piston feeding system guarantees safe processing of heavy and long materials.',
        paragraph2: 'TSY-150 shows superior performance in hard wood types, pine, oak and tropical tree species with advanced rotor design and high-quality steel blades. PLC-based automation system provides energy efficiency with real-time load monitoring and intelligent reverse algorithm. Operational time is kept to minimum with hydraulically opening screen box and quick maintenance system.',
        paragraph3: 'MT Makina TSY-150 comes standard with dual motor design. Optional features: Belt pulley hydraulic coupling, flywheel design, rotor cooling system, automatic lubrication unit, different size screen options, hydraulically opening screen system, auger/conveyor/blower fan integration for output. Reliable solution for palm farms, olive grove maintenance, forestry operations and industrial biomass facilities. CE certified.'
      },
      ru: {
        intro: 'Горизонтальный измельчитель древесины TSY-150 обеспечивает превосходную производительность в промышленном масштабе с длиной ротора 1500 мм и мощностью двух двигателей 75-110 кВт (2X).',
        paragraph1: 'Модель TSY-150 обеспечивает быстрое измельчение стволов деревьев, толстых веток, бревен пальм и плотных древесных отходов с мощными двумя двигателями 75-110 кВт (2X). С длиной ротора 1500 мм это отличное решение для крупных сельскохозяйственных операций, биомассовых электростанций, переработки отходов мебельных фабрик и заводов по производству древесных пеллет. Система подачи с двумя гидравлическими поршнями гарантирует безопасную обработку тяжелых и длинных материалов.',
        paragraph2: 'TSY-150 показывает превосходную производительность на твердых породах дерева, сосне, дубе и тропических видах деревьев благодаря усовершенствованной конструкции ротора и высококачественным стальным ножам. Система автоматизации на базе ПЛК обеспечивает энергоэффективность с мониторингом нагрузки в реальном времени и интеллектуальным алгоритмом реверса. Операционное время сведено к минимуму благодаря гидравлически открывающемуся ящику сита и системе быстрого обслуживания.',
        paragraph3: 'MT Makina TSY-150 поставляется стандартно с двухмоторной конструкцией. Дополнительные функции: Гидравлическая муфта со шкивом, конструкция с маховиком, система охлаждения ротора, автоматический блок смазки, опции сит разных размеров, гидравлически открывающаяся система сит, интеграция шнека/конвейера/вентилятора для выхода. Надежное решение для пальмовых ферм, обслуживания оливковых рощ, лесных хозяйств и промышленных биомассовых объектов. Сертифицировано CE.'
      },
      ar: {
        intro: 'توفر آلة تقطيع الخشب الأفقية TSY-150 أداءً فائقًا على النطاق الصناعي مع طول دوار 1500 مم وقوة محرك عالية 75-110 كيلووات (2X).',
        paragraph1: 'يوفر طراز TSY-150 تقطيعًا سريعًا لجذوع الأشجار والفروع السميكة وجذوع النخيل والنفايات الخشبية الكثيفة بمحرك مزدوج قوي 75-110 كيلووات (2X). مع طول دوار 1500 مم، إنه حل ممتاز للعمليات الزراعية واسعة النطاق ومحطات طاقة الكتلة الحيوية وإعادة تدوير نفايات مصانع الأثاث ومرافق إنتاج حبيبات الخشب. يضمن نظام التغذية ذو المكبسين الهيدروليكيين معالجة آمنة للمواد الثقيلة والطويلة.',
        paragraph2: 'يُظهر TSY-150 أداءً فائقًا في أنواع الخشب الصلب والصنوبر والبلوط وأنواع الأشجار الاستوائية مع تصميم دوار متقدم وشفرات فولاذية عالية الجودة. يوفر نظام الأتمتة القائم على PLC كفاءة في استهلاك الطاقة مع مراقبة الحمل في الوقت الفعلي وخوارزمية عكسية ذكية. يتم الحفاظ على الوقت التشغيلي عند الحد الأدنى مع صندوق الشاشة الذي يفتح هيدروليكيًا ونظام الصيانة السريعة.',
        paragraph3: 'يأتي MT Makina TSY-150 قياسيًا مع تصميم محرك مزدوج. ميزات اختيارية: وصلة هيدروليكية بكرة حزام، تصميم دولاب الموازنة، نظام تبريد الدوار، وحدة تشحيم تلقائي، خيارات شاشة بأحجام مختلفة، نظام شاشة يفتح هيدروليكيًا، تكامل لولب/ناقل/مروحة منفاخ للإخراج. حل موثوق لمزارع النخيل وصيانة بساتين الزيتون وعمليات الغابات والمرافق الصناعية للكتلة الحيوية. معتمد CE.'
      }
    },
    'TSY-200': {
      tr: {
        intro: 'TSY-200 yatay ağaç parçalama makinesi, 2000 mm rotor boyu ve 90-200 kW (2X) ultra güçlü motorları ile endüstriyel ölçekte maksimum kapasite sağlar.',
        paragraph1: 'TSY-200 model, 90-200 kW (2X) ultra güçlü çift motor ile ağaç kütükleri, kalın gövdeler, hurma ağacı gövdeleri ve en sert odunsu atıkların yoğun işlenmesini sağlar. 2000 mm rotor boyu ile büyük biyokütle enerji santralleri, endüstriyel odun pelet fabrikaları, kereste fabrikası atık yönetimi ve geniş ölçekli orman işletmeleri için ideal çözümdür. Üçlü hidrolik pistonlu besleme sistemi ve geniş besleme ağzı, çok büyük malzemelerin kesintisiz işlenmesini garanti eder.',
        paragraph2: 'Premium segment TSY-200, özel alaşımlı çelik rotor bıçakları ve takviyeli rotor gövdesi ile tropik sert ağaçlar, egzotik ahşap türleri ve en yoğun odunsu malzemelerde mükemmel kesim performansı gösterir. Gelişmiş PLC ve HMI dokunmatik panel ile otomasyon, gerçek zamanlı performans izleme, enerji optimizasyonu ve bakım hatırlatıcıları sunar. Hızlı açılır elek sistemi ve modüler bakım teknolojisi ile operasyonel verimlilik maksimize edilir.',
        paragraph3: 'MT Makina TSY-200, ağır hizmet tipi çelik şase ve çift yataklı rotor sistemi ile 7/24 kesintisiz çalışma kapasitesine sahiptir. Çift motorlu tasarım standart gelir. Tüm opsiyonel özellikler mevcuttur: Kayış kasnaklı hidrolik kaplin, volanlı tasarım, rotor soğutma sistemi, çift hatlı otomatik yağlama, toz bastırma ve aspirasyon sistemi, çıkış için helezon/konveyör/taşıma fanı entegrasyonu. Biyokütle pelet üretimi, biyokömür sanayii, MDF-OSB hammadde hazırlama için turnkey çözüm. CE-ISO 9001 sertifikalı.'
      },
      en: {
        intro: 'TSY-200 horizontal wood shredder provides maximum capacity on industrial scale with 2000 mm rotor length and 90-200 kW (2X) ultra-powerful motors.',
        paragraph1: 'TSY-200 model provides intensive processing of tree logs, thick trunks, palm tree trunks and hardest woody waste with 90-200 kW (2X) ultra-powerful dual motor. With 2000 mm rotor length, it is ideal solution for large biomass power plants, industrial wood pellet factories, lumber mill waste management and large-scale forestry operations. Triple hydraulic piston feeding system and wide feed opening guarantee uninterrupted processing of very large materials.',
        paragraph2: 'Premium segment TSY-200 shows excellent cutting performance in tropical hardwoods, exotic wood species and densest woody materials with special alloy steel rotor blades and reinforced rotor body. Advanced automation with PLC and HMI touch panel offers real-time performance monitoring, energy optimization and maintenance reminders. Operational efficiency is maximized with quick-opening screen system and modular maintenance technology.',
        paragraph3: 'MT Makina TSY-200 has 24/7 continuous operation capacity with heavy-duty steel chassis and dual bearing rotor system. Dual motor design comes standard. All optional features available: Belt pulley hydraulic coupling, flywheel design, rotor cooling system, dual-line automatic lubrication, dust suppression and aspiration system, auger/conveyor/blower fan integration for output. Turnkey solution for biomass pellet production, biochar industry, MDF-OSB raw material preparation. CE-ISO 9001 certified.'
      },
      ru: {
        intro: 'Горизонтальный измельчитель древесины TSY-200 обеспечивает максимальную производительность в промышленном масштабе с длиной ротора 2000 мм и ультрамощными двигателями 90-200 кВт (2X).',
        paragraph1: 'Модель TSY-200 обеспечивает интенсивную обработку бревен, толстых стволов, стволов пальм и самых твердых древесных отходов с ультрамощным двойным двигателем 90-200 кВт (2X). С длиной ротора 2000 мм это идеальное решение для крупных биомассовых электростанций, промышленных заводов по производству древесных пеллет, управления отходами лесопильных заводов и крупномасштабных лесных хозяйств. Система подачи с тройным гидравлическим поршнем и широкое отверстие подачи гарантируют непрерывную обработку очень больших материалов.',
        paragraph2: 'TSY-200 премиум-сегмента показывает отличную производительность резки на тропических твердых породах, экзотических видах дерева и самых плотных древесных материалах благодаря роторным ножам из специальной легированной стали и усиленному корпусу ротора. Передовая автоматизация с ПЛК и сенсорной панелью HMI предлагает мониторинг производительности в реальном времени, оптимизацию энергопотребления и напоминания о техническом обслуживании. Операционная эффективность максимизируется благодаря быстро открывающейся системе сит и модульной технологии обслуживания.',
        paragraph3: 'MT Makina TSY-200 имеет круглосуточную непрерывную работу со сверхпрочным стальным шасси и роторной системой с двойными подшипниками. Конструкция с двумя двигателями идет стандартно. Все дополнительные функции доступны: Гидравлическая муфта со шкивом, конструкция с маховиком, система охлаждения ротора, двухлинейная автоматическая смазка, система подавления пыли и аспирации, интеграция шнека/конвейера/вентилятора для выхода. Комплексное решение для производства биомассовых пеллет, промышленности биоугля, подготовки сырья МДФ-ОСБ. Сертифицировано CE-ISO 9001.'
      },
      ar: {
        intro: 'توفر آلة تقطيع الخشب الأفقية TSY-200 أقصى سعة على النطاق الصناعي مع طول دوار 2000 مم ومحركات فائقة القوة 90-200 كيلووات (2X).',
        paragraph1: 'يوفر طراز TSY-200 معالجة مكثفة لجذوع الأشجار والجذوع السميكة وجذوع أشجار النخيل وأصعب النفايات الخشبية بمحرك مزدوج فائق القوة 90-200 كيلووات (2X). مع طول دوار 2000 مم، إنه حل مثالي لمحطات طاقة الكتلة الحيوية الكبيرة ومصانع حبيبات الخشب الصناعية وإدارة نفايات مصانع الأخشاب وعمليات الغابات واسعة النطاق. يضمن نظام التغذية بالمكبس الهيدروليكي الثلاثي وفتحة التغذية الواسعة معالجة مستمرة للمواد الكبيرة جدًا.',
        paragraph2: 'يُظهر TSY-200 من الفئة الممتازة أداء قطع ممتازًا في الأخشاب الصلبة الاستوائية وأنواع الخشب الغريبة وأكثف المواد الخشبية مع شفرات دوار من الفولاذ المقاوم للصدأ السبائكي الخاص وجسم دوار معزز. توفر الأتمتة المتقدمة مع PLC ولوحة اللمس HMI مراقبة الأداء في الوقت الفعلي وتحسين الطاقة وتذكيرات الصيانة. يتم زيادة الكفاءة التشغيلية إلى أقصى حد مع نظام الشاشة سريع الفتح وتقنية الصيانة المعيارية.',
        paragraph3: 'تتميز MT Makina TSY-200 بقدرة تشغيل مستمر على مدار الساعة طوال أيام الأسبوع مع هيكل فولاذي للخدمة الشاقة ونظام دوار بمحمل مزدوج. يأتي التصميم ثنائي المحرك قياسيًا. جميع الميزات الاختيارية متاحة: وصلة هيدروليكية بكرة حزام، تصميم دولاب الموازنة، نظام تبريد الدوار، تشحيم تلقائي ثنائي الخط، نظام قمع الغبار والشفط، تكامل لولب/ناقل/مروحة منفاخ للإخراج. حل جاهز لإنتاج حبيبات الكتلة الحيوية وصناعة الفحم الحيوي وإعداد المواد الخام MDF-OSB. معتمد CE-ISO 9001.'
      }
    }
  },
